PROD-934 I can not visualize code in plugin editor in the RTL language mode
buddyboss/buddyboss-platform pull request #1238
Opened 2020-07-20 16:00 UTC by shohelbuddyboss

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

`wp-content/plugins/buddyboss-platform/src/bp-templates/bp-nouveau/buddypress-functions.php`
Checked if page is not plugin or theme editor page, then Enqueue css file

Fixes #1237 .

### Changelog entry

> Fixed: I can not visualize code in plugin editor in the RTL language mode #1237

2020-07-22 08:32 UTC, mehulkaklotar commented on src/bp-templates/bp-nouveau/buddypress-functions.php
> +		if ( $page == 'plugin-editor.php' || $page == 'theme-editor.php' ) {
```suggestion
		if ( $page === 'plugin-editor.php' || $page === 'theme-editor.php' ) {
```

2020-07-22 09:32 UTC, mehulkaklotar commented on src/bp-templates/bp-nouveau/buddypress-functions.php
> +	public function enqueue_styles( $page ) {
@shohelbuddyboss `bp_enqueue_scripts` hook doesn't have `$page` param? is it going to work?

May be you will need global variable to check that? some thing like $current_screen. https://deluxeblogtips.com/get-admin-screen-information/

Check for network screen as well.

2020-10-30 09:00 UTC, chetansatasiya requested changes
@shohel Please do the changes requested by mehul.

2022-12-21 08:55 UTC, KartikSuthar approved these changes

2023-01-25 10:31 UTC, merged