777 - GIPHY Enhancement
buddyboss/buddyboss-platform pull request #1361
Opened 2020-08-16 13:16 UTC by buddy4kp

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #777 

### How to test the changes in this Pull Request:

1. Add GIF file at any place Activity Feed or Message
2. Check at Backend Media, it is getting upload at in it.
3. GIF should direct the show from GIPHY

### Proof Screenshots or Video

https://www.loom.com/share/7407591fe49b49a7a423dc82875185d1

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2020-09-07 03:42 UTC, chetansatasiya approved these changes
@krunal-buddyboss code looks good to me.

@ankitguptaindia Need to test below things.

1. All Previous Giphy should work properly without any isssues.
2. New change will not create any media in WordPress Media.
3. Need to test on Edit activity & all the places where we allowed the Giphy.

2020-09-07 03:42 UTC, chetansatasiya commented
@krunal-buddyboss Merge the dev branch here and fix the conflict please.

2020-09-14 12:03 UTC, krunal-buddyboss commented
@chetansatasiya I have merged the dev branch here and also resolved the conflict, Please check once when you get chance for it. Thanks.

2020-10-07 04:11 UTC, chetansatasiya submitted a review, later dismissed
@ankitguptaindia Need testing here.

2020-11-06 09:29 UTC, chetansatasiya requested changes
@krunal-buddyboss Run the PHPCS and fix all the spacing errors and all.

2020-11-06 09:29 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/messages/ajax.php
> +			$preview_url = ( is_int( $gif_data['still'] )) ? wp_get_attachment_url( $gif_data['still'] ) : $gif_data['still'];
```suggestion
			$preview_url = ( is_int( $gif_data['still'] ) ) ? wp_get_attachment_url( $gif_data['still'] ) : $gif_data['still'];
```

2020-11-09 10:27 UTC, chetansatasiya approved these changes
@krunal-buddyboss Approved!

2020-11-09 16:58 UTC, sumitbuddyboss commented
Hello @krunal-buddyboss 

Fixed > I've checked the blow points that you shared and it's working as expected, for the proof please check the video.
1) Add GIF file at any place Activity Feed or Message
2) Check at Backend Media, it is getting upload at in it.
3) GIF should direct the show from GIPHY
**Video:**
https://www.loom.com/share/8a0fcfc109314ce5b0c1ff4c5ffc5220

@chetansatasiya  Ready to release 🚀 

CC @ankitguptaindia

2020-11-17 07:29 UTC, mehulkaklotar approved these changes

2020-11-17 07:29 UTC, merged