Fix 1455
buddyboss/buddyboss-platform pull request #1462
Opened 2020-09-07 15:01 UTC by dipskakadiya

Added code to support global search for page and other custom post types

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added search support for page and other custom post types. 

### How to test the changes in this Pull Request:

1. Click on 'search' icon in top navigation menu bar
2. Type in search term with page or Custom CPT like course, lesson etc.
3. See error - no search results returned.

### Proof Screenshots or Video

<img width="1351" alt="Screenshot 2020-09-07 at 8 30 38 PM" src="https://user-images.githubusercontent.com/2979084/92400121-0068db80-f149-11ea-9951-17722c4640ae.png">

<img width="1177" alt="Screenshot 2020-09-07 at 8 28 16 PM" src="https://user-images.githubusercontent.com/2979084/92400135-078fe980-f149-11ea-96d6-8061ec0853fc.png">

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Added search support for page and other custom post types

.

2020-09-08 03:56 UTC, chetansatasiya requested changes
@dipskakadiya I don't think we need this changes as I tested in my local with the dev branch and it's working fine without any issues.

FYI: For this we have a settings here https://prnt.sc/uddkuz to enable/disable for the specific post types.

Let me know if I am undestanding wrong here.

2020-09-08 06:47 UTC, dipskakadiya commented
@chetansatasiya As We discuss, This issue for the new Setup. With the default setting, it was not working so revise my solution. Please review it.

2020-09-08 06:51 UTC, chetansatasiya commented on src/bp-search/plugins/search-cpt/index.php
> +	$custom_handler_cpts = array( 'post', 'forum', 'topic', 'reply', 'post', 'page' );
```suggestion
	$custom_handler_cpts = array( 'post', 'forum', 'topic', 'reply', 'page' );
```

@dipskakadiya Remove duplicate `post`

2020-09-08 06:52 UTC, chetansatasiya requested changes
@dipskakadiya do the requested changes

2020-09-08 06:57 UTC, chetansatasiya submitted a review, later dismissed
@dipskakadiya Looks good.

@ankitguptaindia Need to test this with the fresh setup and also with the existing site as well.

2020-09-22 07:46 UTC, mehulkaklotar approved these changes
@dipskakadiya this looks good to me as well! 

@ankitguptaindia needs testing here!

2020-09-22 07:47 UTC, mehulkaklotar submitted a review, later dismissed

2020-10-09 06:56 UTC, merged