Post Data getting lost if user edit any other post while creating new post. #1494
buddyboss/buddyboss-platform pull request #1505
Opened 2020-09-16 12:14 UTC by shohelbuddyboss

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1494 .

### Changelog entry

> If there any draft post, edit activity post will not working until the main post content delete or publish.

2020-09-17 09:53 UTC, mehulkaklotar reviewed
@shohelbuddyboss you will need different approach here to fix this. There should be one global variable attached to PostForm object and then there should be one wrapper function to check all details if post form has draft or not. This implementation will not work. 

Let's have discussion about this change before you proceed with it.

2020-09-17 09:53 UTC, mehulkaklotar commented on src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
> +			this.checkDraftContentInPostForm();
@shohelbuddyboss We should make use of Backbone events here like this https://github.com/buddyboss/buddyboss-platform/blob/dev/src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js#L2505

https://github.com/buddyboss/buddyboss-platform/blob/dev/src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js#L2532

2020-09-17 09:53 UTC, mehulkaklotar commented on src/bp-templates/bp-nouveau/js/buddypress-activity-post-form.js
> +			var countAttachmets = $whatsNewAttachments.find( '.dz-preview' ).length;
@shohelbuddyboss can you check this without `dz-preview` class elements length and make use of dropzone objects to find if any media and document is added or not in the object?

2020-10-30 09:21 UTC, chetansatasiya requested changes
@shohel Need to make the changes as mehul suggested.

2021-09-02 13:25 UTC, jitendrabanjara1991 commented
@chetansatasiya 
As per request changes, I have changed code and some issue with draft content so fixed it.
Here is the video for the proof - https://screencast-o-matic.com/watch/crQnl1VQOIL
@sourabhmatolia can you send check alert text which displaying as popup? Text something like this - **You have a draft post, publish the draft post first in order to edit any activity.**
Please let me know need to change anything else
Thanks.

2022-11-22 09:52 UTC, closed without merging