1557 - Fixed the issue with group, members page loading with RTL lang…
buddyboss/buddyboss-platform pull request #1597
Opened 2020-10-06 08:37 UTC by janakkaneriya007

…uages

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1557.

### How to test the changes in this Pull Request:

1. Change groups, members page slug to Arabic, Persian OR any RTL languages
2. Go to groups, members page
3. click on URL bar and try to refresh by hitting enter key

### Proof Screenshots or Video

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2020-10-23 07:59 UTC, dipskakadiya submitted a review, later dismissed
@janakkaneriya007 Approved. Please merge this PR to `dev` branch and assign to @mehulkaklotar for final review

2020-10-27 14:48 UTC, mehulkaklotar requested changes

2020-10-27 14:48 UTC, mehulkaklotar commented on src/bp-core/bp-core-catchuri.php
> +
@janakkaneriya007 please fix the phpcs errors

```
L88: Squiz.Commenting.InlineComment.InvalidEndChar: Inline comments must end in full-stops, exclamation marks, or question marks

L90: Squiz.WhiteSpace.SuperfluousWhitespace.EmptyLines: Functions must not contain multiple empty lines in a row; found 2 empty lines

L91: Squiz.WhiteSpace.SuperfluousWhitespace.EndLine: Whitespace found at end of line
```

2020-10-27 14:48 UTC, mehulkaklotar commented on src/bp-forums/core/options.php
> +
@janakkaneriya007 

```
L486: Generic.ControlStructures.InlineControlStructure.NotAllowed: Inline control structures are not allowed
L489: PEAR.Functions.FunctionCallSignature.SpaceAfterCloseBracket: Space after closing parenthesis of function call prohibited
L489: PEAR.Functions.FunctionCallSignature.SpaceBeforeCloseBracket: Expected 1 spaces before closing parenthesis; 0 found
L489: Squiz.WhiteSpace.SemicolonSpacing.Incorrect: Space found before semicolon; expected ");" but found ") ;"
L490: Squiz.WhiteSpace.SuperfluousWhitespace.EndLine: Whitespace found at end of line
```

2020-10-27 14:48 UTC, mehulkaklotar commented on src/bp-forums/core/options.php
> +
@janakkaneriya007 

1. what if `$retval` is empty string?
2. what if function return value from filter `bbp_maybe_get_root_slug` is not urldecoded.

2021-09-28 13:02 UTC, janakkaneriya007 commented
Fixed here: https://github.com/buddyboss/buddyboss-platform/pull/1215

2021-09-28 13:02 UTC, closed without merging