Fix the issue current class is not being added to the <li>
buddyboss/buddyboss-platform pull request #1609
Opened 2020-10-08 16:00 UTC by krunal-buddyboss

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1608 

### How to test the changes in this Pull Request:

1. Go to https://demos.buddyboss.com/online-communities
2. Click on 'my timeline' menu item from buddypanel
3. you will be redirected to your timeline.
4. But the menu in the buddypanel doesn't highlight.

### Proof Screenshots or Video

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2020-10-09 04:54 UTC, chetansatasiya requested changes

2020-10-09 04:54 UTC, chetansatasiya commented on src/bp-core/bp-core-filters.php
> +			if ( in_array( $current, $domain_arr ) ) {
@krunal-buddyboss No need seprate variable for this.

```suggestion
			if ( in_array( $current, array( bp_loggedin_user_domain() ) ) ) {
```

2020-10-15 13:11 UTC, dipskakadiya requested changes

2020-10-15 13:11 UTC, dipskakadiya commented on src/bp-core/bp-core-filters.php
> +							}
```suggestion
                                                                  $menu_item->classes = is_array( $menu_item->classes ) ? $menu_item->classes : array() ;
								$menu_item->classes[] = 'current_page_item';
								$menu_item->classes[] = 'current-menu-item';
							
```

2020-10-15 13:50 UTC, dipskakadiya approved these changes
Good to merged 👍

2020-10-15 13:56 UTC, dipskakadiya approved these changes
Good to merged 👍

2020-10-15 15:13 UTC, ankitguptaindia commented
@dipskakadiya @sourabhmatolia Working on this. 
Will Add final update in morning.

2020-10-16 06:45 UTC, ankitguptaindia commented
@sourabhmatolia 

Above mentioned issue has been fixed. 
https://www.loom.com/share/fab54d48250b41f49fed2c40ec53956e

Ready to Merge 🚀

2020-10-16 06:46 UTC, ankitguptaindia approved these changes
**Closing Remark-** 

- [x] Read PR description

- [x] Checked Description on related Issue

- [x] Pulled respective branch and checked module by pull stable branch (Checked the Before Fix & After Fix differences)

- [ ] Tested negative test scenario

- [ ] Updated Labels as per current status

**Final Update-** Ready to merge 🚀

2020-10-16 06:47 UTC, sourabhmatolia approved these changes

2020-10-16 06:47 UTC, merged