#1610 tags are lost upon updating discussion
buddyboss/buddyboss-platform pull request #1641
Opened 2020-10-16 13:16 UTC by sadrul

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1610

### How to test the changes in this Pull Request:

1. Create a discussion with a few tags
2. Edit the discussion
3. See the tags in tags section

### Proof Screenshots or Video

https://www.loom.com/share/0e45a53eff144c4eaaecfcb24ba920e8

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2020-10-30 09:22 UTC, dipskakadiya requested changes
@sadrul Can we fix minor escaping missing and also resolve conflict.

2020-10-30 09:22 UTC, dipskakadiya commented on src/bp-forums/templates/default/bbpress/form-topic.php
> +							<input type="hidden" value="<?php echo $get_the_tags; ?>" name="bbp_topic_tags" class="bbp_topic_tags" id="bbp_topic_tags" >
@sadrul Can we use escaping function for `get_the_tags`
```suggestion
							<input type="hidden" value="<?php echo esc_attr( $get_the_tags ); ?>" name="bbp_topic_tags" class="bbp_topic_tags" id="bbp_topic_tags" >
```

2020-10-30 09:22 UTC, dipskakadiya commented on src/bp-forums/templates/default/bbpress/form-topic.php
> +										<option selected="selected" value="<?php echo $single_tag; ?>"><?php echo $single_tag; ?></option>
@sadrul Missing escaping function here too.

2020-12-29 13:39 UTC, sadrul commented
@dipskakadiya I updated accordingly. Linked buddyboss-theme PR
https://github.com/buddyboss/buddyboss-theme/pull/1136

2021-08-11 07:26 UTC, chetansatasiya requested changes
Need requested changes

2021-08-11 07:26 UTC, chetansatasiya commented on src/bp-forums/templates/default/bbpress/form-reply.php
> +							<select name="bbp_topic_tags_dropdown[]" class="bbp_topic_tags_dropdown" id="bbp_topic_tags_dropdown" placeholder="<?php esc_html_e( 'Type one or more tag, comma separated', 'buddyboss-theme'
```suggestion
							<select name="bbp_topic_tags_dropdown[]" class="bbp_topic_tags_dropdown" id="bbp_topic_tags_dropdown" placeholder="<?php esc_html_e( 'Type one or more tag, comma separated', 'buddyboss' ); ?>" autocomplete="off" multiple="multiple" style="width: 100%" tabindex="<?php bbp_tab_index(); ?>">
```

2021-08-11 08:16 UTC, KartikSuthar requested changes

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/replies/functions.php
> +	if ( !empty( $existing_terms ) ) {
```suggestion
	if ( ! empty( $existing_terms ) ) {
```

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/replies/functions.php
> +		if ( !empty( $terms ) ) {
```suggestion
		if ( ! empty( $terms ) ) {
```

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/replies/functions.php
> +		if ( !empty( $deleted_terms ) ) {
```suggestion
		if ( ! empty( $deleted_terms ) ) {
```

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/templates/default/bbpress/form-reply.php
> +						$get_the_tags = isset( $get_topic_id ) && !empty( $get_topic_id ) ? bbp_get_topic_tag_names( $get_topic_id ) : '';
```suggestion
						$get_the_tags = isset( $get_topic_id ) && ! empty( $get_topic_id ) ? bbp_get_topic_tag_names( $get_topic_id ) : '';
```

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/templates/default/bbpress/form-reply.php
> +								if( !empty( $get_the_tags ) ) {
```suggestion
								if ( ! empty( $get_the_tags ) ) {
```

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/templates/default/bbpress/form-reply.php
> +									foreach( $get_the_tags as $single_tag ) {
```suggestion
									foreach ( $get_the_tags as $single_tag ) {
```

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/templates/default/bbpress/form-topic.php
> +						$get_the_tags = isset( $get_topic_id ) && !empty( $get_topic_id ) ? bbp_get_topic_tag_names( $get_topic_id ) : '';
```suggestion
						$get_the_tags = isset( $get_topic_id ) && ! empty( $get_topic_id ) ? bbp_get_topic_tag_names( $get_topic_id ) : '';
```

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/templates/default/bbpress/form-topic.php
> +								if( !empty( $get_the_tags ) ) {
```suggestion
								if ( ! empty( $get_the_tags ) ) {
```

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/templates/default/bbpress/form-topic.php
> +									foreach( $get_the_tags as $single_tag ) {
```suggestion
									foreach ( $get_the_tags as $single_tag ) {
```

2021-08-11 08:16 UTC, KartikSuthar commented on src/bp-forums/replies/functions.php
> +		$deleted_terms = [];
```suggestion
		$deleted_terms = array();
```

2021-08-11 12:54 UTC, sadrul commented
@KartikSuthar @chetansatasiya done with change requests

2021-08-11 14:30 UTC, KartikSuthar approved these changes
@sadrul Merged to dev and pass to QA.

2021-08-11 14:55 UTC, sadrul commented
@mohit-buddyboss @sumitbuddyboss Merged into dev and ready for testing

2021-08-12 02:33 UTC, mohit-buddyboss commented
@sadrul 

Tested using dev branch of the platform. Tested this issue for other themes like 2020,2021 for older discussion as well as by creating new discussions. 

Video: https://loom.com/share/f4e1eb049e7142688e7517ac10c6cbfe

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @KartikSuthar 

Related Theme PR:
buddyboss/buddyboss-theme#1136

2021-08-25 13:53 UTC, JetalDobariya commented
Hello

I have tested this PR in QA Approved branch , Tags are appear in the Discussion while we Creating/Editing.
But I facing some issues like Tags are not getting deleted while we edit second time.

Here, I drop videos link for your reference, please check and let me know if you have any Query!
https://www.loom.com/share/2d87a0b69f3543ed995e0cb340b1d544

Thanks!

2021-08-31 09:49 UTC, sadrul commented
@JetalDobariya I fixed the issue you reported in above video (regarding remove tag). 
But as we discussed another issue that new tag does not add when tag exists with same slug https://i.imgur.com/sU8RO4b.png
I created a new issue for this bug https://github.com/buddyboss/buddyboss-platform/issues/2858

2021-08-31 10:34 UTC, JetalDobariya commented
Hello,

I did verify this PR's issue has been done in QA Approved branch, now tags are getting deleted.
See video : https://www.loom.com/share/0b8083d162e14cc989fcd3848f2c0a9f

Thanks!
Jetal!
CC : @sadrul

2021-09-01 10:25 UTC, merged