#1417 - Fix profile completion field data not updating""
buddyboss/buddyboss-platform pull request #1644
Opened 2020-10-16 14:51 UTC by chetansatasiya

This reverts commit 0b08d1365e0edebfb2ac3c5ff10a04ae0507c409.

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2020-10-23 04:23 UTC, mohit-buddyboss commented
@dipskakadiya 
Kindly review this PR and Related theme PR buddyboss/buddyboss-theme/pull/1137.

2020-10-23 07:28 UTC, dipskakadiya submitted a review, later dismissed
@chetansatasiya Approved. Merge this PR into `dev` and assign to @mohit-buddyboss

2020-10-23 08:24 UTC, dipskakadiya submitted a review, later dismissed
@chetansatasiya Approved

2020-10-23 09:18 UTC, chetansatasiya commented
@ankitguptaindia This is ready for testing merged changes to dev.

2020-10-26 19:31 UTC, mohit-buddyboss commented
@chetansatasiya 
FIXED> Tested this again on dev branch after latest merge. Also tested linked PR : buddyboss/buddyboss-theme/pull/1137 related issue.
Tested this with and without Redis enable on server and by activating and deactivating Redis object cache Plugin as well as enabling and disabling website object cache. Also, by adding and deleting Profile fields.

Videos:
https://www.loom.com/share/c43a6df0193245e49778fe2b1cd9d36b - without redis enable
https://www.loom.com/share/43ad7617101f4189b1b2f6946af72b36 - with Redis enable and Plugin active
https://www.loom.com/share/115acbe66ce145edad4d28d752bd329c - with cache active

@mehulkaklotar - Related issue is Fixed and PR is ready to merge.

2020-10-26 19:35 UTC, mohit-buddyboss approved these changes
Related issue is resolve now and PR is ready to merge.

@mehulkaklotar

2020-10-30 13:27 UTC, mehulkaklotar requested changes
@chetansatasiya please follow PHPCS here and fix all the lint errors.

2020-10-30 13:27 UTC, mehulkaklotar commented on src/bp-core/bp-core-functions.php
> +	return apply_filters( 'bp_xprofile_get_selected_options_user_progress', $response, $profile_groups, $profile_photo_type, $get_user_data );
@chetansatasiya please add filter doc here.

2020-10-30 13:27 UTC, mehulkaklotar commented on src/bp-core/bp-core-functions.php
> +				$total_count = $total_count + (int) $get_user_data['groups'][$group]['group_total_fields'];
```phpcs: WordPress.Arrays.ArrayKeySpacingRestrictions.NoSpacesAroundArrayKeys: Array keys must be surrounded by spaces unless they contain a string or an integer.```

2020-10-30 13:27 UTC, mehulkaklotar commented on src/bp-core/bp-core-functions.php
> +				if ( isset( $get_user_data['groups'][$group]['group_completed_fields'] ) && (int) $get_user_data['groups'][$group]['group_completed_fields'] > 0 ) {
```phpcs: WordPress.Arrays.ArrayKeySpacingRestrictions.NoSpacesAroundArrayKeys: Array keys must be surrounded by spaces unless they contain a string or an integer.```

2020-10-30 13:27 UTC, mehulkaklotar commented on src/bp-xprofile/bp-xprofile-functions.php
> +	$user_progress_arr = bp_xprofile_get_selected_options_user_progress( $settings );
@chetansatasiya change variable name here
```suggestion
	$user_progress_options = bp_xprofile_get_selected_options_user_progress( $settings );
```

2020-10-30 13:27 UTC, mehulkaklotar commented on src/bp-xprofile/bp-xprofile-functions.php
> +	if( isset( $user_progress_arr['total_fields'] ) && $user_progress_arr['total_fields'] <= 0  ){
```suggestion
	if( isset( $user_progress_options['total_fields'] ) && $user_progress_options['total_fields'] <= 0  ){
```

2020-10-30 13:27 UTC, mehulkaklotar commented on src/bp-xprofile/bp-xprofile-functions.php
> +	$user_progress = bp_xprofile_get_user_progress_formatted( $user_progress_arr );
```suggestion
	$user_progress = bp_xprofile_get_user_progress_formatted( $user_progress_options );
```

2020-10-30 13:27 UTC, mehulkaklotar commented on src/bp-xprofile/classes/class-bp-xprofile-profile-completion-widget.php
> +		$user_progress                  = bp_xprofile_get_user_profile_progress_data( $settings );
check phpcs here

2020-11-02 13:30 UTC, ankitguptaindia commented
@chetansatasiya Can you update after @mehulkaklotar suggestion so we can add in upcoming release?
As this is already tested by QA.


@mohit-buddyboss keep eye on this if we can add in next release after update by Chetan.

2020-11-02 13:53 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +	return apply_filters( 'bp_core_profile_completion_steps_options', $options );
done

2020-11-02 13:59 UTC, chetansatasiya commented on src/bp-xprofile/bp-xprofile-functions.php
> +	$user_progress = bp_xprofile_get_user_progress_formatted( $user_progress_arr );
done

2020-11-02 13:59 UTC, chetansatasiya commented on src/bp-xprofile/bp-xprofile-functions.php
> +	if( isset( $user_progress_arr['total_fields'] ) && $user_progress_arr['total_fields'] <= 0  ){
done

2020-11-02 13:59 UTC, chetansatasiya commented on src/bp-xprofile/bp-xprofile-functions.php
> +	$user_progress_arr = bp_xprofile_get_selected_options_user_progress( $settings );
done

2020-11-02 14:00 UTC, chetansatasiya commented on src/bp-xprofile/classes/class-bp-xprofile-profile-completion-widget.php
> +		$user_progress                  = bp_xprofile_get_user_profile_progress_data( $settings );
done

2020-11-02 14:08 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +	return apply_filters( 'bp_xprofile_get_selected_options_user_progress', $response, $profile_groups, $profile_photo_type, $get_user_data );
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +				if ( isset( $get_user_data['groups'][$group]['group_completed_fields'] ) && (int) $get_user_data['groups'][$group]['group_completed_fields'] > 0 ) {
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +				$total_count = $total_count + (int) $get_user_data['groups'][$group]['group_total_fields'];
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +				$response['groups'][$group] = $get_user_data['groups'][$group];
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +			if ( isset( $get_user_data['groups'][$group] ) ) {
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +					$total_completed_count = $total_completed_count + 1;
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +				if ( isset( $get_user_data['photo_type']['cover_photo']['is_uploaded'] ) &&  1 === (int) $get_user_data['photo_type']['cover_photo']['is_uploaded'] ) {
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +				$total_count = $total_count + 1;
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +					$total_completed_count = $total_completed_count + 1;
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +				if ( isset( $get_user_data['photo_type']['profile_photo']['is_uploaded'] ) &&  1 === (int) $get_user_data['photo_type']['profile_photo']['is_uploaded'] ) {
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +				$total_count = $total_count + 1;
done

2020-11-02 14:12 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +	$steps_options     = bp_core_profile_completion_steps_options();
done

2020-11-03 06:50 UTC, chetansatasiya commented
@mehulkaklotar All of requested changes done. It's ready for release.

2020-11-03 08:40 UTC, mohit-buddyboss commented
@chetansatasiya 
After latest changes tested again it is working as before and as expected.

@mehulkaklotar @ankitguptaindia

2020-11-03 13:08 UTC, mehulkaklotar approved these changes
approved! 🚀

2020-11-03 13:10 UTC, merged