1299 - Fixed the notification date
buddyboss/buddyboss-platform pull request #1663
Opened 2020-10-20 17:06 UTC by janakkaneriya007

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1299 

### How to test the changes in this Pull Request:

1. Inside admin, Settings > General, set the timezone to UTC -4 or Los Angeles, or whatever timezone except UTC+0
2. Post a reply using a different account
3. Login to the account that started the discussion and you should see a notification
4. Click the notification bell located at the top right corner of the page and you'll see that the timestamp is incorrect.

### Proof Screenshots or Video

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

2020-10-23 07:06 UTC, dipskakadiya approved these changes
@janakkaneriya007 Approved.  Please merge this branch to `dev` and then assign to @mehulkaklotar

2020-10-28 10:42 UTC, mehulkaklotar requested changes

2020-10-28 10:42 UTC, mehulkaklotar commented on src/bp-forums/notifications.php
> +		'date_notified'    => bp_core_current_time(),
@janakkaneriya007 can we use `post_date_gmt` instead?

```suggestion
		'date_notified'    => get_post( $reply_id )->post_date_gmt,
```

2020-10-28 10:59 UTC, mehulkaklotar approved these changes

2020-10-28 11:04 UTC, merged