Media search result enhancement
buddyboss/buddyboss-platform pull request #1738
Opened 2020-11-05 10:06 UTC by amincdev

…preview image full width

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2020-11-10 12:14 UTC, amincdev commented
@chetansatasiya Can you please review this?

2020-11-12 03:59 UTC, chetansatasiya requested changes
@amincdev Do the changes as requested and fix the conflict and then merge in dev.

2020-11-12 03:59 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/search/loop/albums-ajax.php
> +						<img src="<?php echo buddypress()->plugin_url; ?>bp-templates/bp-nouveau/images/placeholder.png" alt="<?php echo wp_kses_post( bp_get_album_title() ); ?>" />
```suggestion
						<img src="<?php echo esc_url( buddypress()->plugin_url ); ?>bp-templates/bp-nouveau/images/placeholder.png" alt="<?php echo wp_kses_post( bp_get_album_title() ); ?>" />
```

2020-11-12 03:59 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/search/loop/albums.php
> +							<img src="<?php echo buddypress()->plugin_url; ?>bp-templates/bp-nouveau/images/placeholder.png" alt="<?php echo wp_kses_post( bp_get_album_title() ); ?>" />
Same here needs escaping.

2020-11-12 12:08 UTC, amincdev commented on src/bp-templates/bp-nouveau/buddypress/search/loop/albums-ajax.php
> +						<img src="<?php echo buddypress()->plugin_url; ?>bp-templates/bp-nouveau/images/placeholder.png" alt="<?php echo wp_kses_post( bp_get_album_title() ); ?>" />
@chetansatasiya  Changes added

2020-11-12 12:08 UTC, amincdev commented on src/bp-templates/bp-nouveau/buddypress/search/loop/albums.php
> +							<img src="<?php echo buddypress()->plugin_url; ?>bp-templates/bp-nouveau/images/placeholder.png" alt="<?php echo wp_kses_post( bp_get_album_title() ); ?>" />
@chetansatasiya Changes added

2020-11-16 00:59 UTC, chetansatasiya approved these changes
@amincdev Approved!!!

2020-11-16 01:00 UTC, chetansatasiya commented
@amincdev Merge in dev and add to testing.

2020-11-16 06:44 UTC, amincdev commented
@ankitguptaindia Merged in `dev` and ready for testing.

2020-11-17 08:36 UTC, sumitbuddyboss commented
Hello @amincdev 

Fixed > I've checked in dev branch and the Below points are working as expected, For proof please check the video.
1) Check the result with no image should have a placeholder now
2) Loading thumbnail version of images now
3) Responsive layout improved

Video:
https://www.loom.com/share/f213f5acde354f9dbe7d6ebe75bb4fe5

@chetansatasiya 
Ready for release 🚀 

CC @ankitguptaindia

2020-11-17 09:22 UTC, merged