REST API Fixes and Enhancement
buddyboss/buddyboss-platform pull request #1748
Opened 2020-11-09 12:25 UTC by KartikSuthar

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

Fixes #1373
Fixes #1741 
Fixes #1424

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

2020-11-09 13:18 UTC, ExoGeek reviewed
@KartikSuthar I've seen in the Projects dashboard that you plan to add the **_share_** functionnality. I don't know how you plan to implement that but the code from **line 603 to 628** of the function **create_item_permission_check** in the file **class-bp-rest-media-endpoint.php** may be a problem.

May I suggest to create a permission check as follow (for having access to a media) : 

1. The logged in user is the author of the attachment_id
2. **OR** the logged in user has already (read) access to the media (see bp_media.privacy) => this enable media sharing.

![image](https://user-images.githubusercontent.com/46819762/98545883-6df2ce80-2296-11eb-92c4-0d97806e2bc0.png)

2020-11-09 14:19 UTC, KartikSuthar commented
@ExoGeek Regarding your suggestions, 

1. I have already implemented `create_item_permission_check()` to check the current user is the author of the uploaded media here: https://github.com/buddyboss/buddyboss-platform/pull/1748/files#diff-ea9fff6b2037b919ceccab7dc7d1b711e39a1dd3f4e112b9d800d50daca3e264R603
2. We will update the API with the sharing module.

2020-11-10 01:34 UTC, chetansatasiya requested changes
@KartikSuthar Some places still spaces is not correct that need to make a proper.

2020-11-10 01:34 UTC, chetansatasiya commented on src/bp-document/classes/class-bp-rest-document-endpoint.php
> +		$attachment_document_id = (int) $wpdb->get_var( "SELECT DISTINCT d.id FROM {$bp->document->table_name} d WHERE d.attachment_id = {$attachment_id}" );
@KartikSuthar Create a seprate function so if anyone need document id via the attachment id they can get and not makea seprate query everywhere.

2020-11-10 09:59 UTC, ExoGeek commented on src/bp-media/classes/class-bp-rest-media-albums-endpoint.php
> +			'group_name'    => ( isset( $album->group_name ) ? $album->group_name : '' ),
Do not forget to add fields **visibility** and **group_name** into the method **get_item_schema**.

2020-11-10 10:00 UTC, ExoGeek commented on src/bp-media/classes/class-bp-rest-media-endpoint.php
> +			'group_name'      => ( isset( $media->group_name ) ? $media->group_name : '' ),
Do not forget to add fields **visibility** and **group_name** into the method **get_item_schema**.

2020-11-10 10:05 UTC, ExoGeek commented on src/bp-media/classes/class-bp-rest-media-albums-endpoint.php
>  			'user_email'    => $album->user_email,
Just a question : why this field "user_email" is added in the response. The email can be private and shouldn't be exposed so easily...

2020-11-10 13:09 UTC, ExoGeek approved these changes
It works ! Thanks.

2020-11-16 00:49 UTC, chetansatasiya approved these changes
@KartikSuthar 2 places needs enahancement. other then Looks good to me..!!

2020-11-16 00:49 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> +	if ( ! empty( $media_ids ) && empty( $bp_activity_post_update ) && ! isset( $_POST['edit'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Missing
@KartikSuthar use the `filter_input` to sanitize the `edit`

2020-11-16 00:49 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> +	if ( ! empty( $document_ids ) && empty( $bp_activity_post_update ) && ! isset( $_POST['edit'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Missing
@KartikSuthar Use sanitize on `edit`

2020-11-17 09:19 UTC, mehulkaklotar approved these changes

2020-11-17 09:19 UTC, merged