Added  notification when someone like a post /  activity #1721
buddyboss/buddyboss-platform pull request #1806
Opened 2020-11-20 07:22 UTC by shohel

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added  notification when someone like a post/activity

Fixes #1721 

### Changelog entry

> Added  notification when someone like a post /  activity

2021-09-08 10:48 UTC, KartikSuthar requested changes

2021-09-08 10:48 UTC, KartikSuthar commented on src/bp-activity/bp-activity-notifications.php
> +	bp_notifications_add_notification(
added pre-check here

```suggestion
	if ( empty( $activity->id ) || $activity->user_id === bp_loggedin_user_id() ) {
		return;
	}

	bp_notifications_add_notification(
```

2021-09-08 10:48 UTC, KartikSuthar commented on src/bp-activity/bp-activity-notifications.php
> +		case 'mark_activity_favorite':
```suggestion
		case 'activity_favorite':
```

2021-09-08 10:48 UTC, KartikSuthar commented on src/bp-activity/bp-activity-notifications.php
> + * @since BuddyBoss 1.5.6
```suggestion
 * @since BuddyBoss 1.7.8
```

2021-09-08 10:48 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/activity/ajax.php
> +		$activity     = new BP_Activity_Activity( $_POST['id'] );
```suggestion
		$activity = new BP_Activity_Activity( $_POST['id'] );
```

2021-09-14 07:04 UTC, sourabhmatolia commented
**UPDATE**

Need to decide how we go about this task. I will share an update soon.

2023-01-09 12:14 UTC, closed without merging