Fix/1713
buddyboss/buddyboss-platform pull request #1832
Opened 2020-11-26 05:37 UTC by chetansatasiya

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-03-11 12:56 UTC, chetansatasiya commented on src/bp-activity/bp-activity-functions.php
> +	if ( (empty( $r['content'] ) && empty($_POST['gif_data'])) || empty( $r['user_id'] ) || empty( $r['activity_id'] )  ) {
@jitendrabanjara1991 We need to remove this newly added condition.

2021-03-11 12:56 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/activity/ajax.php
> +	if ( empty( $_POST['content'] ) && empty($_POST['gif_data']) ) {
@jitendrabanjara1991 We need to remove this newly added condition.

2021-03-11 12:57 UTC, chetansatasiya reviewed
@jitendrabanjara1991 Need to rework on this and we need to make whatever happening with the media same we have to implement here.

2021-03-11 18:01 UTC, jitendrabanjara1991 commented
@chetansatasiya 
When any new gif will added from comment and reply then it will store in DB with &nbsp. So, Please check it and let me know if anything else.
Here is the video - https://screencast-o-matic.com/watch/creXFcVcudI
Thanks.

2021-03-15 10:50 UTC, mehulkaklotar requested changes
@jitendrabanjara1991 please do the changes requested.

2021-03-15 10:50 UTC, mehulkaklotar commented on src/bp-activity/bp-activity-functions.php
> +	if ( empty( $r['content'] ) || empty( $r['user_id'] ) || empty( $r['activity_id'] )  ) {
@jitendrabanjara1991 extra space at the of the condition here.

2021-03-15 10:50 UTC, mehulkaklotar commented on src/bp-media/bp-media-filters.php
> +//Check content empty or not for activity gif
please run your code changes though phpcs linting when you commit.

2021-03-15 10:50 UTC, mehulkaklotar commented on src/bp-templates/bp-nouveau/includes/activity/ajax.php
> +	$content = apply_filters( 'bb_is_activity_content_empty', $_POST );
I don't think we need to add &nbsp; here for activity if it contains gif only. we don't add &nbsp; for media and document when they added in activity if activity has no content in it. please remove this.

2021-03-15 16:59 UTC, jitendrabanjara1991 commented
Hello @mehulkaklotar 
cc - @chetansatasiya 
As per your suggestion, We changed it. So, Please check it and let me know if anything else.
I also run phpcs only for my changes.
Here is the video - https://screencast-o-matic.com/watch/creoD8VcCRS
Thanks.

2021-03-16 17:18 UTC, jitendrabanjara1991 commented
Hello @mehulkaklotar
cc - @chetansatasiya
Fixed - When media, document, and gif add to the reply of the comment in the activity, then Space should be added instead of this content(#8203;).
Here is the video - https://screencast-o-matic.com/watch/creDbiVcJo3
Thanks.

2021-03-24 05:59 UTC, chetansatasiya commented
@jitendrabanjara1991 Need to change as discussed introduce new filter and allow to create empty activity when media, document or gif added.

2021-05-18 13:45 UTC, jitendrabanjara1991 commented
@chetansatasiya 
cc - @KartikSuthar 
Fixed it. Here is the video - https://screencast-o-matic.com/watch/crhFICVfpq3
Please check it and let me know if anything else.
Thanks.

2021-05-28 12:53 UTC, KartikSuthar requested changes
@jitendrabanjara1991 Please do the following changes.

2021-05-28 12:53 UTC, KartikSuthar commented on src/bp-media/bp-media-filters.php
> +add_filter( 'bp_activity_entry_content', 'bp_media_activity_embed_gif' );
```suggestion
add_action( 'bp_activity_entry_content', 'bp_media_activity_embed_gif' );
```

2021-05-28 12:53 UTC, KartikSuthar commented on src/bp-media/bp-media-filters.php
>  }
```
function bp_media_activity_embed_gif() {

	// check if profile and groups activity gif support enabled.
	if ( ( buddypress()->activity->id === bp_get_activity_object_name() && ! bp_is_profiles_gif_support_enabled() ) || ( bp_is_active( 'groups' ) && buddypress()->groups->id === bp_get_activity_object_name() && ! bp_is_groups_gif_support_enabled() ) ) {
		return false;
	}

	echo bp_media_activity_embed_gif_content( bp_get_activity_id() );
}
```

2021-05-31 04:46 UTC, jitendrabanjara1991 commented
@KartikSuthar 
cc - @chetansatasiya
Request changes done
Thanks.

2021-06-02 11:23 UTC, KartikSuthar approved these changes
@jitendrabanjara1991 Code looks good to me. Please merged to dev and pass to QA.

2021-06-02 11:31 UTC, jitendrabanjara1991 commented
@KartikSuthar 
cc - @mohit-buddyboss @sumitbuddyboss 
Merged in dev and ready for testing.
Thanks.

2021-06-03 13:02 UTC, mohit-buddyboss commented
@jitendrabanjara1991 
. 
FIXED> Tested on dev branch of the platform.
Tested for the activity , activity comments , Group activity, group activity comments and for group forum and individual forum replies.
Tested this by uploading media, doc and GIF with or without text.
Now content (#(#8203;) is not appearing in database if user uploads only GIF instead of this blank entry appears. 

Activity and activity comments: https://www.loom.com/share/3dc9ec562bed4b239bf973cdb2d2b114
Group activity and comments : https://www.loom.com/share/e9f6b890e36240e8834fc5da1c241f8b
Edit activity and Forum replies : https://www.loom.com/share/2f097b0c28bc420d8e7e9c69c70419d2

In messages when we upload image, doc and GIF then it automatically add &nbsp; in content for that I created separate issue :https://github.com/buddyboss/buddyboss-platform/issues/2456

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @chetansatasiya @KartikSuthar

2021-06-03 13:02 UTC, chetansatasiya commented
@jitendrabanjara1991 fixed the conflict

2021-06-03 13:10 UTC, jitendrabanjara1991 commented
@chetansatasiya 
Fixed conflict.
Thanks

2021-06-03 13:13 UTC, merged