Removed function which prevents backslashes in content
buddyboss/buddyboss-platform pull request #1852
Opened 2020-12-01 10:46 UTC by janakkaneriya007

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1337 .

### How to test the changes in this Pull Request:

1. Go to the Forum
2. Reply on an existing discussion or create a new discussion with backslash example: wp-content\themes\buddyboss-theme
3. Navigate to the Activity
4. And see the backslash is not showing

### Proof Screenshots or Video
https://www.loom.com/share/2466b711c1ed4630bf99b610c38d0e2c

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2020-12-30 09:49 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> -add_filter( 'bp_get_activity_content_body', 'stripslashes_deep', 5 );
@janakkaneriya007 I don't think we need to remove this filter as I post the content into the activity `wp-content\themes\` then it showing the correct see here https://prnt.sc/wcvsb9 maybe something wrong with the discussion content.

2020-12-30 09:50 UTC, chetansatasiya reviewed
@janakkaneriya007 I don't think we need to remove this filter as I post the content into the activity wp-content\themes\ then it showing the correct see here https://prnt.sc/wcvsb9 maybe something wrong with the discussion content.

2022-04-15 07:58 UTC, chetansatasiya approved these changes

2022-12-23 13:04 UTC, KartikSuthar requested changes

2022-12-23 13:04 UTC, KartikSuthar commented on src/bp-activity/bp-activity-filters.php
> +add_filter( 'bbp_activity_reply_create_excerpt', 'addslashes', 5 );
Please move this filter on the file: src/bp-forums/activity.php

2022-12-30 11:02 UTC, KartikSuthar approved these changes

2023-01-25 10:31 UTC, merged