#1851 Redirect to groups directory page when user leaves a hidden group, otherwise showing 404
buddyboss/buddyboss-platform pull request #1979
Opened 2020-12-30 12:21 UTC by sadrul

### All Submissions:

* [x ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

When a regular user leaves a hidden group, a 404 page displays as the page reload. I updated the code to redirect to the groups directory page as suggested in this issue creator

Fixes #1851

### How to test the changes in this Pull Request:

1. Go into a hidden group (where you are a member)
2. Leave that group by clicking on the button "Leave Group"

### Proof Screenshots or Video

https://www.loom.com/share/5ef16adab1e04ab09293522753750fa8

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

2021-01-19 09:41 UTC, chetansatasiya requested changes

2021-01-19 09:41 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/groups/ajax.php
> +				if ( $group->status == 'hidden' ) {
@sadrul Use the strict comparision and other looks good to me.
```suggestion
				if (  'hidden' === $group->status ) {
```

2021-02-09 09:49 UTC, sadrul commented
@chetansatasiya I updated code to use the strict comparison

2021-02-17 06:18 UTC, chetansatasiya approved these changes

2021-02-17 06:25 UTC, chetansatasiya commented
@sadrul Merge in dev and add in testing.

2021-02-17 17:37 UTC, sadrul commented
@sumitbuddyboss Merged in dev. you can test

2021-02-22 06:31 UTC, mohit-buddyboss commented
@sadrul 

FIXED> Tested on dev branch. Now users are redirecting to Group listing page on Leaving Hidden Group.
Video: https://www.loom.com/share/90152bb0767a4bcd84995877cfc8df70

Related issue is resolve now and PR is ready to merge.

@chetansatasiya

2021-02-22 11:24 UTC, merged