Added fallback option to retrive group id
buddyboss/buddyboss-platform pull request #1995
Opened 2021-01-04 08:22 UTC by janakkaneriya007

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1657 .

### How to test the changes in this Pull Request:

{{group.name}} email token is not working in email notifications: http://prnt.sc/uwjk70

https://secure.helpscout.net/conversation/1299751429/101802

### Proof Screenshots or Video

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-01-05 09:20 UTC, chetansatasiya approved these changes

2021-01-05 09:21 UTC, chetansatasiya commented
@janakkaneriya007 Merge in dev and put in testing.

2021-01-05 09:26 UTC, dipskakadiya requested changes

2021-01-06 10:07 UTC, dipskakadiya approved these changes
@janakkaneriya007 Approved

2021-09-13 13:34 UTC, umohitbuddyboss commented
Verified Result - Blocked

Logged in with : tester1   and group Name : new

Due to - when user open any group and try to send the message to group members, User is not able to enter the text field

![image](https://user-images.githubusercontent.com/85428333/133092997-8a19b5cf-16f7-494d-8b91-7f54fc4d189a.png)

2022-12-16 10:44 UTC, closed without merging