Feature/2121
buddyboss/buddyboss-platform pull request #2132
Opened 2021-02-10 20:31 UTC by jitendrabanjara1991

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2121.

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

InProgress

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-03-23 19:32 UTC, jitendrabanjara1991 commented
Hello @chetansatasiya 
I have completed media and document migration task.
Here is the video - https://screencast-o-matic.com/watch/cre0qvVVbhG
Please check it and let me know if anything else.
Thanks.

2021-03-25 02:30 UTC, mehulkaklotar requested changes
@jitendrabanjara1991 please fix all the suggestions and again put it in review. I will review again once you finish your changes.

2021-03-25 02:30 UTC, mehulkaklotar commented on src/bp-activity/bp-activity-filters.php
> +	$get_offset          = filter_input( INPUT_POST, 'offset', FILTER_SANITIZE_NUMBER_INT );
```suggestion
	$offset          = filter_input( INPUT_POST, 'offset', FILTER_VALIDATE_INT );
```

2021-03-25 02:30 UTC, mehulkaklotar commented on src/bp-activity/bp-activity-filters.php
> +	$offset              = isset( $get_offset ) ? (int) ( $get_offset ) : 0;
```suggestion
```

2021-03-25 02:30 UTC, mehulkaklotar commented on src/bp-activity/bp-activity-filters.php
> +	$get_active_post_types = get_post_types( array( 'public' => true ) );
can we change the variable name `$get_active_post_types` to `$active_post_types` ? 

Whenever we get data from function which name suggests it is getting data, we just need that data's name not get,fetch,update etc in the variable name.

2021-03-25 02:30 UTC, mehulkaklotar commented on src/bp-activity/bp-activity-filters.php
> +/**
add empty line between two functions and please add proper commenting on each important line of codes what it does and describe it.

2021-03-25 02:30 UTC, mehulkaklotar commented on src/bp-activity/bp-activity-filters.php
> +		$get_activity_data   = bp_activity_get_specific( $args );
here too, we don't need `get` in variable name, eg. `$get_activity_data` -> `$activity_data`

2021-03-25 02:30 UTC, mehulkaklotar commented on src/bp-activity/bp-activity-filters.php
> + */
why do we need empty lines in between param docs?

2021-08-13 07:01 UTC, chetansatasiya commented
@jitendrabanjara1991 This is not working as expected as we test on a call with the group activity. So need to make sure it will work with every case.

2021-08-13 07:02 UTC, chetansatasiya requested changes
Migration has a issue so it's not migrating with group activity

2021-08-20 14:58 UTC, jitendrabanjara1991 commented
@chetansatasiya 
Fixed - group migration issue. - https://screencast-o-matic.com/watch/crjY29VjJvC
Right now I have added migration code in repair community section. So let me know it need to move with background process.
Thanks.

2021-08-24 10:53 UTC, shakilAshraful commented
@jitendrabanjara1991 My initial impression on this is that this issue **doesn't need any App Native change** as long as the fetch APIs (for medias, documents, videos) don't include medias/documents/videos posted with activity comments. This will most probably need API changes, but shouldn't require any App Native change.

cc. @KartikSuthar @chetansatasiya @sourabhmatolia

2021-08-31 06:42 UTC, jitendrabanjara1991 commented
We found another solution for this issue. So, we have created new PR for the same - https://github.com/buddyboss/buddyboss-platform/pull/2844. 
**What I have changed code in this PR?** - User will able to see comment for media/documents. Not able to do like/comment for the media. If user will add new media in child comment then user can not able to do like/comment.
So I am closing this PR now and will update on new PR.
cc - @firozwp @sourabhmatolia @KartikSuthar @chetansatasiya 
Thanks.

2021-08-31 06:42 UTC, closed without merging