Moderation > Make Block and Report button less prominent in the frontend
buddyboss/buddyboss-platform pull request #2237
Opened 2021-03-11 13:27 UTC by amincdev

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2222 .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-06-29 05:51 UTC, janakkaneriya007 commented
@amincdev I have finished backend changes you can design it new changes

2021-07-22 06:15 UTC, KartikSuthar requested changes

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-moderation/bp-moderation-functions.php
> +	return apply_filters( "bp_moderation_{$item_type}_report_content_type", __( 'Post', 'buddyboss' ), $item_id );
```suggestion
	return apply_filters( "bp_moderation_{$item_type}_report_content_type", esc_html__( 'Post', 'buddyboss' ), $item_id );
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-moderation/bp-moderation-functions.php
> +	return apply_filters( "bb_moderation_{$item_type}_report_button_text", __( 'Report', 'buddyboss' ), $item_id );
```suggestion
	return apply_filters( "bb_moderation_{$item_type}_report_button_text", esc_html__( 'Report', 'buddyboss' ), $item_id );
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-moderation/bp-moderation-functions.php
> +	return apply_filters( "bb_moderation_{$item_type}_reported_button_text", __( 'Reported', 'buddyboss' ), $item_id );
```suggestion
	return apply_filters( "bb_moderation_{$item_type}_reported_button_text", esc_html__( 'Reported', 'buddyboss' ), $item_id );
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-moderation/classes/class-bp-moderation-activity-comment.php
> +		return __( 'Report Comment', 'buddyboss' );
```suggestion
		return esc_html__( 'Report Comment', 'buddyboss' );
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-moderation/classes/class-bp-moderation-activity-comment.php
> +		return __( 'Comment', 'buddyboss' );
```suggestion
		return esc_html__( 'Comment', 'buddyboss' );
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-moderation/screens/block-member-form.php
> +                        </button>
Fix phpcbf

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-moderation/screens/content-report-form.php
> +                    </button>
Fix phpcbf

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-moderation/screens/reported-content-popup.php
> +</div>
Fix phpcbf

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/activity/template-tags.php
> +			'link_text'         => __( 'Reply', 'buddyboss' ),
```suggestion
			'link_text'         => esc_html__( 'Reply', 'buddyboss' ),
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/activity/template-tags.php
> +		'link_text'         => __( 'Delete', 'buddyboss' ),
```suggestion
		'link_text'         => esc_html__( 'Delete', 'buddyboss' ),
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/groups/template-tags.php
> +			'link_text'         => __( 'Reject', 'buddyboss' ),
```suggestion
			'link_text'         => esc_html__( 'Reject', 'buddyboss' ),
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/groups/template-tags.php
> +			'link_text'         => __( 'Reject', 'buddyboss' ),
```suggestion
			'link_text'         => esc_html__( 'Reject', 'buddyboss' ),
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/groups/template-tags.php
> +		/*
```suggestion
		/**
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/groups/template-tags.php
> +				'link_text'         => __( 'Remove Ban', 'buddyboss' ),
```suggestion
				'link_text'         => esc_html__( 'Remove Ban', 'buddyboss' ),
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/groups/template-tags.php
> +				'link_text'         => __( 'Kick &amp; Ban', 'buddyboss' ),
```suggestion
				'link_text'         => esc_html__( 'Kick &amp; Ban', 'buddyboss' ),
```

2021-07-22 06:15 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/groups/template-tags.php
> +				'link_text'         => __( 'Remove from group', 'buddyboss' ),
```suggestion
				'link_text'         => esc_html__( 'Remove from group', 'buddyboss' ),
```

2021-07-22 09:46 UTC, KartikSuthar approved these changes
@janakkaneriya007 Merged to dev and pass to QA.

2021-07-22 14:55 UTC, mohit-buddyboss commented
@janakkaneriya007  @amincdev 

Tested this on dev branch of the platform and theme. 
Tested with and without theme. 

All changes are implemented successfully and looking fine. PR is ready for release.

connected PR in theme : buddyboss/buddyboss-theme#1343

cc @sourabhmatolia @chetansatasiya

2021-07-23 05:36 UTC, merged