Email invite link for the Hidden Group Go To the 404 Page
buddyboss/buddyboss-platform pull request #2257
Opened 2021-03-22 06:46 UTC by manishpatolia

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2209 .

### How to test the changes in this Pull Request:

1.Create a hidden group
2.Send invitation
3.Check-in mail "visit button"

### Proof Screenshots or Video
The "Visit Group" button will hide when the group type is hidden.

Hidden Group
https://prnt.sc/10s6x1y

Privet/public group
https://prnt.sc/10s6wt7

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-09-21 02:57 UTC, chetansatasiya requested changes
Need changes

2021-09-21 02:57 UTC, chetansatasiya commented on src/bp-core/classes/class-bp-email-tokens.php
> +																	if ( 'hidden' !== $group->status ){
```suggestion
																	if ( 'hidden' !== $group->status ) {
```

2021-09-21 02:57 UTC, chetansatasiya commented on src/bp-core/classes/class-bp-email-tokens.php
> +																						<a class="mobile-button-center" href="<?php echo bp_get_group_permalink( $group ); ?>" target="_blank" rel="nofollow" style="font-family: 'Helvetica Neue', Helvetica, Arial, san
```suggestion
																						<a class="mobile-button-center" href="<?php echo esc_url( bp_get_group_permalink( $group ) ); ?>" target="_blank" rel="nofollow" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size: <?php echo esc_attr( floor( $settings['body_text_size'] * 0.875 ) . 'px' ); ?>;text-decoration: none;display: block;border-radius: 100px;text-align: center; height: 16px;line-height: 16px;background: <?php echo $settings['highlight_color']; ?>;color: #fff !important;width: 110px;padding: 8px;"><font style="color:#fff;"><?php _e( 'Visit Group', 'buddyboss' ); ?></font></a>
```

2021-09-21 04:55 UTC, manishpatolia commented on src/bp-core/classes/class-bp-email-tokens.php
> +																						<a class="mobile-button-center" href="<?php echo bp_get_group_permalink( $group ); ?>" target="_blank" rel="nofollow" style="font-family: 'Helvetica Neue', Helvetica, Arial, san
DOne

2021-09-21 04:58 UTC, chetansatasiya submitted a review, later dismissed

2021-12-01 07:02 UTC, sumitbuddyboss commented
Hello @manishpatolia 

I've checked in the fix branch and still, I'm getting the same issue, check the below video.

Video:
https://www.loom.com/share/5605f67e5d5b4aeaa1366366f1990117

Thank you

2021-12-08 08:21 UTC, jitendrabanjara1991 commented
@chetansatasiya 
Ready for review. Please check it
https://screencast-o-matic.com/watch/crljjYV2byd
cc - @KartikSuthar @sumitbuddyboss @firozwp

2021-12-08 13:18 UTC, jitendrabanjara1991 commented
@sourabhmatolia 
Here is one question - We don't see hidden group in group directory till member doesn't accept invitation. If member has not accepted group invitation then hidden group's link will redirect to 404. So, As per discussed with @chetansatasiya or @KartikSuthar we will send invitation link in the mail. ( [https://prnt.sc/22b3c5f](https://prnt.sc/22b3c5f) ) - Like this one - http://bbpltform.local/members/bb-arianna/groups/invites/

For more info please check below screenshot.
![image](https://user-images.githubusercontent.com/30429982/145214897-52effc11-eb97-43ee-addb-cd15fe84ba8f.png)

cc - @KartikSuthar @chetansatasiya @firozwp

2021-12-09 04:40 UTC, sourabhmatolia commented
@jitendrabanjara1991 

I agree.
For hidden groups we can redirect to a link like this:
`domain.com/members/username/groups/invites/`

Thanks

2021-12-09 04:51 UTC, jitendrabanjara1991 commented
@KartikSuthar @chetansatasiya 
As per discussed with @sourabhmatolia Button text is fine for hidden .
cc - @firozwp 
Thanks.

2021-12-09 05:30 UTC, KartikSuthar approved these changes

2021-12-09 05:43 UTC, jitendrabanjara1991 commented
Code status
Merged in dev and qa-ongoing
Thanks

2021-12-09 17:28 UTC, sumitbuddyboss commented
Hello @jitendrabanjara1991 @manishpatolia 

**Fixed >**
A related issue is resolved, 

**Testcase - 1**
- Hidden group: Sending the invitations the user should be able to access the group from the email link. - Pass

**Testcase - 2**
-  Private group: Sending the invitations the user should be able to access the group from the email link. - Pass

**Testcase - 3**
- Public group: Sending the invitations the user should be able to access the group from the email link. - Pass

**Testcase - 4**
- Button text is for the hidden group. - Pass


**Video Proof:**
https://www.loom.com/share/9abba8c52b7a4c10aef043e77573c5d1

**Testcase:**
https://docs.google.com/spreadsheets/d/1v7bvYc-n-VZYQu8CcAcc9jLmHFduAQmxz_0n8lhjw7o/edit?pli=1#gid=1451538933

Ready for release 🚀 

Thank you

2021-12-13 11:10 UTC, jitendrabanjara1991 commented
Code status
Merged in qa-approved
Thanks

2021-12-15 06:13 UTC, basil-buddyboss commented
Hello @manishpatolia 

This has been tested in the QA-approved branch including the four test cases and there were no issues encountered.

Result: Pass

2021-12-22 11:29 UTC, merged