Fix/1082
buddyboss/buddyboss-platform pull request #2286
Opened 2021-03-30 09:37 UTC by jitendrabanjara1991

### All Submissions:

https://github.com/buddyboss/buddyboss-platform/pull/2031

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1082.

### How to test the changes in this Pull Request:

1.  Add fieldset with this name - Repeater Fieldset
2.  Add new field in above fieldset with this name - Text Field
3.  Save it and add repeater field at front side in profile section.
4.  Sometimes it generated duplicate fields.

### Proof Screenshots or Video

Only one time replicate in local after that didn't replicate same issue again. When I replicate this issue then checked in DB its cloned from multiple added ids. So, I have changed in code and after that I didn't replicate same issue.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-04-08 13:48 UTC, jitendrabanjara1991 commented
Hello @chetansatasiya 
cc - @sourabhmatolia 
I have changed some code for the repeater field issue. So, Please review it. 
Thanks.

2021-05-31 14:12 UTC, jitendrabanjara1991 commented
@chetansatasiya 
cc - @sourabhmatolia 
Ready for review code.
Please check it and let me know if need any changes.
Note - I have added code for the background process. So, I don't think we need to add option in Repair Community option in the Tools. Right now I have added it. So, Please confirm with me so I can check based on suggestion.
Thanks.

2021-06-22 12:27 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/js/buddypress-xprofile.js
> +            console.log('loaded');
Remove debug code

2021-06-22 12:41 UTC, chetansatasiya requested changes
@sadrul now we are not using the`bp_` prefix in newly introduce function instead of we are using the `bb_` so need to change in this pr in all the new functions

2021-06-22 17:01 UTC, sadrul commented
@chetansatasiya I updated accordingly

2021-06-23 07:21 UTC, chetansatasiya commented on src/bp-xprofile/bp-xprofile-filters.php
> +	$recipients_query = "SELECT DISTINCT id FROM {$bp->profile->table_name_groups} WHERE can_delete= 1 LIMIT 2 OFFSET $offset ";
Use the $wpdb->prepare for query

2021-06-23 07:22 UTC, chetansatasiya requested changes
add the since tag on all the newly added function and run the phpcs in all the newly added a code and fix all of them.

2021-06-24 10:28 UTC, chetansatasiya submitted a review, later dismissed
@sadrul LGTM merge to dev and put in testing

2021-06-24 10:48 UTC, sadrul commented
@sumitbuddyboss this one ready for testing

2021-06-29 11:57 UTC, sadrul commented
Fixed this issue here as well https://github.com/buddyboss/buddyboss-platform/issues/1823
Proof: https://www.loom.com/share/7273e1029739453899d59687eaae17a9

2021-07-19 12:00 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> +add_action( 'admin_init', 'bb_xprofile_repeater_field_repair_with_background' );
@sadrul Please remove the background update here. If we have provided the repair tool that's enough.

2021-07-20 11:07 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> + * @since BuddyBoss 1.6.2
@sadrul Update the since to latest release.

2021-07-20 11:07 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> +	$get_bp_xprofile_migration = (bool) bp_get_option( 'bp_xprofile_migration' );
Remove the option as we provide the tool always.

2021-07-20 11:07 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> + * @since BuddyBoss 1.6.2
Update the since to latest release.

2021-07-20 11:08 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> + * @since BuddyBoss 1.6.2
Update the since to latest release.

2021-07-20 11:09 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> +function bb_xprofile_repeater_field_migration( $offset, $callback ) {
@sadrul I have checked the code and it's not working for me. Can you please test and update accordingly?

2021-07-20 11:09 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> + * @since BuddyBoss 1.6.2
Update the since to latest release.

2021-07-20 11:10 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-repeaters.php
> +					bp_xprofile_add_meta( $new_field_id, 'field', $meta['meta_key'], $meta['meta_value'] );
I think it's not needed. Please revert with `bp_xprofile_update_meta`

2021-07-20 11:11 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-repeaters.php
> +				 * It will issuing in query.
Update the typo.

2021-07-20 11:13 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-repeaters.php
> + * @since BuddyBoss 1.6.2
Update the since to latest release.

2021-07-28 11:47 UTC, KartikSuthar requested changes

2021-07-28 11:47 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> + * @since BuddyBoss 1.7.2.3
@sadrul update the since tag to latest release.

2021-07-28 11:47 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> + * @since BuddyBoss 1.7.2.3
update the since tag to the latest release.

2021-07-28 11:47 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-filters.php
> + * @since BuddyBoss 1.7.2.3
update the since tag to the latest release.

2021-07-28 11:47 UTC, KartikSuthar commented on src/bp-xprofile/bp-xprofile-repeaters.php
> + * @since BuddyBoss 1.7.2.3
update the since tag to the latest release.

2021-07-28 14:21 UTC, KartikSuthar submitted a review, later dismissed

2021-07-29 05:26 UTC, sadrul commented
@sumitbuddyboss @mohit-buddyboss Merged to dev and ready for testing
cc: @sourabhmatolia

2021-07-29 07:19 UTC, sumitbuddyboss commented
Hello @sadrul 

Fixed >
I have checked in dev and fix/1082 branch and related issue are resolved now, for the proof please check the below video.

**Video:**
https://www.loom.com/share/3aa90c31abc54d9786bf7bebf7a9e167

Ready to release 🚀 

Thank you

2021-07-29 11:23 UTC, KartikSuthar approved these changes

2021-07-29 11:56 UTC, merged