Escaped the attributes before echo
buddyboss/buddyboss-platform pull request #2373
Opened 2021-05-03 14:43 UTC by ngolwalkar

### Changes proposed in this Pull Request:

Fixes #1564

### How to test the changes in this Pull Request:

1. Add a new post with a title which have special characters in it.
2. Go to the frontend and search for the same post you created.
3. Now it won't break HTML.

### Proof Screenshots or Video

https://prnt.sc/12ff93n

2021-07-23 06:07 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/search/loop/post-ajax.php
> +				alt="<?php esc_attr( the_title() ); ?>"
@ngolwalkar `the_title()` will print directly so `esc_attr` will not work. You should use `echo esc_attr( get_the_title() );` 

also `the_title()` no need to escape as is already escaping by WordPress

2021-07-23 06:08 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/search/loop/post.php
> +				<img src="<?php echo $result['post_thumbnail']; ?>" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="<?php esc_attr( the_title() ); ?>"/>
@ngolwalkar Needs to make the same changes as above.

2021-07-23 06:08 UTC, chetansatasiya requested changes
See here for more info https://wordpress.stackexchange.com/questions/52597/should-i-escape-wordpress-functions-like-the-title-the-excerpt-the-content/52600#52600

2021-07-26 06:12 UTC, chetansatasiya requested changes
Need changes

2021-07-26 06:12 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/search/loop/post-ajax.php
> +				alt="<?php esc_attr( get_the_title() ); ?>"
```suggestion
				alt="<?php echo esc_attr( get_the_title() ); ?>"
```

2021-07-26 06:12 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/search/loop/post.php
> +				<img src="<?php echo $result['post_thumbnail']; ?>" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="<?php esc_attr( the_title() ); ?>"/>
```suggestion
				<img src="<?php echo $result['post_thumbnail']; ?>" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="<?php echo esc_attr( get_the_title() ); ?>"/>
```

2021-07-26 06:34 UTC, chetansatasiya approved these changes
LGTM 🚀 

@ngolwalkar Merge in dev and put in testing

2021-08-13 13:40 UTC, sumitbuddyboss commented
Hello @ngolwalkar 

I can't reproduce this issue in my local site and demo site as well, for the prof please check the below screenshots.

**Demo site**
https://prnt.sc/1o0f2wu

**Local site**
https://prnt.sc/1o0fboc

@ngolwalkar Please make sure from your end.

cc @chetansatasiya 

Thank you

2021-08-24 04:09 UTC, chetansatasiya requested changes
@ngolwalkar Add the `esc_url` in image src.

2021-08-24 04:09 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/search/loop/post.php
> +				<img src="<?php echo $result['post_thumbnail']; ?>" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="<?php echo esc_attr( get_the_title() ); ?>"/>
```suggestion
				<img src="<?php echo esc_url( $result['post_thumbnail'] ); ?>" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="<?php echo esc_attr( get_the_title() ); ?>"/>
```

2021-09-01 10:15 UTC, merged