Member search for learndash open course
buddyboss/buddyboss-platform pull request #2382
Opened 2021-05-06 08:59 UTC by asaquzzamanbb

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-05-17 17:05 UTC, dipskakadiya commented
@chetansatasiya @KartikSuthar Can you review this PR? I don't have much context for this in platform.

2021-05-26 08:41 UTC, chetansatasiya commented on src/bp-integrations/learndash/learndash/Hooks.php
> +			if ( 'open' == $course_settings['course_price_type'] ) {
```suggestion
			if ( 'open' === $course_settings['course_price_type'] ) {
```
Check for a strict comparision

2021-05-26 08:42 UTC, chetansatasiya commented on src/bp-integrations/learndash/learndash/Hooks.php
> +	 * @since BuddyBoss 1.5.9
```suggestion
	 * @since BuddyBoss 1.6.0
```

2021-05-26 08:43 UTC, chetansatasiya requested changes
Need to make proper since tag and strict comparision.

2021-05-26 09:02 UTC, chetansatasiya approved these changes

2021-05-26 12:29 UTC, mohit-buddyboss commented
@KartikSuthar @chetansatasiya @asaquzzamanbb 

To this PR all members on directory page must appear correctly but on dev branch members count on directory page is not correct because of this PR: https://github.com/buddyboss/buddyboss-platform/pull/2245
@asaquzzamanbb resolved issue mentioned on above PR by Sumit. Now this PR needs review. @KartikSuthar can you please review this PR: PR: https://github.com/buddyboss/buddyboss-platform/pull/2245


cc @sourabhmatolia

2021-05-27 05:56 UTC, merged