Profile search is not working properly for Repeater field set dropdown - Fixed.
buddyboss/buddyboss-platform pull request #2389
Opened 2021-05-09 22:46 UTC by mahedihasannoman

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2353 .

### How to test the changes in this Pull Request:

1. Please see this video to reproduce this issue: https://www.loom.com/share/8610c6c62c5443d88d17337190de0d93

### Proof Screenshots or Video

https://www.loom.com/share/633027418e10475584b8df19cb04dfec

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Profile search issue for repeater field set - Fixed

2021-09-10 07:35 UTC, dipskakadiya requested changes

2021-09-10 07:38 UTC, dipskakadiya requested changes

2021-09-10 07:38 UTC, dipskakadiya commented on src/bp-core/profile-search/bps-xprofile.php
> +	$sql['where']['field_id'] = $wpdb->prepare( "field_id IN(SELECT id FROM {$bp->profile->table_name_fields} where 1 and group_id IN(SELECT group_id FROM {$bp->profile->table_name_fields} where 1 and i
I think `where 1` should be like where 1=1

2021-09-24 11:17 UTC, dipskakadiya submitted a review, later dismissed

2021-12-01 11:32 UTC, mckdlrs commented
Retested in the QA ongoing branch
Status: Not yet fixed

Proof Screenshots or Video: https://www.loom.com/share/7a49a268b1ae42fe9ceee9c550a19dfa

2022-04-18 12:11 UTC, KartikSuthar submitted a review, later dismissed

2022-05-03 12:27 UTC, KartikSuthar approved these changes

2022-07-21 12:48 UTC, merged