Added caching functions to prevent the repeated SQL queries
buddyboss/buddyboss-platform pull request #2433
Opened 2021-05-26 08:23 UTC by janakkaneriya007

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2160 .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-06-08 05:19 UTC, KartikSuthar requested changes

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/bp-moderation-filters.php
> + * @since BuddyBoss 1.5.6
```suggestion
 * @since BuddyBoss 1.6.2
```

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/bp-moderation-filters.php
> + * @since BuddyBoss 1.5.6
```suggestion
 * @since BuddyBoss 1.6.2
```

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/bp-moderation-filters.php
> + * @since BuddyBoss 1.5.6
Update the since here.

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-core-suspend.php
> +		 * @since BuddyBoss 1.5.6
Update the since here.

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-core-suspend.php
> +		 * @since BuddyBoss 1.5.6
Update the since here.

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-suspend-abstract.php
> +					 * @since BuddyBoss 1.5.6
Update the since here.

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-suspend-abstract.php
> +					 * @since BuddyBoss 1.5.6
Update the since here.

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-suspend-member.php
> +		wp_cache_delete( 'bb_check_user_suspend_' . $user_id, 'bb' );
I don't think it's needed here please check and remove it if not needed.

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-core-suspend.php
> +		$cache_key = 'bb_check_user_suspend_' . $user_id;
I think you have the setup key as wrong it will be like this:

```suggestion
		$cache_key = 'bb_check_user_suspend_user_' . $user_id;
```

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/bp-moderation-filters.php
> +function bp_moderation_clear_delete_cache( $suspend_record ) {
Update the function name: 

```suggestion
function bb_moderation_clear_delete_cache( $suspend_record ) {
```

2021-06-08 05:19 UTC, KartikSuthar commented on src/bp-moderation/bp-moderation-filters.php
> +function bp_moderation_clear_status_change_cache( $content_type, $content_id, $args ) {
Update the function name:

```suggestion
function bb_moderation_clear_status_change_cache( $content_type, $content_id, $args ) {
```

2021-06-08 06:16 UTC, KartikSuthar approved these changes
@janakkaneriya007 Approved! Please merged to dev and pass to QA.

2021-06-08 07:14 UTC, janakkaneriya007 commented
@sumitbuddyboss @mohit-buddyboss 

This is ready for testing.

2021-06-09 04:09 UTC, mohit-buddyboss commented
@janakkaneriya007 

FIXED> Tested on dev branch of the platform. 
On dev branch now moderation related queries are not executing multiple times. Also, moderation functionality working fine.
Video: https://www.loom.com/share/0c537bde5a0d4f778db10f0cbbf68e52

Related issue is resolve now and PR is ready to release.

cc @chetansatasiya @sourabhmatolia

2021-06-10 07:00 UTC, chetansatasiya commented on src/bp-moderation/classes/suspend/class-bp-core-suspend.php
> +			$result = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$bp->table_prefix}bp_suspend s WHERE s.item_id = %d AND s.item_type = %s AND user_suspended = 1", $user_id, BP_Suspend_Member::$type ) );
```suggestion
			$result = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$bp->moderation->table_name} s WHERE s.item_id = %d AND s.item_type = %s AND user_suspended = 1", $user_id, BP_Suspend_Member::$type ) ); // phpcs:ignore
```

2021-06-10 07:01 UTC, chetansatasiya commented on src/bp-moderation/classes/suspend/class-bp-core-suspend.php
> +			$result = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$bp->table_prefix}bp_suspend s WHERE s.item_id = %d AND s.item_type = %s AND user_suspended = 1", $item_id, $item_type ) ); // phpcs:igno
```suggestion
			$result = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$bp->moderation->table_name} s WHERE s.item_id = %d AND s.item_type = %s AND user_suspended = 1", $item_id, $item_type ) ); // phpcs:ignore
```

2021-06-10 07:01 UTC, chetansatasiya commented on src/bp-moderation/classes/suspend/class-bp-core-suspend.php
> +			$result = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$bp->table_prefix}bp_suspend s WHERE s.item_id = %d AND s.item_type = %s AND ( hide_sitewide = 1 OR hide_parent = 1 )", $item_id, $item_t
```suggestion
			$result = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$bp->moderation->table_name} s WHERE s.item_id = %d AND s.item_type = %s AND ( hide_sitewide = 1 OR hide_parent = 1 )", $item_id, $item_type ) ); // phpcs:ignore
```

2021-06-10 07:02 UTC, chetansatasiya requested changes
@janakkaneriya007 Need to change the table name as suggested.

2021-06-10 07:46 UTC, chetansatasiya commented on src/bp-moderation/classes/suspend/class-bp-core-suspend.php
> +		do_action( 'bp_suspend_before_remove_suspend', $args );
```suggestion
		do_action( 'bb_suspend_before_remove_suspend', $args );
```

2021-06-10 07:46 UTC, chetansatasiya commented on src/bp-moderation/classes/suspend/class-bp-suspend-abstract.php
> +					do_action( 'bp_suspend_hide_before', $content_type, $content_id, $args );
```suggestion
					do_action( 'bb_suspend_hide_before', $content_type, $content_id, $args );
```

2021-06-10 07:47 UTC, chetansatasiya commented on src/bp-moderation/classes/suspend/class-bp-suspend-abstract.php
> +					do_action( 'bp_suspend_unhide_before', $content_type, $content_id, $args );
```suggestion
					do_action( 'bb_suspend_unhide_before', $content_type, $content_id, $args );
```

2021-06-10 07:47 UTC, chetansatasiya commented on src/bp-moderation/classes/suspend/class-bp-core-suspend.php
> +		do_action( 'bp_suspend_before_add_suspend', $args );
```suggestion
		do_action( 'bb_suspend_before_add_suspend', $args );
```

2021-06-10 07:48 UTC, chetansatasiya commented on src/bp-moderation/bp-moderation-filters.php
> +add_action( 'bp_suspend_before_add_suspend', 'bb_moderation_clear_suspend_cache' );
```suggestion
add_action( 'bb_suspend_before_add_suspend', 'bb_moderation_clear_suspend_cache' );
```

2021-06-10 07:48 UTC, chetansatasiya commented on src/bp-moderation/bp-moderation-filters.php
> +add_action( 'bp_suspend_before_remove_suspend', 'bb_moderation_clear_suspend_cache' );
```suggestion
add_action( 'bb_suspend_before_remove_suspend', 'bb_moderation_clear_suspend_cache' );
```

2021-06-10 07:49 UTC, chetansatasiya commented on src/bp-moderation/bp-moderation-filters.php
> +add_action( 'bp_suspend_hide_before', 'bb_moderation_clear_status_change_cache', 10, 3 );
```suggestion
add_action( 'bb_suspend_hide_before', 'bb_moderation_clear_status_change_cache', 10, 3 );
```

2021-06-10 07:49 UTC, chetansatasiya commented on src/bp-moderation/bp-moderation-filters.php
> +add_action( 'bp_suspend_unhide_before', 'bb_moderation_clear_status_change_cache', 10, 3 );
```suggestion
add_action( 'bb_suspend_unhide_before', 'bb_moderation_clear_status_change_cache', 10, 3 );
```

2021-06-10 07:50 UTC, chetansatasiya requested changes
@janakkaneriya007 Please change all the prefix `bp_` to `bb_`

2021-06-10 08:58 UTC, chetansatasiya approved these changes

2021-06-10 11:47 UTC, merged