Update - Group user role
buddyboss/buddyboss-platform pull request #2446
Opened 2021-06-01 10:53 UTC by asaquzzamanbb

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-06-08 04:12 UTC, chetansatasiya commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +	if ( 'revision' != $post->post_type ) {
```suggestion
	if ( 'revision' !== $post->post_type ) {
```

2021-06-08 04:12 UTC, chetansatasiya commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +	if ( 'groups' != $post_parent->post_type ) {
```suggestion
	if ( 'groups' !== $post_parent->post_type ) {
```

2021-06-08 04:13 UTC, chetansatasiya requested changes
@asaquzzamanbb Run the PHPCS and fix all the errors

2021-06-08 12:04 UTC, asaquzzamanbb commented
@chetansatasiya 

Fixed all PHPCS issue. Could you please review it again.

2021-06-09 05:56 UTC, KartikSuthar requested changes
@asaquzzamanbb Please do the below changes.

2021-06-09 05:56 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> + * @since BuddyBoss 1.6.1
```suggestion
 * @since BuddyBoss 1.6.2
```

2021-06-09 05:56 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> + * @since BuddyBoss 1.6.1
```suggestion
 * @since BuddyBoss 1.6.2
```

2021-06-09 05:56 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> + * @since BuddyBoss 1.6.1
```suggestion
 * @since BuddyBoss 1.6.2
```

2021-06-09 05:56 UTC, KartikSuthar commented on src/bp-integrations/learndash/library/SyncGenerator.php
> +	 * @since BuddyBoss 1.6.1
```suggestion
	 * @since BuddyBoss 1.6.2
```

2021-06-09 05:56 UTC, KartikSuthar commented on src/bp-integrations/learndash/library/SyncGenerator.php
> +	 * @since BuddyBoss 1.6.1
```suggestion
	 * @since BuddyBoss 1.6.2
```

2021-06-09 06:06 UTC, asaquzzamanbb commented
@KartikSuthar 

Changes done! Could you please review it again.

2021-06-09 06:08 UTC, KartikSuthar approved these changes
@asaquzzamanbb Approved. Merged to dev and pass to QA.

2021-06-09 06:16 UTC, asaquzzamanbb commented
@KartikSuthar 

Merge done! https://github.com/buddyboss/buddyboss-platform/commit/8faf829b939f806e2a3495ccfd0439d6692d85eb

2021-06-09 06:38 UTC, chetansatasiya submitted a review, later dismissed

2021-06-09 11:30 UTC, mohit-buddyboss commented
@asaquzzamanbb 

Tested on the dev branch of the platform.
This issue is partially resolved. Now Organizer gets role in LearnDash group as mentioned in Integration setting.

Issue :  But for moderator it is not working. Group Moderator not getting the assigned role as per integration setting

Video: https://www.loom.com/share/2b4a285e680443369cc43cf956e6a27d

cc @sourabhmatolia @chetansatasiya

2021-06-14 05:05 UTC, asaquzzamanbb commented
@chetansatasiya @KartikSuthar 

Could you please review this PR again.

2021-06-14 05:09 UTC, chetansatasiya approved these changes
LGTM

2021-06-14 05:14 UTC, asaquzzamanbb commented
@chetansatasiya 
Merge done with dev branch https://github.com/buddyboss/buddyboss-platform/commit/494d0e7476cb45d96931a5245bc4f8a01a0ec381

2021-06-14 10:26 UTC, mohit-buddyboss commented
@asaquzzamanbb 

Tested on dev branch of the platform 

FIXED> Now if group gets created by non admin users then group organizer and moderators are getting role in associated Learndash group as per selection in BuddyBoss integration settings. 
Video: https://www.loom.com/share/c41cc86c8e69488d8fd20a1639fc74fc

Related issue is resolve now and PR is ready to release.

cc @sourabhmatolia @chetansatasiya

2021-06-16 07:43 UTC, chetansatasiya approved these changes

2021-06-16 09:59 UTC, chetansatasiya approved these changes

2021-06-16 11:10 UTC, chetansatasiya approved these changes

2021-06-16 11:11 UTC, KartikSuthar approved these changes

2021-06-16 11:19 UTC, merged