On-Screen notification
buddyboss/buddyboss-platform pull request #2519
Opened 2021-06-21 17:19 UTC by asaquzzamanbb

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2483

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-06-27 10:10 UTC, mikejyoung commented
@amincdev @shashank-buddyboss @asaquzzamanbb 

Some changes to On-Screen Notifications settings:
https://www.loom.com/share/e98a74a734314c40a80d3398b7f9f268

CC: @sourabhmatolia

2021-06-28 03:56 UTC, shashank-buddyboss commented
@mikejyoung 

Changes (https://github.com/buddyboss/buddyboss-platform/pull/2519#issuecomment-869136966) are done > https://prnt.sc/177nufg

Thanks

2021-06-30 11:57 UTC, chetansatasiya requested changes
@mahedihasannoman all the newly functions need the `bb` prefix instead of `bp`

2021-06-30 11:59 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/notifications/functions.php
> +function bb_notification_avatar() {
@asaquzzamanbb need a function doc block

2021-06-30 12:00 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/notifications/functions.php
> +function bb_current_user_status( $user_id ) {
@asaquzzamanbb need doc block

2021-06-30 12:37 UTC, chetansatasiya approved these changes
@asaquzzamanbb LGTM

2021-06-30 13:06 UTC, merged