Fix/video miscellaneous
buddyboss/buddyboss-platform pull request #2556
Opened 2021-07-02 18:59 UTC by chetansatasiya

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-07-02 19:35 UTC, eisenwasser commented
@chetansatasiya 

We need another status in the notices.

IF Symlinks are disabled, notice should say:
"Symbolic links are disabled"

IF symlinks are enabled, but server is not working properly, only then do we say:
"Symbolic links are not supported on your server. Please contact BuddyBoss for support."

Video explanation https://www.loom.com/share/003c375eaffa4d3abce1a71c002b83eb

2021-07-03 08:05 UTC, chetansatasiya commented
> @chetansatasiya
> 
> We need another status in the notices.
> 
> IF Symlinks are disabled, notice should say:
> "Symbolic links are disabled"
> 
> IF symlinks are enabled, but server is not working properly, only then do we say:
> "Symbolic links are not supported on your server. Please contact BuddyBoss for support."
> 
> Video explanation https://www.loom.com/share/003c375eaffa4d3abce1a71c002b83eb

DONE

2021-07-06 11:52 UTC, KartikSuthar requested changes

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-core/bp-core-actions.php
> +	if ( isset( $_GET ) && isset( $type ) && 'bp-media' ===$type && 'bp-settings' === $page ) {
```suggestion
	if ( isset( $_GET ) && isset( $type ) && 'bp-media' === $type && 'bp-settings' === $page ) {
```

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-media/bp-media-settings.php
> +        <?php _e( 'Enable symbolic links. If you are having issues with media display, try disabling this option.', 'buddyboss' ); ?>
```suggestion
        <?php esc_html_e( 'Enable symbolic links. If you are having issues with media display, try disabling this option.', 'buddyboss' ); ?>
```

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-media/bp-media-settings.php
> +                <p><?php _e( 'Symbolic links are disabled', 'buddyboss' ); ?></p>
```suggestion
                <p><?php esc_html_e( 'Symbolic links are disabled', 'buddyboss' ); ?></p>
```

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-media/bp-media-settings.php
> +				<p><?php _e( 'Symbolic links are activated', 'buddyboss' ); ?></p>
```suggestion
				<p><?php esc_html_e( 'Symbolic links are activated', 'buddyboss' ); ?></p>
```

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-media/bp-media-settings.php
> +	<p class="description"><?php _e( 'Symbolic links are used to create "shortcuts" to media files uploaded by members, providing optimal security and performance. If symbolic links are disabled, a fall
```suggestion
	<p class="description"><?php esc_html_e( 'Symbolic links are used to create "shortcuts" to media files uploaded by members, providing optimal security and performance. If symbolic links are disabled, a fallback method will be used to protect your media files.', 'buddyboss' ); ?></p>
```

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-suspend-video.php
> +	 * @since BuddyBoss 1.7.0
@janakkaneriya007 update the since tag 1.7.0.1

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-suspend-video.php
> +		 * @since BuddyBoss 1.7.0
@janakkaneriya007 update the since tag 1.7.0.1

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-suspend-video.php
> +		$join_sql = apply_filters( 'bp_suspend_video_get_join', $join_sql, $this );
@janakkaneriya007 update the filter name as per the function.

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-suspend-video.php
> +		$where = apply_filters( 'bp_suspend_video_get_where_conditions', $where, $this );
@janakkaneriya007 update the filter name as per the function.

2021-07-06 11:52 UTC, KartikSuthar commented on src/bp-moderation/classes/suspend/class-bp-suspend-video.php
> +		 * @since BuddyBoss 1.7.0
@janakkaneriya007 update the since tag to 1.7.0.1

2021-07-06 11:52 UTC, chetansatasiya commented on src/bp-core/bp-core-actions.php
> +	if ( isset( $_GET ) && isset( $type ) && 'bp-media' ===$type && 'bp-settings' === $page ) {
done

2021-07-06 11:54 UTC, chetansatasiya commented on src/bp-media/bp-media-settings.php
> +        <?php _e( 'Enable symbolic links. If you are having issues with media display, try disabling this option.', 'buddyboss' ); ?>
done

2021-07-06 11:54 UTC, chetansatasiya commented on src/bp-media/bp-media-settings.php
> +                <p><?php _e( 'Symbolic links are disabled', 'buddyboss' ); ?></p>
done

2021-07-06 11:54 UTC, chetansatasiya commented on src/bp-media/bp-media-settings.php
> +				<p><?php _e( 'Symbolic links are activated', 'buddyboss' ); ?></p>
done

2021-07-06 11:54 UTC, chetansatasiya commented on src/bp-media/bp-media-settings.php
> +	<p class="description"><?php _e( 'Symbolic links are used to create "shortcuts" to media files uploaded by members, providing optimal security and performance. If symbolic links are disabled, a fall
done

2021-07-06 12:09 UTC, KartikSuthar approved these changes
@chetansatasiya Approved. Merged to dev and pass to QA.

2021-07-06 14:44 UTC, mohit-buddyboss commented
@chetansatasiya 

Tested on branch `fix/video-miscellaneous` of the platform.
FIXED> 1. Option to disable/enable Symlinks updated successfully.
Screenshots:
https://prnt.sc/191bzya
https://prnt.sc/191c4gz

Issue> Regarding Moderation> Issues is resolved for Photos and Documents but if activity content video file and we report that particular activity then activity is getting hide but "Video" is not getting hide from videos directory page and user profile video tab or group videos tab.
Video> https://www.loom.com/share/c04f17e312be482b834f9a1ea8dcf75f

cc @sourabhmatolia

2021-07-06 16:08 UTC, janakkaneriya007 commented
@mohit-buddyboss What you have shared related to moderation is being worked on right now and it will be ready in the next release.

2021-07-06 16:15 UTC, mohit-buddyboss commented
> @mohit-buddyboss What you have shared related to moderation is being worked on right now and it will be ready in the next release.

@janakkaneriya007 Thanks for the update ! 
Regarding main issue related to Photos. I tested on fix/video-miscellaneous branch of the platform. Now on reporting Photos if photos gets hide after reaching reporting limit then that photos is now not appearing under Photos directory tab, Profile Photo tab and Group Photo tab. Also, count is appearing correct. 


Related issue is resolve now and PR is ready for release. 

cc @sourabhmatolia

2021-07-06 16:33 UTC, merged