Safari Browser popup video not playing
buddyboss/buddyboss-platform pull request #2595
Opened 2021-07-09 04:24 UTC by krunal-buddyboss

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1. Go to Activity OR Video pages in a group, user profile, and directory page
2. Open a video in the popup it's not playing.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-07-13 09:32 UTC, chetansatasiya commented
@krunal-buddyboss Issue is still their in Safari if the symlink is disabled

2021-07-13 09:41 UTC, chetansatasiya commented on src/bp-document/bp-document-functions.php
> +								$attachment_path .= ( ! empty( $ext ) ) ? '.' . $ext : '';
FIX PHPCS

2021-07-13 09:42 UTC, chetansatasiya commented on src/bp-video/bp-video-functions.php
> +			$attachment_path     = $video_symlinks_path . '/' . md5( $video->id . $attachment_id . $privacy . $time ) . ( ! empty( $ext ) ? '.' . $ext : '' );
FIX PHPCS

2021-07-13 09:42 UTC, chetansatasiya requested changes
FIX PHPCS issues

2021-07-13 11:22 UTC, chetansatasiya approved these changes

2021-07-13 11:24 UTC, chetansatasiya commented
@krunal-buddyboss Merge in dev and put in testing.

@mohit-buddyboss @sumitbuddyboss Make sure to test this in all the devices & servers

2021-07-13 11:28 UTC, krunal-buddyboss commented
Thanks @chetansatasiya , I have merged in dev.

@mohit-buddyboss @sumitbuddyboss  Please test it. Thanks.

2021-07-15 09:51 UTC, sumitbuddyboss commented
Hello @krunal-buddyboss 

I have checked the Safari browser issue in the Mobile devices and Different Servers and it's working fine for proof please check the below videos.

**Local server, Flywheel, Site ground, and Windows Server**
https://www.loom.com/share/794fb309c15d45f7b26721c01860b40d
https://www.loom.com/share/144a08326a274c75bdb49150c950d5dd 

**ios Mobile device**
https://www.loom.com/share/129873a5daec49969ed528d53f7b23f0

@sourabhmatolia @chetansatasiya 
Ready for release 🚀 

Thank you

2021-07-15 18:55 UTC, merged