Fix to remove private activity from latest update
buddyboss/buddyboss-platform pull request #2641
Opened 2021-07-21 06:06 UTC by ngolwalkar

### Changes proposed in this Pull Request:

Fixes #1615

### How to test the changes in this Pull Request:

1. Login with User1 and create an activity with privacy "Only Me"
2. Disconnect User1
3. Login with User2 and have a look at the widget Latest Updates

### Proof Screenshots or Video

https://www.loom.com/share/4570bc9b21fb4b6c9c856e18493dff8a

2021-07-22 05:28 UTC, chetansatasiya commented on src/bp-core/bp-core-filters.php
> +
@ngolwalkar No need for this filters

2021-07-22 05:29 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/activity/widgets.php
> +			'privacy' 	   => apply_filters( 'bb_activity_privacy_values', $privacy ),
@ngolwalkar No need for this as well just pass the `'scope'        => 'all',` to `'scope'        => bp_activity_default_scope( 'all' ),`

2021-07-22 05:29 UTC, chetansatasiya requested changes
Fix the changes requested

2021-07-23 05:48 UTC, chetansatasiya approved these changes
LGTM

2022-04-18 08:35 UTC, KartikSuthar commented
Closing the PR as proper fix over here: https://github.com/buddyboss/buddyboss-platform/pull/2913

2022-04-18 08:35 UTC, closed without merging