Activity Post on Public Group to Private Group do not change the privacy of the post - Fixed
buddyboss/buddyboss-platform pull request #2748
Opened 2021-08-06 18:43 UTC by mahedihasannoman

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2171  .

### How to test the changes in this Pull Request:

1. Create activity post on a public group
2. Change the group status to private
3. View as another user who is not a member of that group
4. See the activity feed
5. You will not see that group feed anymore

### Proof Screenshots or Video

https://www.loom.com/share/4716f0e88963454ab4f2201fb3503d44

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-08-11 17:46 UTC, chetansatasiya commented
@ngolwalkar @krunal-buddyboss whoever gets the time first make sure to work on this as first priority. We need to make the sync below all cases.

1. Public to Private
2. Private to Public

2021-08-11 19:51 UTC, mahedihasannoman commented
@chetansatasiya , @ngolwalkar & @krunal-buddyboss I have done the following sync
- Public to Private
- Private to Public
Please review now.

2021-08-12 05:09 UTC, chetansatasiya requested changes
@mahedihasannoman Needs to update condition otherwise, it will break the document, video & photos data for a group.

2021-08-12 05:09 UTC, chetansatasiya commented on src/bp-groups/bp-groups-functions.php
> +	$q = $wpdb->prepare( "UPDATE {$bp->activity->table_name} SET hide_sitewide = %d WHERE item_id = %d and component = 'groups'", $status, $group_id );
@mahedihasannoman We need to add the check here like the privacy = 'public'
```suggestion
	$q = $wpdb->prepare( "UPDATE {$bp->activity->table_name} SET hide_sitewide = %d WHERE item_id = %d and component = 'groups' AND privacy = 'public' ", $status, $group_id );
```

2021-08-12 11:59 UTC, chetansatasiya approved these changes

2021-08-19 07:24 UTC, sumitbuddyboss commented
Hello @mahedihasannoman 

Issue >
Still, I'm able to access all the private group activity in the news feed, So this fix is not working for me, please check the issue video.


Issue video:
https://www.loom.com/share/cd4d907ecea94557a62df034f1eaa458

cc @chetansatasiya 

Thank you

2021-08-19 08:19 UTC, mahedihasannoman commented
Hi @sumitbuddyboss , I have also checked the issue but unable to replicate on my end unfortunately. Will you please see my video here: https://www.loom.com/share/d3a32d2a3a2f4261a46acaed61f55345
Will you please double check and confirm how we can replicate it.
Thank you.

2021-08-19 11:08 UTC, krunal-buddyboss commented
@sumitbuddyboss 
As we have checked together we can not reproduce this issue anymore. please confirm from your side once more.
Thanks.
@mahedihasannoman

2021-08-20 06:01 UTC, KartikSuthar requested changes
@krunal-buddyboss please do the following changes when group privacy updates to the public to hidden or hidden to the public.

2021-08-20 06:01 UTC, KartikSuthar commented on src/bp-groups/bp-groups-functions.php
> +	if ( 'private' === $group->status && 'public' === $status ) {
```suggestion
	if ( ( 'private' === $group->status || 'hidden' === $group->status ) && 'public' === $status ) {
```

2021-08-20 08:58 UTC, krunal-buddyboss commented
Hello @sumitbuddyboss 

We have applied some changes to activity privacy when group privacy updates to the public to hidden or hidden to the public and also private to hidden or hidden to the private. So please test and confirm from your side as well.
Also merged the same to dev as well.
Thanks.
@KartikSuthar @chetansatasiya @sourabhmatolia @mahedihasannoman

2021-08-20 09:41 UTC, KartikSuthar approved these changes

2021-08-23 07:15 UTC, sumitbuddyboss commented
Hello @krunal-buddyboss 

Fixed >
I have test fix/2171 and dev branch, now the group privacy functionality is working as expected. 
Checked the scenario like
 Public group to private 
 Private to Hidden
 Hidden to Public
Also check the subgroup, for proof please check the below video.

Video:
https://www.loom.com/share/f24371f718b24c40b6961fcd3aa65f61

Ready for release 🚀 

cc @chetansatasiya 

Thank you

2021-08-24 16:53 UTC, JetalDobariya commented
Hello 

I have tested this PR in QA Approved branch and this PR's fictionalities are working fine related to Privacy of the groups.
Here, I attached Video for reference.
https://www.loom.com/share/bdea8a69b84f4cc7a9fbdf5638798702

So this PR is Ready for Productions.

Thanks!

2021-09-01 10:13 UTC, merged