Fatar error when Clearing default data from BuddyBoss Tools
buddyboss/buddyboss-platform pull request #2750
Opened 2021-08-08 13:27 UTC by Nayeem-BB

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

=> Activate Forum discussions component first
=> Import data related to Forum discussions like Discussions/Replies
=> Deactivate Forum discussions component
=> The again go to BuddyBoss > Tools > Click on Clear default data
=> The Fatal Error should not appear anymore in this fix as stated in the issue

### Proof Screenshots or Video

https://www.loom.com/share/609d53c82adf4fa391844b16006815cb

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-08-09 04:19 UTC, chetansatasiya commented on src/bp-core/bp-core-tools-default-data.php
> +			}
@Nayeem-BB Need the proper tabing here.

2021-08-09 04:20 UTC, chetansatasiya requested changes
@Nayeem-BB Thanks for the PR but we need to follow the proper tabing and spacing as per coding standard.

2021-08-09 13:05 UTC, Nayeem-BB commented on src/bp-core/bp-core-tools-default-data.php
> +			}
Done @chetansatasiya  Thank you 🙂

2022-04-12 13:24 UTC, jitendrabanjara1991 approved these changes
LGTM

2022-11-24 09:42 UTC, merged