#2690 - quick reply ajax
buddyboss/buddyboss-platform pull request #2757
Opened 2021-08-09 17:17 UTC by sadrul

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-08-11 05:44 UTC, chetansatasiya commented on src/bp-forums/common/template.php
> +		<input type="hidden" name="bbp_topic_id"    id="bbp_topic_id"    value="<?php echo $topic_id; ?>" />
Use the escaping function here

2021-08-11 05:45 UTC, chetansatasiya requested changes
Need changes

2021-08-11 11:06 UTC, sadrul commented
@chetansatasiya done with the change requests

2021-08-12 06:50 UTC, chetansatasiya commented
@sadrul This is not working and even not opening the popup

2021-08-13 06:24 UTC, KartikSuthar requested changes

2021-08-13 06:24 UTC, KartikSuthar commented on src/bp-forums/common/template.php
> +
@sadrul Remove this change from here.

2021-08-13 06:24 UTC, KartikSuthar commented on src/bp-forums/common/template.php
> +		<input type="hidden" name="bbp_topic_id"    id="bbp_topic_id"    value="<?php echo esc_attr( $topic_id ); ?>" />
@sadrul Remove this change from here.

2021-08-13 06:24 UTC, KartikSuthar commented on src/bp-forums/templates/default/bbpress/form-attachments.php
> +
@sadrul Remove this change from here.

2021-08-13 14:48 UTC, sadrul commented
This PR is not needed as everything is done from theme PR - https://github.com/buddyboss/buddyboss-theme/pull/1584

2021-08-16 07:00 UTC, sadrul commented
Reopening this PR as we need this

2021-08-16 08:02 UTC, chetansatasiya approved these changes
LGTM 🚀

2021-08-16 10:39 UTC, sadrul commented
@sumitbuddyboss @mohit-buddyboss Merged into dev and ready for testing

2021-08-18 03:12 UTC, mohit-buddyboss commented
@sadrul 

Tested using dev branch of the platform and master branch of the platform pro.

Now, users who don't have access to upload media, document or videos are getting option to upload all for group related forum discussion quick reply.
Tested by checking quick reply medium editor option for both individual and group forum related activity. Also, uploaded media ,doc and video through quick reply editor.

Video: https://loom.com/share/445b91db0de34a4e807611acc283864c

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @chetansatasiya @KartikSuthar 

Related Theme PR
buddyboss/buddyboss-theme#1584

2021-08-19 09:03 UTC, KartikSuthar approved these changes

2021-08-31 12:40 UTC, sourabhmatolia commented
@amincdev @sadrul 

Check the video here talking about the UI issue:
https://www.loom.com/share/618df528dd5a4f7ea79fb0e6ce9dcad2
Screenshot again for ref: https://prnt.sc/1qvnpoi

Please fix. Thanks.

2021-08-31 15:01 UTC, amincdev commented
> @amincdev @sadrul
> 
> Check the video here talking about the UI issue:
> 
> https://www.loom.com/share/618df528dd5a4f7ea79fb0e6ce9dcad2
> Screenshot again for ref: https://prnt.sc/1qvnpoi
> 
> Please fix. Thanks.

@sourabhmatolia Changes are made and merged in `QA-approved` branch in theme repo PR: https://github.com/buddyboss/buddyboss-theme/pull/1584.

2021-09-01 10:13 UTC, merged