fix: Profile Search with Search all fields has Undefined id
buddyboss/buddyboss-platform pull request #2822
Opened 2021-08-23 15:05 UTC by milanhirapra

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2124 .

### How to test the changes in this Pull Request:

1. Go to Buddyboss > Profiles > Profile Search Tab add (Search all fields ) fields. https://prnt.sc/yu4ae6
2. Try to search/filter on members directory using search all fields textbox

### Proof Screenshots or Video
https://vimeo.com/591067740/278137bc27

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-09-06 07:07 UTC, dipskakadiya submitted a review, later dismissed
@milanhirapra Approved. Ready for testing.

2021-09-14 16:37 UTC, JetalDobariya commented
Hello @milanhirapra , @dipskakadiya 

I tested this PR in qa-ongoing branch, now "All search field" is working perfectly in the member directory.
See in the Video : https://www.loom.com/share/d67036c20bf9472481cddfccdb26fbf1

Thanks!

2021-09-20 04:41 UTC, chetansatasiya requested changes
@milanhirapra Follow the spacing properly.

2021-09-20 04:41 UTC, chetansatasiya commented on src/bp-xprofile/bp-xprofile-repeaters.php
> +	if( ! isset( $f->id ) ){
```suggestion
	if ( ! isset( $f->id ) ) {
```

2021-09-20 07:03 UTC, KartikSuthar approved these changes

2021-09-23 10:04 UTC, JetalDobariya commented
Hello @milanhirapra and @dipskakadiya 

I did verify this PR in qa-approved branch, now "Search with All" field results are getting perfect on Member Directory page.
--> https://www.loom.com/i/cfc77bcb5fff4eae858ac960d17b33d7

Thanks!

2021-09-30 14:04 UTC, merged