#1746 - add basic code for batch email
buddyboss/buddyboss-platform pull request #2827
Opened 2021-08-24 14:08 UTC by sadrul

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-08-25 09:12 UTC, KartikSuthar requested changes

2021-08-25 09:12 UTC, KartikSuthar commented on src/bp-core/classes/class-bp-email-queue.php
> +			$this->create_db_table();
remove this from here

2021-08-25 09:12 UTC, KartikSuthar commented on src/bp-core/classes/class-bp-email-queue.php
> +
```
 public static function instance() {
        if ( is_null( self::$_instance ) )
			self::$_instance = new self();

		return self::$_instance;
    }

```

2021-08-25 09:12 UTC, KartikSuthar commented on src/bp-core/classes/class-bp-email-queue.php
> +
`private static $_instance = null;`

2021-08-25 09:12 UTC, KartikSuthar commented on src/bp-core/classes/class-bp-email-queue.php
> +			add_action( 'bp_email_queue_cron_hook', array( $this, 'email_queue_cron_cb' ) );
replace with background job here

2021-08-25 09:12 UTC, KartikSuthar commented on src/bp-core/classes/class-bp-email-queue.php
> +		public function get_records() {
```suggestion
		public function get_records( $limit = 20, $order_column = 'id', $orderby = 'ASC' ) {
```

2021-08-25 09:12 UTC, KartikSuthar commented on src/bp-core/classes/class-bp-email-queue.php
> +	            arguments mediumtext DEFAULT NULL,
```suggestion
	            arguments longtext DEFAULT NULL,
```

2021-08-25 09:12 UTC, KartikSuthar commented on src/bp-core/classes/class-bp-email-queue.php
> +
```
function bp_email_queue() {
	if ( class_exists( 'BP_Email_Queue' ) ) {
		global $bp_email_queue;
		$bp_email_queue = BP_Email_Queue::instance();

		return $bp_email_queue;
	}
}
```

2021-08-25 09:12 UTC, KartikSuthar commented on src/bp-core/bp-core-email-queue.php
> +
remove this file its not needed.

2021-08-25 09:12 UTC, KartikSuthar commented on src/class-buddypress.php
> +		require $this->plugin_dir . 'bp-core/bp-core-email-queue.php';
remove the file include here

2021-08-30 05:38 UTC, chetansatasiya commented on src/bp-core/classes/class-bp-email-queue.php
> +				//}
@sadrul We need to remove the record only if the email fired successfully. So need to keep the condition as it is.

2021-08-30 05:41 UTC, chetansatasiya requested changes
Need to check class exists in many places

2021-08-30 05:41 UTC, chetansatasiya commented on src/bp-groups/bp-groups-notifications.php
> +	}
```suggestion
	if ( function_exists( 'bp_email_queue' ) ) {
	        bp_email_queue()->add_record( 'groups-member-promoted', (int) $user_id, $args );
		// call email background process.
		bp_email_queue()->bb_email_background_process();
	} else {
	       bp_send_email( 'groups-member-promoted', (int) $user_id, $args );
	}
```

2021-09-06 06:43 UTC, KartikSuthar requested changes

2021-09-06 06:43 UTC, KartikSuthar commented on src/bp-core/bp-core-update.php
> +		if ( $raw_db_version < 17501 ) {
```suggestion
		if ( $raw_db_version < 17701 ) {
```

2021-09-06 06:43 UTC, KartikSuthar commented on src/class-buddypress.php
> +		$this->db_version = 17501;
```suggestion
		$this->db_version = 17701;
```

2021-09-06 07:29 UTC, KartikSuthar commented on src/bp-invites/actions/invites.php
> +		}
```suggestion
              if ( function_exists( 'bp_email_queue' ) ) {
			bp_email_queue()->add_record( 'invites-member-invite', $email, $args );
			// call email background process.
			bp_email_queue()->bb_email_background_process();
		} else {
			bp_send_email( 'invites-member-invite', $email, $args );
		}
```

2021-09-06 07:29 UTC, KartikSuthar commented on src/bp-members/bp-members-functions.php
> +	}
```suggestion
	        if ( function_exists( 'bp_email_queue' ) ) {
			bp_email_queue()->add_record( 'core-user-registration', $to, $args );
			// call email background process.
			bp_email_queue()->bb_email_background_process();
		} else {
			bp_send_email( 'core-user-registration', $to, $args );
		}
```

2021-09-06 08:31 UTC, KartikSuthar approved these changes

2021-09-06 09:20 UTC, sadrul commented
@sumitbuddyboss @mohit-buddyboss merged into dev and qa-ongoing and ready for testing

2021-09-06 13:05 UTC, sadrul commented
This task is bumped for release 1.7.7 because it was not delivered in keeping enough time for QA in hand. The task has taken time because there are a couple of areas that need to consider implementing this and had to test a lot to make sure working fine for each module and for a varied range of users. Also, we had to restructure the code couple of times to achieve this correctly, so there was a couple of back and forth and discussion. There are the main reasons for delaying the delivery of this task.

2021-09-10 12:32 UTC, KartikSuthar requested changes

2021-09-10 12:32 UTC, KartikSuthar commented on src/bp-core/bp-core-update.php
> +		}
remove this function not exists.

2021-09-10 12:32 UTC, KartikSuthar commented on src/bp-core/bp-core-update.php
> +	if ( function_exists( 'bb_is_email_queue' ) && bb_is_email_queue() ) {
```suggestion
	if ( function_exists( 'bb_email_queue' )  ) {
```

2021-09-10 12:41 UTC, KartikSuthar commented on src/class-buddypress.php
> +		$this->db_version = 17701;
```suggestion
		$this->db_version = 17801;
```

2021-09-10 12:51 UTC, KartikSuthar approved these changes

2021-09-10 13:32 UTC, sadrul commented
@sumitbuddyboss it will not work in group > send message > Send private message https://i.imgur.com/rcTq0B8.png because there is some other issue (maximum execution timeout) and its been taken care in another PR https://github.com/buddyboss/buddyboss-platform/pull/2911

2021-09-17 09:52 UTC, KartikSuthar submitted a review, later dismissed

2021-09-17 11:19 UTC, sumitbuddyboss commented
Hello @sadrul 

**Issue:**
moderation >  If the user gets suspend and report any activity then why getting 3 batches in the database table.

**Issue:**
https://www.loom.com/share/e77339974c1a41a69d30b6e87d79497d

Thank you

2021-09-17 13:46 UTC, sadrul commented
@sumitbuddyboss It has been fixed and merged already https://www.loom.com/share/b7301d725ecf46eabe34db5b5b5b2540

2021-09-17 13:58 UTC, sadrul commented
We are bumping this task as we going to change the logic in the implementation. The batch email will be implemented only where more than 20 emails need to process and a filter will be provided to change this number.

2021-09-23 02:05 UTC, chetansatasiya requested changes
Need changes

2021-09-23 10:27 UTC, chetansatasiya approved these changes

2021-09-23 16:28 UTC, sadrul commented
@mohit-buddyboss @sumitbuddyboss Merged into dev and qa-ongoing and ready for testing

2021-09-28 12:10 UTC, sumitbuddyboss commented
Hello @sadrul 

I have checked in qa-ongoing branch and now as per new logic Email batch is working as expected, Please check my below comments and video proof.

**Forums**
Sends notification emails for new replies to subscribed topics
Sends notification emails for new topics to subscribed forums
https://www.loom.com/share/3522a17bd195448eb1e739d66ece23d2

**Groups**
Notify all group members when a group is updated.
Email message recipients to alert them of a new unread group message.

https://www.loom.com/share/af4ef6fe51a14907ba221615452888da
https://www.loom.com/share/7ba7383fff0e4a368b723f1a7289b7d6

**Messages**
Email message recipients to alert them of a new unread private message.
https://www.loom.com/share/50cafed2845a4975bb8c728a21c13237
https://www.loom.com/share/5cf2fbafe2724e06a66df7a4f7645070

**Profile**
Member submit email invite.
Right now only we can invite 20 member so email not send in batch but our batch email code is there so if in future we increase limit then batch email is work.
https://www.loom.com/share/8759a160e7a946fab9fbf13525e6114c


Ready for release 🚀 

Thank you

2021-10-12 11:46 UTC, mohit-buddyboss commented
@sadrul 

Tested on qa-approved branch of the platform.
This PR functionality is working as expected and ready for production.

cc @sourabhmatolia @chetansatasiya @KartikSuthar

2021-10-18 11:19 UTC, sadrul commented
@sumitbuddyboss as we discussed via a call that the batch email background processes never execute due to the moderation module issue (suspend background processes exist in db and try to process, however they never been completed) which has been fixed in this pr https://github.com/buddyboss/buddyboss-platform/pull/3061 otherwise if we remove those suspend background processes, then batch email working fine

2021-11-03 18:06 UTC, JetalDobariya commented
Hello @sadrul 

I did verify all of above TCs in the qa-approved branch, now all the TCs are passed and batch email functionalities are working as expected.
here , I attached few Screenshots for the proofs.
Group update :
Database : https://prnt.sc/1y9g25r
Email : https://prnt.sc/1y9g5bu

Group msg :
Database : https://prnt.sc/1y9gibc
Email : https://prnt.sc/1y9glyc

Forum : 
Databse : https://prnt.sc/1ya0j0e
Email : https://prnt.sc/1ya0ki5

Forum Reply
Database : https://prnt.sc/1ya1k4g
Email : https://prnt.sc/1ya1lo1

Zoom 
Databse : https://prnt.sc/1ya1uhc

Thanks!
CC : @sourabhmatolia @KartikSuthar @sumitbuddyboss

2021-11-10 11:18 UTC, KartikSuthar commented
@sourabhmatolia As discussed on call we have an issue with the moderation background process(https://github.com/buddyboss/buddyboss-platform/issues/3153). 
So, as discussed we are going to create a new background process for the email one.

CC: @chetansatasiya @firozwp

2021-11-11 06:43 UTC, chetansatasiya submitted a review, later dismissed

2021-11-11 07:19 UTC, KartikSuthar commented
@sumitbuddyboss @JetalDobariya 

We need to test it again as a registered new background job for the email one.
http://prntscr.com/1z48yu4

We need to test the background job is correctly registered and email sending is working correctly or not.

2021-11-11 11:02 UTC, JetalDobariya commented
Hello @KartikSuthar 

I did verify again all the Batch email which i tested earlier and all the emails are working fine.

Thanks!
CC : @sourabhmatolia @sumitbuddyboss

2021-11-15 06:18 UTC, merged

2021-12-23 15:07 UTC, azanoni commented
Hi, I think that you introduce by mistake another BIG issue on 1.8.1, we updated from 1.8.0 to 1.8.2 on my client website the 1st of December, and in that time we have our wp_options table with a size of **31MB** and now we have wp_options table with a size of **60GIGABYTES!!!**, we suffer a lots of crashes/frozen DB because this, please dont attach in WP_OPTIONS without delete later this kind of rows:

SELECT count(*) FROM ebdbprd.wp_options WHERE option_name like "wp_1_bb_email%" returns 67913 rows 

![image](https://user-images.githubusercontent.com/21685626/147258218-4b9e0a9a-bfb8-4b29-90fe-60d0ab677484.png)

![image](https://user-images.githubusercontent.com/21685626/147258334-a51d9d51-c65b-46cb-9787-5be9027f7d4b.png)

Example of each json that you store in wp_options table

`a:238:{i:0;a:2:{s:8:"callback";a:2:{i:0;O:14:"BP_Email_Queue":0:{}i:1;s:22:"bb_email_queue_cron_cb";}s:4:"args";a:1:{i:0;a:1:{i:0;a:6:{s:2:"id";s:4:"1561";s:10:"email_type";s:28:"zoom-scheduled-meeting-email";s:9:"recipient";s:1024:"O:7:"WP_User":8:{s:4:"data";O:8:"stdClass":12:{s:2:"ID";s:4:"3958";s:10:"user_login";s:8:"XXXX";s:9:"user_pass";s:34:"XXXXXXXXXXX1";s:13:"user_nicename";s:8:"XXXXX";s:10:"user_email";s:21:"XXXX@gmail.com";s:8:"user_url";s:0:"";s:15:"user_registered";s:19:"2017-03-18 21:14:01";s:19:"user_activation_key";s:0:"";s:11:"user_status";s:1:"0";s:12:"display_name";s:17:"xxxx( xxxxxx)";s:4:"spam";s:1:"0";s:7:"deleted";s:1:"0";}s:2:"ID";i:3958;s:4:"caps";a:2:{s:10:"subscriber";b:1;s:15:"bbp_participant";b:1;}s:7:"cap_key";s:15:"wp_capabilities";s:5:"roles";a:2:{i:0;s:10:"subscriber";i:1;s:15:"bbp_participant";}s:7:"allcaps";a:13:{s:4:"read";b:1;s:7:"level_0";b:1;s:16:"propanel_widgets";b:0;s:8:"spectate";b:1;s:11:"participate";b:1;s:19:"read_private_forums";b:1;s:14:"publish_topics";b:1;s:11:"edit_topics";b:1;s:15:"publish_replies";b:1;s:12:"edit_replies";b:1;s:17:"assign_topic_tags";b:1;s:10:"subscriber";b:1;s:15:"bbp_participant";b:1;}s:6:"filter";N;s:16:"`

2021-12-24 04:22 UTC, chetansatasiya commented
> Hi, I think that you introduce by mistake another BIG issue on 1.8.1, we updated from 1.8.0 to 1.8.2 on my client website the 1st of December, and in that time we have our wp_options table with a size of **31MB** and now we have wp_options table with a size of **60GIGABYTES!!!**, we suffer a lots of crashes/frozen DB because this, please dont attach in WP_OPTIONS without delete later this kind of rows:
> 
> SELECT count(*) FROM ebdbprd.wp_options WHERE option_name like "wp_1_bb_email%" returns 67913 rows
> 
> ![image](https://user-images.githubusercontent.com/21685626/147258218-4b9e0a9a-bfb8-4b29-90fe-60d0ab677484.png)
> 
> ![image](https://user-images.githubusercontent.com/21685626/147258334-a51d9d51-c65b-46cb-9787-5be9027f7d4b.png)
> 
> Example of each json that you store in wp_options table
> 
> `a:238:{i:0;a:2:{s:8:"callback";a:2:{i:0;O:14:"BP_Email_Queue":0:{}i:1;s:22:"bb_email_queue_cron_cb";}s:4:"args";a:1:{i:0;a:1:{i:0;a:6:{s:2:"id";s:4:"1561";s:10:"email_type";s:28:"zoom-scheduled-meeting-email";s:9:"recipient";s:1024:"O:7:"WP_User":8:{s:4:"data";O:8:"stdClass":12:{s:2:"ID";s:4:"3958";s:10:"user_login";s:8:"XXXX";s:9:"user_pass";s:34:"XXXXXXXXXXX1";s:13:"user_nicename";s:8:"XXXXX";s:10:"user_email";s:21:"XXXX@gmail.com";s:8:"user_url";s:0:"";s:15:"user_registered";s:19:"2017-03-18 21:14:01";s:19:"user_activation_key";s:0:"";s:11:"user_status";s:1:"0";s:12:"display_name";s:17:"xxxx( xxxxxx)";s:4:"spam";s:1:"0";s:7:"deleted";s:1:"0";}s:2:"ID";i:3958;s:4:"caps";a:2:{s:10:"subscriber";b:1;s:15:"bbp_participant";b:1;}s:7:"cap_key";s:15:"wp_capabilities";s:5:"roles";a:2:{i:0;s:10:"subscriber";i:1;s:15:"bbp_participant";}s:7:"allcaps";a:13:{s:4:"read";b:1;s:7:"level_0";b:1;s:16:"propanel_widgets";b:0;s:8:"spectate";b:1;s:11:"participate";b:1;s:19:"read_private_forums";b:1;s:14:"publish_topics";b:1;s:11:"edit_topics";b:1;s:15:"publish_replies";b:1;s:12:"edit_replies";b:1;s:17:"assign_topic_tags";b:1;s:10:"subscriber";b:1;s:15:"bbp_participant";b:1;}s:6:"filter";N;s:16:"`
> 
> Could you please tell us what we could do until you fix this in your core? we are increasing the DB table per 10gigabytes each week
> 
> EDIT2: You need to find a way to deleted those notifications, also improve the way to do that when the groups are having 1000 users.

@azanoni Could you please create a support ticket with us via your BuddyBoss account and send us your site's credentials so we can take look into that in priority as no one has reported this kind of issue to us?

2021-12-24 04:40 UTC, chetansatasiya commented
@azanoni Also, in the meantime you can add this code `add_filter( 'bb_is_email_queue', '__return_false' );` to your child theme `functions.php` file to stop creating a cron and fire the email instantly without creating a background job.