PROD-755 BuddyBoss component pages are rendered blank on Platform + Multisite + TranslatePress - Fixed
buddyboss/buddyboss-platform pull request #2836
Opened 2021-08-25 18:20 UTC by mahedihasannoman

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2835  .

### How to test the changes in this Pull Request:

1. Create a Multisite environment
2. Install BuddyBoss Theme, Platform and TranslatePress
3. In TranslatePress, create another language aside from default language
4. In front end, check BuddyBoss pages (activity page for instance ) and try to switch language.
5. See error is not happening anymore

### Proof Screenshots or Video

https://www.loom.com/share/ed7b21c45676430fa070a74208157588

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-09-10 07:21 UTC, dipskakadiya approved these changes

2021-11-29 10:03 UTC, dipskakadiya approved these changes

2021-12-31 14:26 UTC, KartikSuthar requested changes

2021-12-31 14:26 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +		 * @param string $url URL with Language code
```suggestion
		 * @param string $url URL with Language code.
```

2021-12-31 14:26 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +		 * @return string $url URL without language code
```suggestion
		 * @return string $url URL without language code.
```

2021-12-31 14:26 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +		}
```suggestion
		function bb_core_multisite_multilang_translatepress_exclude_lang_slug( $url ) {
			if ( ! is_admin() ) {
				$tp_settings = get_option( 'trp_settings' );
				if ( $tp_settings && isset( $tp_settings['url-slugs'] ) && ! empty( $tp_settings['url-slugs'] ) ) {
					foreach ( $tp_settings['url-slugs'] as $lang_key => $lang_slug ) {
						$url = str_replace( $lang_slug . '/', '', $url );
					}
				}
			}

			return $url;
		}
```

2022-01-06 15:43 UTC, mahedihasannoman commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +		}
Done

2022-04-18 08:16 UTC, KartikSuthar commented
Its duplicate PR: https://github.com/buddyboss/buddyboss-platform/pull/2950/files

2022-04-18 08:16 UTC, closed without merging