#2121 - activity comment sync fixed
buddyboss/buddyboss-platform pull request #2844
Opened 2021-08-27 10:30 UTC by chetansatasiya

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2121 .

### How to test the changes in this Pull Request:

1. Add a root comment in the Feed section with release branch
2. Add a media/document in the root as well as child also ( Hierarchy comment ) with release branch
3. Now move this branch and check all added comment for media/document
4. FYI - We will not allow user to add like/comment for media/document with this branch. If user has already this type of fees then user can only see comments. Not add new comments for media/document

### Proof Screenshots or Video

https://screencast-o-matic.com/watch/crjviCVQ2jR

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Dependent API
https://github.com/buddyboss/buddyboss-platform-api/pull/314
Dependent App Native
https://github.com/buddyboss/buddyboss-app-native/issues/1565

2021-08-31 11:28 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> +function bp_nouveau_get_activity_entry_buttons_callback( $buttons, $activity_id ) {
```suggestion
function bb_nouveau_get_activity_entry_buttons_callback( $buttons, $activity_id ) {
```

2021-08-31 11:29 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/document/ajax.php
> +			remove_filter( 'bp_nouveau_get_activity_entry_buttons', 'bp_nouveau_get_activity_entry_buttons_callback', 99, 2 );
```suggestion
			remove_filter( 'bp_nouveau_get_activity_entry_buttons', 'bb_nouveau_get_activity_entry_buttons_callback', 99, 2 );
```

2021-08-31 11:30 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/media/ajax.php
> +			add_filter( 'bp_nouveau_get_activity_entry_buttons', 'bp_nouveau_get_activity_entry_buttons_callback', 99, 2 );
```suggestion
			add_filter( 'bp_nouveau_get_activity_entry_buttons', 'bb_nouveau_get_activity_entry_buttons_callback', 99, 2 );
```

2021-08-31 11:30 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/media/ajax.php
> +			remove_filter( 'bp_nouveau_get_activity_entry_buttons', 'bp_nouveau_get_activity_entry_buttons_callback', 99, 2 );
```suggestion
			remove_filter( 'bp_nouveau_get_activity_entry_buttons', 'bb_nouveau_get_activity_entry_buttons_callback', 99, 2 );
```

2021-08-31 11:30 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> + *
Add since tag.

2021-08-31 11:31 UTC, chetansatasiya reviewed
Need requested changes.

2021-08-31 11:37 UTC, jitendrabanjara1991 commented on src/bp-activity/bp-activity-filters.php
> + *
Added since tag 1.7.7

2021-08-31 11:40 UTC, jitendrabanjara1991 commented
@chetansatasiya 
Request changes done. Please review again and let me know if anything else.
Thanks.

2021-08-31 11:47 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> + * @since BuddyBoss 1.7.7
```suggestion
 * @return mixed
  * 
 * @since BuddyBoss 1.7.7
```

2021-08-31 11:52 UTC, chetansatasiya reviewed
@jitendrabanjara1991 Many places need to add the escaping functions

2021-08-31 11:52 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/media/ajax.php
> +                                          placeholder="<?php esc_html_e( 'Add a description', 'buddyboss' ); ?>" role="textbox"><?php echo $content; ?></textarea>
```suggestion
                                          placeholder="<?php esc_html_e( 'Add a description', 'buddyboss' ); ?>" role="textbox"><?php echo sanitize_textarea_field( $content ); ?></textarea>
```

2021-08-31 11:52 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/media/ajax.php
> +                                <input type="hidden" id="bp-attachment-id" value="<?php echo $attachment_id; ?>">
```suggestion
                                <input type="hidden" id="bp-attachment-id" value="<?php echo esc_attr( $attachment_id ); ?>">
```

2021-08-31 11:52 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/media/ajax.php
> +                        <a class="bp-add-media-activity-description <?php echo( ! empty( $content ) ? 'show-edit' : 'show-add' ); ?>" href="#">
```suggestion
                        <a class="bp-add-media-activity-description <?php echo( ! empty( $content ) ? esc_attr( 'show-edit' ) : esc_attr( 'show-add' ) ); ?>" href="#">
```

2021-08-31 12:19 UTC, KartikSuthar requested changes

2021-08-31 12:19 UTC, KartikSuthar commented on src/bp-activity/bp-activity-filters.php
> +				$activity_id     = $bp_new_activity_comment;
apply phpcs here.

2021-08-31 12:19 UTC, KartikSuthar commented on src/bp-activity/bp-activity-filters.php
> +					$document->privacy     = 'comment';
apply phpcs here.

2021-08-31 12:19 UTC, KartikSuthar commented on src/bp-document/bp-document-filters.php
> +			) {
```suggestion
			if (
				! in_array( $document->privacy, array( 'forums', 'message', 'media', 'document', 'grouponly', 'video' ), true ) &&
			     'comment' !== $document->privacy &&
			     ! empty( $document->blog_id )
			) {
```

2021-08-31 12:19 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/includes/document/ajax.php
> +						<a class="bp-add-media-activity-description <?php echo( ! empty( $content ) ? 'show-edit' : 'show-add' ); ?>"
```suggestion
						<a class="bp-add-media-activity-description <?php echo ( ! empty( $content ) ? 'show-edit' : 'show-add' ); ?>"
```

2021-08-31 13:22 UTC, jitendrabanjara1991 commented
@KartikSuthar @chetansatasiya 
Request changes done. Please review again and let me know if still need any changes.
Thanks.

2021-09-01 08:40 UTC, chetansatasiya reviewed
@jitendrabanjara1991 LGTM 🚀

2021-09-01 08:58 UTC, KartikSuthar approved these changes

2021-09-01 10:18 UTC, jitendrabanjara1991 commented
@sumitbuddyboss @mohit-buddyboss 
Merged in dev and QA-ongoing branch and ready for testing.
cc - @chetansatasiya @KartikSuthar 
Thanks.

2021-09-03 06:11 UTC, mohit-buddyboss commented
@jitendrabanjara1991 @janakkaneriya007 

This PR is conflicting with moderation feature and also creating backward compatibility issue - For all existing activity comment (if comment contain Photo and doc) then when we open those photos or doc in pop up on 'QA-ongoing' branch then we are getting option to report photos and doc. This fix is working for new activity comments but not for older comments.
Video: https://loom.com/share/9781fe32bf734d6fa94e769ea24c7d12

 @sumitbuddyboss you can work on this PR to verify other issues.

cc @sourabhmatolia @chetansatasiya @firozwp @KartikSuthar

2021-09-03 07:20 UTC, jitendrabanjara1991 commented
@chetansatasiya 
I have fixed issue as per suggestion by @mohit-buddyboss . So, please review it.
Thanks.

2021-09-03 12:17 UTC, KartikSuthar submitted a review, later dismissed

2021-09-03 16:43 UTC, sumitbuddyboss commented
Hello @jitendrabanjara1991 

Issue >
1) Video does not allow to move in the comment but new activity comment photo allows to move in album 
https://prnt.sc/1r3yye5

But the old media did not allow to move media, so kindly make sure
https://prnt.sc/1r3zbgq

2) Group > Comment > Reply
If we add multiples documents in reply then the document does not appear.
https://www.loom.com/share/cf41bd8c943945c0bad6d195fb4eb21c

3) Group > Dropzone not seen when clicking on reply, the issue is only for when we upload photos and documents.
https://www.loom.com/share/7f5e0d7cd6374be598c1679c3339a361


Thank you

2021-09-06 04:26 UTC, jitendrabanjara1991 commented
Hello @sumitbuddyboss 

Fixed below issue so please test again and let me know if you find anything else.

Issue >

1) Video does not allow to move in the comment but new activity comment photo allows to move in album
https://prnt.sc/1r3yye5
But the old media did not allow to move media, so kindly make sure
https://prnt.sc/1r3zbgq
**Fixed** - https://screencast-o-matic.com/watch/crQ1fFVQaOR

2) Group > Comment > Reply
If we add multiples documents in reply then the document does not appear.
https://www.loom.com/share/cf41bd8c943945c0bad6d195fb4eb21c
**Fixed** - https://screencast-o-matic.com/watch/crQ1frVQatQ

3) Group > Dropzone not seen when clicking on reply, the issue is only for when we upload photos and documents.
https://www.loom.com/share/7f5e0d7cd6374be598c1679c3339a361
**Fixed** - https://screencast-o-matic.com/watch/crQ1fTVQatu

Thanks

2021-09-06 05:08 UTC, KartikSuthar submitted a review, later dismissed

2021-09-06 08:10 UTC, sumitbuddyboss commented
> Hello @sumitbuddyboss
> 
> Fixed below issue so please test again and let me know if you find anything else.
> 
> Issue >
> 
> 1. Video does not allow to move in the comment but new activity comment photo allows to move in album
>    https://prnt.sc/1r3yye5
>    But the old media did not allow to move media, so kindly make sure
>    https://prnt.sc/1r3zbgq
>    **Fixed** - https://screencast-o-matic.com/watch/crQ1fFVQaOR
> 2. Group > Comment > Reply
>    If we add multiples documents in reply then the document does not appear.
>    https://www.loom.com/share/cf41bd8c943945c0bad6d195fb4eb21c
>    **Fixed** - https://screencast-o-matic.com/watch/crQ1frVQatQ
> 3. Group > Dropzone not seen when clicking on reply, the issue is only for when we upload photos and documents.
>    https://www.loom.com/share/7f5e0d7cd6374be598c1679c3339a361
>    **Fixed** - https://screencast-o-matic.com/watch/crQ1fTVQatu
> 
> Thanks

Hello @jitendrabanjara1991 

Above mentioned all the issues are resolved, for the proof please check the below video.

Video.
https://www.loom.com/share/011058da3db447fa98fa430b1b142cc7

Thank you

2021-09-06 10:37 UTC, sumitbuddyboss commented
Hello @jitendrabanjara1991 

I have checked on qa-ongoing branch and now media and document comments are working same as video. 
We're not allow to add Like, Comment for the child media/doument comment and also not allow to move, edit,delete and report, photo / Document in the popup

https://www.loom.com/share/e193ffcd730b4a7393389bf176efce3e
https://www.loom.com/share/37348599c4f84221b142749c54736277

 
**Note:**
When we upload media or document in qa-ongoing branch and then revert to release branch, at that time media is not appear on front side. Document is appear on the font side because for the document not using any image source of the display purpose.

https://www.loom.com/share/e8ffda3ae10840d4bc38d7e029d0a06e

Please let us know your thoughts

cc @sourabhmatolia @chetansatasiya @KartikSuthar 


Thank you

2021-09-06 12:29 UTC, jitendrabanjara1991 commented
Dependent task( buddyboss/buddyboss-platform-api#314 ) is remaining from QA side. So that's why moving this task to **Sprint 2021+2 (Scrum: Platform)** to  **Sprint 2021+3 (Scrum: Platform)**.
cc - @sourabhmatolia @firozwp @sumitbuddyboss 
Thanks.

2021-09-07 12:12 UTC, jitendrabanjara1991 commented
@sumitbuddyboss 
One pint also check from your side - For old comment( Media/document), when open popup then we removed reply button. Please check screenshot - https://prnt.sc/1rhc5eg and test it.
Thanks.

2021-09-07 14:03 UTC, sumitbuddyboss commented
Hello @jitendrabanjara1991 @KartikSuthar 

I found another issue,

**Issue 1**
If we open activity in the popup and close then click on comment then the like and comment button appears in the child comment, for the proof please check the video.

**Issue 2**
Some time Comment button not working in the activity.

Issue video:
https://www.loom.com/share/6fa6b6637dfa49d1b4322dc4a3dcfe95


Thank you

2021-09-07 15:59 UTC, jitendrabanjara1991 commented
@sumitbuddyboss 
Thanks for the finding this one. I have checked it and this is not related to this PR. Means its also replicate with release branch. Here is the video in which I have checked with release branch - https://screencast-o-matic.com/watch/crQioLVQkYe. So, Please verify with the release branch. 
@sourabhmatolia can you just add your input here - Like we need to fix both issue with this PR or create a new issue for the same.
cc - @chetansatasiya @KartikSuthar 
Thanks.

2021-09-08 11:53 UTC, jitendrabanjara1991 commented
@sumitbuddyboss
I have fixed **Issue 1** in this PR. So, Please check it. For the proof please check video - https://screencast-o-matic.com/watch/crQjX7VQ539
For **Issue 2** - Based on debugging me and @amincdev, it will take time so, you can create a new issue for the same.
cc - @chetansatasiya @KartikSuthar @sourabhmatolia
Thanks.

2021-09-08 12:07 UTC, KartikSuthar submitted a review, later dismissed

2021-09-08 13:43 UTC, sumitbuddyboss commented
Hello @jitendrabanjara1991 

I have checked issue no - 1 and it's working as expected for proof please check the below video.
https://www.loom.com/share/eabf75c211074e8e9b680af33009bcb2


**Note:**
For issue 2 we have created a new issue.
https://github.com/buddyboss/buddyboss-platform/issues/2902 

cc @sourabhmatolia

2021-09-24 09:15 UTC, JetalDobariya commented
Hello @jitendrabanjara1991 

I did verify this issue in qa-approved branch, issues is resolved one as mentioned in above thread related to Groups, and Activity child comment. Now user can not see like/comment option from child comment.
--> Activity : https://www.loom.com/i/ca6bab1522b84c7ea88b402fbf018509
--> Groups : https://www.loom.com/i/9c04704939994f34b9adb558738a1f62

Thanks!

2021-09-28 15:42 UTC, jitendrabanjara1991 commented
@sourabhmatolia 
Fixed issue like - When click on comment counts for child comments then comment form is opening. 
Here is the video for the proof - https://screencast-o-matic.com/watch/crQuo2V6mfe
cc - @chetansatasiya 
Thanks.

2021-09-30 13:48 UTC, merged