#1945 - Fix Profile field names not escaped, backslashes added
buddyboss/buddyboss-platform pull request #2845
Opened 2021-08-27 11:55 UTC by milanhirapra

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2236 .

### How to test the changes in this Pull Request:

1. BuddyBoss > Profiles > Click **Edit** button on any field
2. Update the Title like **I'm field**
3. Click on update and see the backslash is no more added

### Proof Screenshots or Video
https://vimeo.com/593235504/411f8aa96b

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-08-30 03:56 UTC, chetansatasiya approved these changes

2021-09-06 07:14 UTC, dipskakadiya requested changes
@milanhirapra `stripslashes` should be add while storing data not rending data.

2021-09-08 12:19 UTC, dipskakadiya approved these changes

2021-09-13 05:42 UTC, harshalQA commented
Not fixed

Kindly check QA comment against ticket: https://github.com/buddyboss/buddyboss-platform/issues/2236#issuecomment-917856473

2021-11-08 09:55 UTC, JetalDobariya commented
Hello @milanhirapra 

I did verify this PR in QA-Approved branch, now backslash is not appear after edit profie with some special char like " I'm "
--> https://prnt.sc/1yqz92e
--> https://prnt.sc/1yqzhy9

Thanks!
CC : @sourabhmatolia

2021-11-15 06:19 UTC, merged