#2514 - In Forum Discussion Reply, user post second GIF, it gives dup…
buddyboss/buddyboss-platform pull request #2861
Opened 2021-09-01 11:17 UTC by milanhirapra

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2514 .

### How to test the changes in this Pull Request:

1. Go to any discussion while logged in as a non admin
2. Post only GIF in reply
3. Similarly, post another different GIF in reply

### Proof Screenshots or Video
https://vimeo.com/595850783/ef30045f0c

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-09-06 07:20 UTC, dipskakadiya approved these changes
@milanhirapra Approved. Ready for testing.

2021-09-09 08:07 UTC, sumitbuddyboss commented
Hello @milanhirapra 

Issue >
I have checked in fix/2514 branch and Getting an error while uploading gif.

1. How to reproduce.
2. Goto forum 
3. add a reply
4. go to forum page 1 if you have a pagination
5. then again add a new reply with a gif
6. see the error

for the proof and how to reproduce check the below issue video.

Issue video:
https://www.loom.com/share/f0fcf25444324db397885131464d2bd8

Thank you

2021-09-09 12:55 UTC, sumitbuddyboss commented
Hello @milanhirapra 

**Fixed >**
I have checked in fix/2514 branch and cross check with @JetalDobariya @mohit-buddyboss it's working as expected for the proof please check the below video.

**Video:**
https://www.loom.com/share/16f3043993664902b4b25e65697cfaa9

Ready for release 🚀 

@milanhirapra 
Please merge this PR to qa-ongoing branch.

Thank you

2021-09-20 04:09 UTC, chetansatasiya requested changes
@milanhirapra Follow the spacing properly.

@dipskakadiya We need to make sure all the changes should follow the PHPCS properly.

2021-09-20 04:09 UTC, chetansatasiya commented on src/bp-forums/common/functions.php
> +	if( empty( $r['post_content'] ) ){
```suggestion
	if ( empty( $r['post_content'] ) ) {
```

2021-09-20 07:04 UTC, KartikSuthar approved these changes

2021-09-24 09:19 UTC, JetalDobariya commented
Hello @milanhirapra 

I did verify this PR in qa-approved branch, now if we post 2 different GIF then it is working fine.
--> https://www.loom.com/i/f0b881eab51a4e8281dc21e7ba4a2679

Thanks!

2021-09-30 14:05 UTC, merged