2301 - Fix The {{recipient.name}} email token is not working properly when used in resending the activation email
buddyboss/buddyboss-platform pull request #2872
Opened 2021-09-02 17:47 UTC by kent-carlo

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2301.

### How to test the changes in this Pull Request:
https://www.loom.com/share/ac8f5a85356345f19b14198c576b4c30

### Proof Screenshots or Video

https://www.loom.com/share/ac8f5a85356345f19b14198c576b4c30

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed {{recipient.name}} to display name instead of username

2021-09-06 07:58 UTC, dipskakadiya requested changes

2021-09-06 07:58 UTC, dipskakadiya commented on src/bp-core/classes/class-bp-email-recipient.php
> +				$name    = wp_specialchars_decode( bp_core_get_user_displayname( $this->user_object->ID ), ENT_QUOTES );
@kent-carlo In else part, `$this->user_object` is undefined.

2021-09-08 12:06 UTC, dipskakadiya requested changes

2021-09-08 12:06 UTC, dipskakadiya commented on src/bp-core/classes/class-bp-email-recipient.php
> +				$name    = wp_specialchars_decode( bp_core_get_user_displayname( $email_or_user ), ENT_QUOTES );
@kent-carlo 
`bp_core_get_user_displayname` first argument only except user id or username as I know so if it's email we need to convert it in user_id or username.

2021-09-09 14:49 UTC, dipskakadiya requested changes

2021-09-09 14:49 UTC, dipskakadiya commented on src/bp-core/classes/class-bp-email-recipient.php
> +				$user_id = get_user_by( 'email', $address )->ID;
@kent-carlo I think you need to check $user_id is found or not. if not then use email id as name.

2021-09-10 06:26 UTC, dipskakadiya approved these changes

2022-04-14 17:11 UTC, chetansatasiya approved these changes

2022-04-14 17:22 UTC, chetansatasiya approved these changes

2022-12-16 10:48 UTC, closed without merging