#2771 - Fix - Textstring "and" connecting Terms of Services and Privacy Policy is hardcoded and cannot be translated
buddyboss/buddyboss-platform pull request #2889
Opened 2021-09-06 18:32 UTC by meetmakadiya

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2771  .

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-09-07 10:30 UTC, chetansatasiya commented on src/bp-core/bp-core-catchuri.php
> +			$link        .= esc_html__( ' and ','buddyboss' );
```suggestion
			$link        .= esc_html__( ' and ', 'buddyboss' );
```

2021-09-07 10:30 UTC, chetansatasiya requested changes
Need proper spacing

2021-09-07 12:48 UTC, meetmakadiya commented on src/bp-core/bp-core-catchuri.php
> +			$link        .= esc_html__( ' and ','buddyboss' );
@chetansatasiya updated with proper space.

2021-09-08 12:13 UTC, dipskakadiya approved these changes

2021-09-20 11:36 UTC, meetmakadiya commented
Duplicate PR so I close this PR
https://github.com/buddyboss/buddyboss-platform/pull/2599

2021-09-20 11:36 UTC, closed without merging