Group & Forum settings field will not show in activity settings when group & forum deactivated
buddyboss/buddyboss-platform pull request #2890
Opened 2021-09-06 20:03 UTC by mahedihasannoman

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2725  .

### How to test the changes in this Pull Request:

1. Go to BuddyBoss setting components and disabled Social Groups and Forum Discussions modules.
2. Go to BuddyBoss Activity settings tab.
3. Find the Posts in Activity Feeds settings section.
4. Now you will not see, some of the setting options like Member creates a group, Member joins a group, Group details are updated, Member creates a forum discussion, Member replies to a forum discussion that are dependent on Group and Forum modules.

### Proof Screenshots or Video

https://www.loom.com/share/f7507297a620450f8e485b0b1c25cd87

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-09-10 07:30 UTC, dipskakadiya approved these changes

2022-04-11 14:59 UTC, chetansatasiya commented on src/bp-core/bp-core-functions.php
> +	return apply_filters( 'bp_platform_default_activity_types', $settings_fields );
all new filters should start with `bb_` instead of `bp_`

also missed the doc block of the filter with proper info.

2022-04-11 15:00 UTC, chetansatasiya requested changes
@mahedihasannoman Need requested changes

2022-11-24 11:58 UTC, jitendrabanjara1991 approved these changes

2023-03-08 12:53 UTC, merged