Activity page doesn't protected by MemberPress- Fixed
buddyboss/buddyboss-platform pull request #2904
Opened 2021-09-08 15:53 UTC by mahedihasannoman

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2755  .

### How to test the changes in this Pull Request:

1. Go to MemberPress > Memberships
2. Click on "Add New" and create a new membership
3. Go to MemberPress > Rules
4. Click on "Add New" and create a rule
5. Set Activity page in the Protected Content section and assign membership to this rule
6. See activity page is protected now.

### Proof Screenshots or Video

https://www.loom.com/share/990660449d9c4517b0d2657b3ab1d4d2

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-09-10 07:33 UTC, dipskakadiya approved these changes

2021-12-01 05:06 UTC, dipskakadiya submitted a review, later dismissed

2022-12-23 11:36 UTC, KartikSuthar requested changes

2022-12-23 11:36 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +	if ( bp_is_active( 'activity' ) && bp_is_activity_component() ) {
```suggestion
	if ( bp_is_active( 'activity' ) && bp_is_activity_component() && function_exists('is_bbpress') && is_bbpress() ) {
```

2022-12-30 08:48 UTC, KartikSuthar approved these changes

2023-03-08 12:54 UTC, merged