#2858 - fixed topics same slug tag does not add issue
buddyboss/buddyboss-platform pull request #2905
Opened 2021-09-08 18:19 UTC by sadrul

### All Submissions:

* [ ] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [ ] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #ISSUE_NUMBER .

### How to test the changes in this Pull Request:

1.
2.
3.

### Proof Screenshots or Video

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-09-10 12:46 UTC, KartikSuthar requested changes

2021-09-10 12:46 UTC, KartikSuthar commented on src/bp-forums/replies/functions.php
> +				$terms = bp_set_object_terms( $topic_id, $term_ids, bbp_get_topic_tag_tax_id(), true );
```suggestion
				$terms = wp_set_post_terms( $topic_id, $term_ids, bbp_get_topic_tag_tax_id(), true );
```

2021-09-10 12:46 UTC, KartikSuthar commented on src/bp-forums/replies/functions.php
> +			$terms = bp_set_object_terms( $topic_id, $term_ids, bbp_get_topic_tag_tax_id(), true );
```suggestion
			$terms = wp_set_post_terms( $topic_id, $term_ids, bbp_get_topic_tag_tax_id(), true );
```

2021-09-10 12:46 UTC, KartikSuthar commented on src/bp-forums/topics/functions.php
> +				bp_set_object_terms( $topic_id, $term_ids, bbp_get_topic_tag_tax_id(), true );
```suggestion
				wp_set_post_terms( $topic_id, $term_ids, bbp_get_topic_tag_tax_id(), true );
```

2021-09-10 12:46 UTC, KartikSuthar commented on src/bp-forums/topics/functions.php
> +				bp_set_object_terms( $topic_id, $term_ids, bbp_get_topic_tag_tax_id(), true );
```suggestion
				wp_set_post_terms( $topic_id, $term_ids, bbp_get_topic_tag_tax_id(), true );
```

2021-09-14 05:19 UTC, chetansatasiya requested changes
Need changes

2021-09-14 05:19 UTC, chetansatasiya commented on src/bp-forums/replies/functions.php
> +		$terms = bb_add_topic_tags( $terms, $topic_id, $topic_taxonomy );
```suggestion
		if ( ! is_array( $terms ) && strstr( $terms, ',' ) ) {
			$terms = explode( ',', $terms );
		} else {
			$terms = (array) $terms;
		}
		$terms = bb_add_topic_tags( $terms, $topic_id, bbp_get_topic_tag_tax_id() );
```

2021-09-14 05:19 UTC, chetansatasiya commented on src/bp-forums/replies/functions.php
> +	$topic_taxonomy = bbp_get_topic_tag_tax_id();
```suggestion
```

2021-09-14 05:19 UTC, chetansatasiya commented on src/bp-forums/replies/functions.php
> +	$terms = bb_add_topic_tags( $terms, $topic_id, $topic_taxonomy, $existing_terms );
```suggestion
	$terms = bb_add_topic_tags( $terms, $topic_id, bbp_get_topic_tag_tax_id(), $existing_terms );
```

2021-09-14 05:19 UTC, chetansatasiya commented on src/bp-forums/topics/functions.php
> +
```suggestion
		bb_add_topic_tags( (array) $terms[ $topic_taxonomy ], $topic_id, bbp_get_topic_tag_tax_id(), bbp_get_topic_tag_names( $topic_id ) );

```

2021-09-16 06:26 UTC, chetansatasiya submitted a review, later dismissed

2021-09-16 09:22 UTC, sadrul commented
@sumitbuddyboss @mohit-buddyboss merged into dev and qa-ongoing and ready for testing

2021-09-20 08:01 UTC, mohit-buddyboss commented
@sadrul 

Tested on qa-ongoing branch of the platform.
Now we are able to create tags having same slug and also edit/delete functionality is working fine.
Video: https://loom.com/share/6ee49a4af48741ee8ff7b4a3165e6bc4

Related issue is resolve now and PR is ready for release.

cc @sourabhmatolia @firozwp @KartikSuthar @chetansatasiya

2021-09-24 07:39 UTC, JetalDobariya commented
Hello @sadrul 

I did verify this PR on qa-approved branch, now tags are working fine when we add tags like "C , C++ , C#".
--> https://www.loom.com/i/c89f1887ad2c4d659d22ee781116b72a

Thanks!

2021-09-30 14:10 UTC, merged