#2696-fix-Title showing wrong if Rank Math SEO activated
buddyboss/buddyboss-platform pull request #2912
Opened 2021-09-09 18:14 UTC by meetmakadiya

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2696  .

### How to test the changes in this Pull Request:

1. Activate the Rank Math SEO plugin.
2. Go to the frontend user connection, feed, groups tab, and check the title.

### Proof Screenshots or Video

https://www.loom.com/share/025582bf6454454792932454b54970ae

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-09-10 06:28 UTC, dipskakadiya submitted a review, later dismissed

2021-11-17 07:09 UTC, basil-buddyboss commented
Retested in the QA ongoing branch.
Status: Not Fixed

Proof Screenshots or Video:
https://watch.screencastify.com/v/GdjzTYNT1YthCVKZJTKB

2022-01-04 08:10 UTC, KartikSuthar requested changes

2022-01-04 08:10 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-rankmath-plugin-helpers.php
> +		if ( bp_is_user() && bp_is_current_component('xprofile') ) {
```suggestion
		if ( bp_is_user() && bp_is_current_component( 'xprofile' ) ) {
```

2022-01-04 08:10 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-rankmath-plugin-helpers.php
> +	if ( bp_is_active( 'groups' ) && ! empty( buddypress()->groups->current_group ) || bp_is_current_component('groups') ) {
```suggestion
	if ( bp_is_active( 'groups' ) && ( ! empty( buddypress()->groups->current_group ) || bp_is_current_component( 'groups' ) ) ) {
```

2022-01-05 10:58 UTC, KartikSuthar approved these changes

2022-02-03 08:46 UTC, KartikSuthar approved these changes

2022-02-04 10:40 UTC, KartikSuthar commented on src/bp-core/compatibility/bp-rankmath-plugin-helpers.php
> +			}
@meetmakadiya  follow PHPCS here.

2022-02-04 10:46 UTC, meetmakadiya commented on src/bp-core/compatibility/bp-rankmath-plugin-helpers.php
> +			}
@KartikSuthar fixed the phpcs.

2022-02-08 09:23 UTC, KartikSuthar approved these changes

2022-02-23 12:50 UTC, merged