#1594 - Fix reply notification redirects to the main comments instead of the exact reply
buddyboss/buddyboss-platform pull request #2940
Opened 2021-09-15 16:32 UTC by kent-carlo

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1594.

### How to test the changes in this Pull Request:

https://www.loom.com/share/dca6561d7e9541ffba84b752dfe50982

### Proof Screenshots or Video

https://www.loom.com/share/dca6561d7e9541ffba84b752dfe50982

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Added support on navigating to the specific comment from URL hash when the loading single activity page

2021-09-28 10:46 UTC, dipskakadiya requested changes

2021-09-28 10:46 UTC, dipskakadiya commented on src/bp-templates/bp-nouveau/js/buddypress-activity.js
> +									return false;
@kent-carlo we need to add display all. Because of return might be it'll not execute `// Prepend a link to display all.` section.

2021-11-20 05:41 UTC, dipskakadiya approved these changes

2022-04-11 12:49 UTC, KartikSuthar approved these changes

2022-06-08 06:20 UTC, merged