#1172 - Fix Bug - conflict with 'Invite Anyone' plugin
buddyboss/buddyboss-platform pull request #2952
Opened 2021-09-17 11:21 UTC by kent-carlo

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #1172.

### How to test the changes in this Pull Request:
1. Install plugin "Invite Anyone"
2. Enable Learndash/BuddyBoss group syncing
3. Try to create a group, see above errors

### Proof Screenshots or Video

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

>Fixed - conflict with 'Invite Anyone' plugin

2021-09-24 12:52 UTC, dipskakadiya approved these changes

2021-09-24 13:58 UTC, chetansatasiya commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +			$bp->groups->group_creation_steps['invite-anyone']['name'] = __( 'Invite Anyone', 'invite-anyone' );
```suggestion
			$bp->groups->group_creation_steps['invite-anyone']['name'] = __( 'Invite Anyone', 'buddyboss' );
```

2021-09-24 13:58 UTC, chetansatasiya requested changes
@kent-carlo Need below changes.

1. Create a separate class for the plugin compatibility same as offload media we did.
2. Need function doc block with all the details.
3. Follow the proper translation domain.
4. Use function name prefix `bb_`

CC @dipskakadiya

2021-09-24 13:58 UTC, chetansatasiya commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +function bbp_fix_invite_anyone_overriding_bbp_invites() {
```suggestion
function bb_fix_invite_anyone_overriding_bbp_invites() {
```

2021-09-24 13:58 UTC, chetansatasiya commented on src/bp-core/compatibility/bp-incompatible-plugins-helper.php
> +function bbp_fix_invite_anyone_overriding_bbp_invites() {
Need proper doc block.

2021-09-24 15:00 UTC, kent-carlo commented
@chetansatasiya noted and thanks

2021-10-15 11:35 UTC, dipskakadiya submitted a review, later dismissed

2021-11-29 11:45 UTC, chetansatasiya requested changes
Need proper Since tags

2021-11-29 11:45 UTC, chetansatasiya commented on src/bp-core/compatibility/bp-invite-anyone-helpers.php
> + * @since BuddyBoss 1.7.8
```suggestion
 * @since BuddyBoss [BBVERSION]
```

2021-11-29 11:45 UTC, chetansatasiya commented on src/bp-core/compatibility/bp-invite-anyone-helpers.php
> +	 * @since BuddyBoss 1.7.8
```suggestion
	 * @since BuddyBoss [BBVERSION]
```

2021-11-29 11:45 UTC, chetansatasiya commented on src/bp-core/compatibility/bp-invite-anyone-helpers.php
> +	 * @since BuddyBoss 1.7.8
```suggestion
	 * @since BuddyBoss [BBVERSION]
```

2021-12-10 13:55 UTC, dipskakadiya approved these changes

2021-12-23 06:01 UTC, chetansatasiya commented on src/bp-core/compatibility/bp-invite-anyone-helpers.php
> +    public function bb_rename_send_envites_steps_for_invite_anyone() {
Add spacing properly

2021-12-23 06:02 UTC, chetansatasiya requested changes
Need phpcbf

2023-09-07 08:11 UTC, closed without merging