Fix 2287 Spammed Discussion Content with documents are removed and unable to recover after unspam
buddyboss/buddyboss-platform pull request #2977
Opened 2021-09-27 10:22 UTC by bb-yudhisthir

Mark related activity as spam if topic/reply marked as spam instead earlier was deleting it which was permanently removing attachment

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2287.

### How to test the changes in this Pull Request:

1. Go to any discussion and create a reply with the document
2. Mark as spam
3. The document gets removed and cannot be recovered even after unspam.

### Proof Screenshots or Video

https://screencast-o-matic.com/watch/crQZ6rV64fK

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Mark related activity as spam if topic/reply marked as spam

2021-09-28 11:09 UTC, dipskakadiya submitted a review, later dismissed

2022-04-20 05:41 UTC, jitendrabanjara1991 requested changes

2022-04-20 05:41 UTC, jitendrabanjara1991 commented on src/bp-forums/activity.php
> +				//Mark related activity as spam if topic marked as spam
// Mark related activity as spam if topic marked as spam.
Same thing on line no 826

2022-11-24 11:31 UTC, jitendrabanjara1991 requested changes

2022-11-24 11:31 UTC, jitendrabanjara1991 commented on src/bp-forums/activity.php
> +			} else if( bbp_get_spam_status_id() === $post->post_status ){
```suggestion
			} elseif( bbp_get_spam_status_id() === $post->post_status ) {
```

2022-11-24 11:31 UTC, jitendrabanjara1991 commented on src/bp-forums/activity.php
> +			} else if( bbp_get_spam_status_id() === $post->post_status ){
```suggestion
			} elseif( bbp_get_spam_status_id() === $post->post_status ) {
```

2022-11-24 11:31 UTC, jitendrabanjara1991 commented on src/bp-forums/activity.php
> +					return false;
```suggestion
					if ( empty( $activity->id ) ) {
						return false;
					}
```

2022-11-24 11:31 UTC, jitendrabanjara1991 commented on src/bp-forums/activity.php
> +					return false;
```suggestion
					if ( empty( $activity->id ) ) {
						return false;
					}
```

2022-11-27 06:01 UTC, jitendrabanjara1991 approved these changes

2022-12-20 10:20 UTC, merged