#2921 - Fix: New User Role Assignment doesn't stick upon initial User creation
buddyboss/buddyboss-platform pull request #2992
Opened 2021-09-29 14:19 UTC by milanhirapra

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2921 .

### How to test the changes in this Pull Request:

1. Activate plugins and theme 
2. Add a couple of basic, manually-created test users for good measure
3. Go to BuddyBoss > Components and enable all components
4. Go to BuddyBoss > Settings > Profiles > Profile Types
5. select “Enable profile types to give members unique profile fields and permissions” and update it
6. Go to BuddyBoss > Settings > Groups > Group Types
7. select “Enable group types to better organize groups enabled” and update it
8. Add a couple of Profile Types from BuddyBoss > Profile > Profile Types [Add New]
9. Go to BuddyBoss> Settings > Profiles > Profile Types
10. From the **Default Profile Type** Dropdown, select any one Profile Type from the list and save it

**Scenario 1**

1. Create a new member by going to WP > Users > Add New
2. Enter desired test user data
3. Select any role other than **Subscriber** and create it.
4. Go to WP > Users and find this user and see that the role is correct.

**Scenario 2**

1. Again Add a couple of Profile Types from BuddyBoss > Profile > Profile Types [Add New]
2. Go to the website with the admin user
3. Click on send invite button ( Go profile image in the upper right corner > Email Invites > Send Invites )
4. Send Invite - make sure to choose a profile type
5. Go to email and click on the link to register
6. Activate account after register
7. Go to WP > Users and find registered user and see that the profile type is correct.

### Proof Screenshots or Video
https://vimeo.com/617965408/edc1577e27

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-10-06 13:47 UTC, dipskakadiya approved these changes

2021-11-20 06:48 UTC, dipskakadiya requested changes

2021-11-20 06:48 UTC, dipskakadiya commented on src/bp-members/bp-members-functions.php
> +				} else {
@milanhirapra Can you run PHPCS to fix formatting?

2021-11-30 03:17 UTC, dipskakadiya approved these changes

2021-12-01 10:44 UTC, mckdlrs commented
Retested in the QA ongoing branch
Status: Not yet fixed

Proof Screenshots or Video:
https://www.loom.com/share/6ab1f38b3375498d9c8f93fdad6d99e8

2021-12-07 02:29 UTC, chetansatasiya submitted a review, later dismissed

2021-12-09 08:27 UTC, basil-buddyboss commented
Hello @milanhirapra 

Both scenarios have been tested in the QA-ongoing branch and the issue is now resolved.

**Pre-condition:**
1. All BB platform component is enabled.
2. Profile type and Group Type is enabled
3. Create a couple of profile types
4. Select a default profile type to be auto-assigned to users during registration

**To reproduce:
Scenario 1:**
1. Create a new member from the WP> Users> Add new
2. Select any WP role other than the subscriber role.
3. Go to the WP user list and check if the WP role of the user is correct.

**Scenario 2:**
1. Create a new profile type and the WP role is admin
2. Set this profile type to a user
3. Go to the profile of that user and send an email invite - make sure to choose a profile type
4. Register and activate the account
5. View the WP user list and check if the profile type assigned to the user is correct.

Video:
**Scenario 1:**
https://watch.screencastify.com/v/q8Qh4qWJCRPJ5UmnigWx
**Scenario 2:**
https://watch.screencastify.com/v/9GppCJJ1WnVgJlNGkYY1

**Status: Passed**

2021-12-16 13:46 UTC, joeytoribio commented
Hello @milanhirapra,

This has been tested in the qa-approved branch without any issues.

**Status: PASSED**

2021-12-21 15:10 UTC, sourabhmatolia commented
**UPDATE**

This is not done correctly. I will share more details later. Thanks.

2023-03-29 11:43 UTC, KartikSuthar approved these changes

2023-04-18 11:55 UTC, merged