#2947 - Fix: Profile edit > Field set issue in saving
buddyboss/buddyboss-platform pull request #3021
Opened 2021-10-06 08:23 UTC by milanhirapra

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2947 .

### How to test the changes in this Pull Request:

1. Setup fieldset with repeater and make the fields inside it required.
2. Go to User profile > edit.
3. Try adding blank fieldsets.
4. Change some of the fields and delete empty fieldsets and save them.
5. Can see deleted fieldset will delete from the user profile.

### Proof Screenshots or Video
https://vimeo.com/624258970/c200ab761a

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-11-30 03:19 UTC, dipskakadiya approved these changes

2022-04-13 12:17 UTC, KartikSuthar requested changes

2022-04-13 12:17 UTC, KartikSuthar commented on src/bp-xprofile/screens/edit.php
> +	$bp = buddypress();
remove this as its not needed.

2022-04-13 12:17 UTC, KartikSuthar commented on src/bp-xprofile/screens/edit.php
> +				$field_group_id = 0;
```suggestion
				$field_group_id = (int) bp_action_variable( 1 );
```

2022-04-13 12:17 UTC, KartikSuthar commented on src/bp-xprofile/screens/edit.php
> +				}
Remove this as its not needed.

2022-04-13 12:27 UTC, KartikSuthar approved these changes

2022-11-27 06:36 UTC, jitendrabanjara1991 approved these changes

2023-01-25 10:32 UTC, merged