PROD-709 Network search result count issue fixed
buddyboss/buddyboss-platform pull request #3099
Opened 2021-10-22 11:26 UTC by mahedihasannoman

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3094  .

### How to test the changes in this Pull Request:

1. "Blog pages show at most" set to 5 from Settings > Reading page.
2. Go to frontend and do a network search with a keyword that has more then 5 blog posts.
3. Click on the Blog Posts from left content category panel.
4. See it works fine now.

### Proof Screenshots or Video

https://watch.screencastify.com/v/dRvW1KYPo1qcHgy0slvK

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-11-20 06:18 UTC, dipskakadiya requested changes

2021-11-20 06:18 UTC, dipskakadiya commented on src/bp-search/classes/class-bp-search-posts.php
> +					'posts_per_page'	=> -1
@mahedihasannoman I don't think this is the correct solution. if will return all post. We can found count on found posts.

2021-11-29 10:06 UTC, dipskakadiya commented
@mahedihasannoman I think without any change you remove the "change requested" tag. Please check my comment.

2021-11-29 13:46 UTC, mahedihasannoman commented
> @mahedihasannoman I think without any change you remove the "change requested" tag. Please check my comment.

Hi @dipskakadiya changes added now. Please check. Thanks

2021-11-30 03:21 UTC, dipskakadiya submitted a review, later dismissed

2022-01-03 12:56 UTC, KartikSuthar requested changes

2022-01-03 12:56 UTC, KartikSuthar commented on src/bp-search/classes/class-bp-search-posts.php
> +					'posts_per_page'	=> count( $post_ids )
@mahedihasannoman @dipskakadiya We just need `- 1` here as, already used `post__in`,

```suggestion
					'posts_per_page'	=> - 1
```
```

2022-04-15 09:19 UTC, jitendrabanjara1991 approved these changes
LGTM

2022-07-21 12:44 UTC, merged