PROD-870 #2002 - Fix Moderation - Reporting Categories Breaks on WP Multisite
buddyboss/buddyboss-platform pull request #3115
Opened 2021-10-28 15:43 UTC by kent-carlo

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2002.

### How to test the changes in this Pull Request:

1. Go to a standard WP Multisite Installation.
2. Enable the moderation component in the network admin.
3. Visit the bp-moderation page or the Moderation Tab in the BuddyBoss Menu.
4. Click on Reporting Categories Tab on the top.

### Proof Screenshots or Video

https://www.loom.com/share/4ac4cc69178446049f52d25fa98e703d

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Moved moderation component into individual sites when plugin is network activated

2021-11-20 05:37 UTC, dipskakadiya approved these changes

2022-01-03 05:20 UTC, KartikSuthar commented on src/bp-core/admin/bp-core-admin-functions.php
> +			'href'  => ( is_multisite() ) ? get_admin_url( get_current_blog_id(), add_query_arg( array( 'page' => 'bp-moderation', ), 'admin.php' ) ) : bp_get_admin_url( add_query_arg( array( 'page' => 'bp-mo
```suggestion
			'href'  => ( is_multisite() ) ? get_admin_url( get_current_blog_id(), add_query_arg( array( 'page' => 'bp-moderation' ), 'admin.php' ) ) : bp_get_admin_url( add_query_arg( array( 'page' => 'bp-moderation' ), 'admin.php' ) ),
```

2022-01-03 05:20 UTC, KartikSuthar requested changes

2022-01-03 05:20 UTC, KartikSuthar commented on src/bp-core/admin/bp-core-admin-functions.php
> +		'href'  => ( is_multisite() ) ? get_admin_url( get_current_blog_id(), add_query_arg( array( 'taxonomy' => 'bpm_category', 'tab' => 'report-categories' ), 'edit-tags.php' ) ) : bp_get_admin_url( add
```suggestion
		'href' => ( is_multisite() ?
			get_admin_url(
				get_current_blog_id(),
				add_query_arg(
					array(
						'taxonomy' => 'bpm_category',
						'tab'      => 'report-categories',
					),
					'edit-tags.php'
				)
			)
			: bp_get_admin_url(
				add_query_arg(
					array(
						'taxonomy' => 'bpm_category',
						'tab'      => 'report-categories',
					),
					'edit-tags.php'
				)
			)
		),
```

2022-01-03 05:20 UTC, KartikSuthar commented on src/bp-moderation/classes/class-bp-moderation-list-table.php
> +		$blocked_members_url_base  =  add_query_arg( array( 'page' => 'bp-moderation' ), ( is_multisite() ) ? get_admin_url( get_current_blog_id(), 'admin.php') : bp_get_admin_url( 'admin.php' ) );
```suggestion
		$blocked_members_url_base  = add_query_arg( array( 'page' => 'bp-moderation' ), ( is_multisite() ) ? get_admin_url( get_current_blog_id(), 'admin.php' ) : bp_get_admin_url( 'admin.php' ) );
```

2022-12-07 07:00 UTC, chetansatasiya approved these changes

2023-03-28 06:04 UTC, closed without merging