PROD-734 #2988 Fixed mentioning in blog post comments doesn't send notifications
buddyboss/buddyboss-platform pull request #3123
Opened 2021-10-29 11:25 UTC by bb-yudhisthir

### All Submissions:
https://buddyboss.atlassian.net/browse/PROD-5126

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2988.

### How to test the changes in this Pull Request:

1. Enable the wordpress post and comments settings in the buddyboss settings > activities under "Posts in Activity Feeds"
2. Create a new sample blog
3. Comment and mention any user in the blog comment
4. View as the user you tagged, Notification should be there as well as an Email for the mention

### Proof Screenshots or Video

http://somup.com/cr6UXi3EJr

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Mentioning in blog post comments sends notifications

2021-11-01 07:23 UTC, chetansatasiya requested changes
Need PHPCS changes

2021-11-01 07:23 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> +//Action notification for mentions in single page blog comments
```suggestion
// Action notification for mentions in single page blog comments
```

2021-11-01 07:23 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> +function bb_blogs_comment_mention_notification( $activity_id, $comment, $activity_args, $activity_post_object ){
```suggestion
function bb_blogs_comment_mention_notification( $activity_id, $comment, $activity_args, $activity_post_object ) {
```

2021-11-20 06:38 UTC, dipskakadiya submitted a review, later dismissed

2021-12-03 02:24 UTC, chetansatasiya requested changes
Need changes

2021-12-03 02:24 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> +				if ( 'no' != bp_get_user_meta( $user_id, 'notification_activity_new_mention', true ) ) {
```suggestion
				if ( 'no' !== bp_get_user_meta( $user_id, 'notification_activity_new_mention', true ) ) {
```

2021-12-03 02:24 UTC, chetansatasiya commented on src/bp-activity/bp-activity-filters.php
> +					if ( $activity_id == $notification->item_id && 'new_at_mention' === $notification->component_action ) {
```suggestion
					if ( $activity_id === $notification->item_id && 'new_at_mention' === $notification->component_action ) {
```

2021-12-07 02:26 UTC, chetansatasiya approved these changes

2021-12-09 12:11 UTC, joeytoribio commented
Hi @bb-yudhisthir,

This has been tested in the qa-ongoing branch without any issues.

### Test Case#1
Mentioning in blog post comments doesn't send notification - Push Notification

**To Reproduce**
1] Enable the WordPress post and comments settings in the Buddyboss settings > activity under "Posts in Activity Feeds"
2] Create a new sample blog
3] Comment and mention any user in the blog comment
4] Make sure that the mentioned user is login in a separate browser to verify the web notification

**Remarks:** The User receives a web push notification

**Result: PASSED**

### Test Case#2
Mentioning in blog post comments doesn't send notification - Email

**To Reproduce**
1] Enable the WordPress post and comments settings in the buddyboss settings > activity under ""Posts in Activity Feeds""
2] Create a new sample blog
3] Comment and mention any user in the blog comment
4] Open tagged user's email to verify

**Remarks:** The user receives an email notification

**Result: PASSED**

### Test Case#3
Mentioning in blog post comments doesn't send notification - Notification Tab

**To Reproduce**
1] Enable the WordPress post and comments settings in the buddyboss settings > activity under "Posts in Activity Feeds"
2] Create a new sample blog
3] Comment and mention any user in the blog comment
4] View as the user you tagged and go to Notification Icon

**Remarks:** The user receives a notification in the notification bell icon

**Result: PASSED**

**Video:** 
https://www.loom.com/share/918581a3b8ef46ccadfeb20e56310d42

Thank you!

2021-12-16 05:24 UTC, basil-buddyboss commented
Hi @bb-yudhisthir 

This has been tested in the QA-approved branch including the three test cases and there were no issues encountered.

Result: Passed

2021-12-21 14:20 UTC, sourabhmatolia commented
**UPDATE**

This is not done correctly. I will share more details later. Thanks.

2023-04-07 12:12 UTC, jitendrabanjara1991 submitted a review, later dismissed

2023-05-29 09:59 UTC, merged