#311 - Fix include param for platform document API
buddyboss/buddyboss-platform pull request #3141
Opened 2021-11-07 16:16 UTC by surajkrsingh

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes https://github.com/buddyboss/buddyboss-platform-api/issues/311.

### How to test the changes in this Pull Request:

1. Pull the changes
2.  Check endpoint - `site-url/wp-json/buddyboss/v1/document?include=10`  ( e.g- document id as 10 )
3. See the response

### Proof Screenshots or Video
https://www.awesomescreenshot.com/video/5920582?key=aca06b75b795e13ec5bb84f5f86e5423

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed the include param for platform document API

2021-11-08 02:36 UTC, chetansatasiya requested changes
@surajkrsingh We have already **in** parameter so why need to add extra **include** here.

2021-11-08 03:05 UTC, surajkrsingh commented
@chetansatasiya 
As per the API document, 
it should have the `include` param  - https://www.buddyboss.com/resources/api/#api-Document-GetBBDocuments

And also if we check the consistency with another API endpoint like groups, videos and media, has `include` param. 

I didn't find the `in` param working for the document endpoints and 
the customer has created an issue because they follow the documentation.

Please let me know, your thought on this.

2021-11-08 03:08 UTC, chetansatasiya submitted a review, later dismissed

2021-11-08 05:48 UTC, KartikSuthar requested changes

2021-11-08 05:48 UTC, KartikSuthar commented on src/bp-document/bp-document-functions.php
> +			'include'             => false,        // Comma-separated list of activity IDs to include.
```suggestion
			'in'             => false,        // Comma-separated list of activity IDs to include.
```

2021-11-08 05:48 UTC, KartikSuthar commented on src/bp-document/bp-document-functions.php
> +			'include'             => $r['include'],
```suggestion
			'in'             => $r['in'],
```

2021-11-08 05:48 UTC, KartikSuthar commented on src/bp-document/classes/class-bp-document.php
> +				'include'             => false,           // Array of ids to include.
remove this

2021-11-08 05:48 UTC, KartikSuthar commented on src/bp-document/classes/class-bp-document.php
> +
Remove this as already have `in`

2021-11-08 06:49 UTC, KartikSuthar commented
@surajkrsingh 
Also need to update the API: https://github.com/buddyboss/buddyboss-platform-api/blob/release/includes/bp-document/classes/class-bp-rest-document-endpoint.php#L302
`$args['in'] = $request['include'];`

2021-11-08 07:52 UTC, surajkrsingh commented
@KartikSuthar @chetansatasiya 
Changes updated on the PR

We already making changes here - https://github.com/buddyboss/buddyboss-platform/pull/3141#discussion_r744421185
Then it's not needed here - https://github.com/buddyboss/buddyboss-platform/pull/3141#issuecomment-962858716

Tested the API result demo
![image](https://user-images.githubusercontent.com/19591301/140703534-50a4a8be-e27e-4def-ae04-5a9351baed9e.png)

2021-11-08 08:32 UTC, KartikSuthar approved these changes

2021-12-01 05:09 UTC, dipskakadiya approved these changes

2021-12-01 05:09 UTC, dipskakadiya commented
@surajkrsingh Approved. can you prepare this for QA.

2021-12-01 05:52 UTC, surajkrsingh commented
Merged into `dev` and `qa-ongoing`

2023-03-23 08:53 UTC, closed without merging