#3124 - Fix: Preview link is not working when no any keystroke or only using right-click to paste the URL
buddyboss/buddyboss-platform pull request #3151
Opened 2021-11-10 07:07 UTC by milanhirapra

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3124 .

### How to test the changes in this Pull Request:

1. Copy any link from YouTube/Vimeo
2. Go to the News Feed and paste the URL using your mouse, do not add any text or use any keyboard shortcuts
3. click post and notice the preview is working fine

### Proof Screenshots or Video
https://vimeo.com/644241225/996aa669a8

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-11-10 11:03 UTC, chetansatasiya approved these changes
LGTM 🚀

2021-11-16 08:48 UTC, aprilgeller commented
Retested on QA ongoing branch. 
Status: Not yet Fixed

Proof Video recording: https://www.loom.com/share/3117359b2ad94213a58a7a4a32090a1a

2022-01-24 06:03 UTC, KartikSuthar requested changes

2022-01-24 06:03 UTC, KartikSuthar commented on src/bp-activity/bp-activity-filters.php
> +add_filter( 'bp_activity_content_before_save', 'bb_activity_content_has_paragraph_tag' );
@milanhirapra please remove this filter its not needed.

2022-01-24 06:03 UTC, KartikSuthar commented on src/bp-activity/bp-activity-filters.php
> +}
Remove this code from here.
add it on: https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-core/classes/class-bp-embed.php#L299

```
if ( ! empty( $embed_code ) ) {

	if ( ! empty( $content ) ) {
		preg_match( '/(https?:\/\/[^\s<>"]+)/i', $content, $content_url );
		preg_match( '(<p(>|\s+[^>]*>).*?<\/p>)', $content, $content_tag );

		if ( ! empty( $content_url ) && empty( $content_tag ) ) {
			$content = sprintf( '<p>%s</p>', $content );
		}
	}

	$content .= $embed_code;
	$link_embed = true;
}
```

2022-01-24 09:28 UTC, KartikSuthar approved these changes

2022-02-08 04:19 UTC, merged