#3156 - Fixed autocomplete in group results in new activity > post in: group should be sorted by title alphabetically
buddyboss/buddyboss-platform pull request #3158
Opened 2021-11-11 13:40 UTC by kent-carlo

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3156

### How to test the changes in this Pull Request:
https://www.loom.com/share/2ca50b34cfe64796a4cdc26cef0ffb1d

### Proof Screenshots or Video

![image](https://user-images.githubusercontent.com/82648504/141307274-0eacfc29-5ab8-4f58-a918-d24860feb9a3.png)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Added code to search group autocomplete results so will be sorted alphabetically by default and changed per page to 5

2021-11-11 13:43 UTC, chetansatasiya requested changes
Need changes

2021-11-11 13:43 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/activity/ajax.php
> +				'order'	       => 'ASC'
Follow proper code alignment and spacing

2021-11-12 02:48 UTC, chetansatasiya approved these changes

2021-11-12 02:48 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/activity/ajax.php
> +				'order'	       => 'ASC'
I think you can use the **bp_before_groups_get_groups_parse_args** filter to make the changes and add the **orderby** and **order** parameters into the query. Maybe we can't change globally.

2021-11-12 02:49 UTC, chetansatasiya approved these changes

2021-11-20 05:39 UTC, dipskakadiya approved these changes

2021-12-03 11:55 UTC, gabybeldoro commented
Retested in the QA ongoing branch
Status: Fixed

Proof Screenshots or Video:
https://www.screencast.com/t/B75nUEjNRP

2021-12-06 07:36 UTC, joeytoribio commented
Hi @kent-carlo,

This has been tested in the qa-ongoing branch without any issues.

**TC Title:** 
New Activity > Post in; Group - Suggestion result is not filtered 

**TC:** 
To Reproduce
Steps to reproduce the behavior:

1] Create at least 3 groups. e.g.
    1st - titled "Group test A" with no description
    2nd - titled "Group test B" with description "Group test A"
    3rd - titled "Group test C" with description "Group test A"
2] Go to the news feed and create one.
3] Select post in: group and try searching for "Group test A"
4] You will see that groups will appear only Group test B and Group test C because Group test C and B were created later than Group test A

**Video:**
https://www.loom.com/share/b9ad9459c16040eeb4a546cf3fb86c40

**Status: Passed**

2021-12-15 07:37 UTC, basil-buddyboss commented
Hello @kent-carlo 

This has been tested in the QA-approved branch and there were no issues encountered.

Result: Pass

2021-12-22 05:18 UTC, sourabhmatolia commented
**UPDATE**

Groups per page and order issue will be fixed in Post Form task here:
https://github.com/buddyboss/buddyboss-platform/pull/3190

Closing this PR. Thanks.

2021-12-22 05:18 UTC, closed without merging