#2933 - Fix: Forum page with group associated title tag issue
buddyboss/buddyboss-platform pull request #3160
Opened 2021-11-12 10:49 UTC by milanhirapra

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #2933 .

### How to test the changes in this Pull Request:

1. Create a forum and associate it with the group.
2. Check the forum page.
3. You'll see that title gets like Discussion - Group - Site Name.

Related Issue solved:
1. Copy the forum with no group and discussion URL
2. Paste in the activity feed
3. Can see the live preview is working fine instead of https://prnt.sc/1rtktn4

### Proof Screenshots or Video
https://vimeo.com/645160371/e987c33080

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-12-01 08:20 UTC, chetansatasiya approved these changes

2021-12-02 11:35 UTC, sumitbuddyboss commented
Hello @milanhirapra 

Issue >

Getting the same issue, still the title is not updated. Check the below screenshot.
https://prntscr.com/21dyaqb

Thank you

2021-12-07 05:18 UTC, milanhirapra commented
Hello @sumitbuddyboss,

I have fixed this issue. Here is the video: https://vimeo.com/653974721/2469e53382

CC: @KartikSuthar @chetansatasiya

2021-12-07 05:33 UTC, chetansatasiya submitted a review, later dismissed

2021-12-07 06:13 UTC, KartikSuthar requested changes

2021-12-07 06:13 UTC, KartikSuthar commented on src/bp-forums/classes/class-bp-forums-component.php
> +			add_filter( 'pre_get_document_title', array( $this, 'bb_group_forums_set_title_tag' ), 999, 1);
```suggestion
			add_filter( 'pre_get_document_title', array( $this, 'bb_group_forums_set_title_tag' ), 999, 1 );
```

2021-12-08 12:33 UTC, KartikSuthar approved these changes

2021-12-09 10:50 UTC, sumitbuddyboss commented
Hello @milanhirapra 

A related both the issue is resolved, 

1. Forum page with group associated title tag issue is resolve for the proof check below video.

**Cases:**

- Verify that title tag is changed or not ? _ Pass
- Vefify after changes slug of forum - Pass
- Verify after change of permalink - Pass

**Video proof:**
https://www.loom.com/share/ec5f00bafb0f4953b6afc732d80cbf16


2. The live preview is working fine with the forum url, proof check below video.

**Video proof:**
https://www.loom.com/share/b2e78eb311cf49d7a279c9c773674c5c


Test status: **Pass**

Ready for release 🚀 

Thank you

2021-12-14 13:50 UTC, basil-buddyboss commented
Hello @milanhirapra 

This has been tested in the QA-approved branch and there were no issues encountered.

**Result: Pass**

2021-12-22 11:28 UTC, merged

2021-12-22 12:22 UTC, nickchomey commented
I'm glad to see that this was fixed, but may I ask why my feedback was ignored? Specifically, to add "- Discussions - " to the title tag?

A group can have various other tabs, be they courses, events, a knowledge base, etc... It is quite possible that these might have the same title as a forum discussion topic (e.g. A discussion related to an event or knowledgebase article). So it is necessary to include Discussions (or whatever the user has set topics to be called) in the title tag in order to distinguish them. And even if there aren't any matching topics/events/kb articles etc..., it is still useful to show the group "component" in the tag - the tag isn't just for when viewing the topic, but also for SEO purposes. 

It would be very simple to add using the code I shared in my above comment.

Another very useful addition would simply be adding a filter on the return, so that we can modify/override the default tag structure ourselves. Some might want to reverse the order or add/remove fields.

More generally, filters should be added as much as possible throughout the BB code to allow for customization. 

@mikejyoung

2021-12-22 13:25 UTC, mikejyoung commented
@nickchomey 

This PR was to fix a specific bug.

Bugs can be worked on independently by our developers, as long as they are resolving predefined logic. When we need to start changing the logic or adding new filters, UI or settings, the request becomes a suggestion and needs contribution from more team members. 

We're currently in the design and planning stage of our forum update and I'll make sure to account for your suggestions while we're designing and scoping the work. However, we do have some forum improvements coming alongside BuddyBoss Theme 2.0. 

I totally agree about filters and customization. One of our major focuses of 2021/2022 has, and is, going through each of the BuddyBoss components (forums, groups, profiles, etc) and making the code more extendable and friendly to developers (including our own!). This is lengthly work as there is still a lot to be done with the code we inherited from BuddyPress and BBPress to unlock all the great suggestions that you and all our customers are bringing up.

2021-12-22 13:51 UTC, nickchomey commented
@mikejyoung thanks for the thoughtful response! I look forward to the progress you make with it all. 

However, it seems to me that my request/suggestion for this fix was a) part of fixing the bug, since the goal was to make the title tag functional while viewing the topic and with SEO and b) completely insignificant and could have been implemented in 30 seconds - we've spent more time writing comments than it would have taken to add a filter to the return, or even just add "Discussion" to the return string...