#3095 fix filtered moderated users from the bp_get_followers and bp_get_following functions
buddyboss/buddyboss-platform pull request #3201
Opened 2021-11-24 11:33 UTC by bb-yudhisthir

Added function and filters to exclude moderated users from the widget earlier the count was also counting the moderated(hidden users) in the following functions:
bp_get_followers
bp_get_following

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3095 .

### How to test the changes in this Pull Request:

Steps to reproduce the behavior:

1. Enable the Moderation Component
2. And allow members to block each other (member blocking) and enable the auto suspend on 1 time blocking from the Moderation Settings( Buddyboss > Settings > Moderation )
3. Login as few multiple members with View As and click Follow
4. Get back to the admin account and add the (BB) Members Following Me Widget to the Activity Page Sidebar
5. Check the follower count in widget should be equal to the numbers of members avatar is showing in the widget
6. Now suspend or block the user by going to their profile page and clicking on block and check

### Proof Screenshots or Video
https://somup.com/crXZX20YDi

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Added function and filters to exclude moderated(hidden) users from the widget

2021-11-29 09:47 UTC, dipskakadiya requested changes

2021-11-29 09:47 UTC, dipskakadiya commented on src/bp-moderation/classes/suspend/class-bp-suspend-member.php
> +		add_filter( 'bp_get_followers', array( $this, 'bb_exclude_moderated_user_ids' ), 9999, 1 );
@bb-yudhisthir We should exclude users from queries. I think that is the optimized way. This way will create an issue if the hidden user list is very long.

2021-12-10 14:39 UTC, dipskakadiya approved these changes

2021-12-31 06:22 UTC, chetansatasiya approved these changes

2022-10-27 13:37 UTC, merged