#3188 : Group > Private message > All the users are not displayed
buddyboss/buddyboss-platform pull request #3206
Opened 2021-11-25 10:37 UTC by milanhirapra

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3188 .

### How to test the changes in this Pull Request:

1. Go to 'Group private message'
2. Scroll down 'user list'
3. See error

**NOTE:** If users blocked then it does affect on total user count. 
- Sumit mentioned in this issue, The group has 1251 users and Send message screen appears 1221 count. 
=> The reason is bp_group_members table has duplicate user entry so, the total count appears 1251 instead of actual user count.

### Proof Screenshots or Video
https://vimeo.com/649891810/8586f36d9c

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-11-26 02:22 UTC, chetansatasiya requested changes
Remove `getMemberOnScroll` blank function as no needed.

2021-11-26 02:22 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
> +		},
@milanhirapra Not needed

2021-12-01 02:38 UTC, chetansatasiya requested changes
Need changes

2021-12-01 02:38 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/js/buddypress-group-messages.js
> +				if ( $(membersDiv).length ) {
```suggestion
				if ( $( membersDiv ).length ) {
```

2021-12-01 08:27 UTC, chetansatasiya approved these changes

2021-12-01 14:55 UTC, sumitbuddyboss commented
Hello @milanhirapra 

Fixed >
Now all the members are displayed for the proof please check the below video.

Video:
https://www.loom.com/share/0ee419056b3a473fa9aed1879e89c7fe

Test Result:  Pass

Ready for release 🚀 

Thank you

2021-12-14 10:27 UTC, basil-buddyboss commented
Hi @milanhirapra 

This has been tested in the QA-approved branch without any issues encountered.

Result: Pass

2021-12-22 11:28 UTC, merged