#3163 - Fixed users are not being added to the Social Groups that are associated to the enrolled courses
buddyboss/buddyboss-platform pull request #3230
Opened 2021-12-09 16:06 UTC by kent-carlo

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes #3163.

### How to test the changes in this Pull Request:

Prerequisite plugins:
- LearnDash LMS
- BuddyPress for LearnDash
- BuddyBoss Platform / BuddyPress

**To Reproduce**
Steps to reproduce the behavior:
1. Create at least 3 courses, with free Access mode, and associate them separately to a Social Group.
2. Now, create a LearnDash group and associate the courses you have created with this LD group.
3. Save your changes.
4. Go to the Users tab of the LD group you created and add a user.
5. Then, log in using the user you have added to the LD group.
6. Notice that he was able to have all the 3 courses but he was not added to the associated Social Groups.

https://www.loom.com/share/899424c433fb480f8dd9103cf6d6b30a

### Proof Screenshots or Video

[](https://www.loom.com/share/899424c433fb480f8dd9103cf6d6b30a)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Fixed users are not being added to the Social Groups that are associated to the enrolled courses

2021-12-10 13:59 UTC, dipskakadiya approved these changes

2021-12-10 14:01 UTC, dipskakadiya requested changes

2021-12-10 14:01 UTC, dipskakadiya commented on src/bp-integrations/learndash/bp-learndash-filters.php
> +//user is removed from ld group
@kent-carlo We should not inline function. It'll restrict to overwrite or remove an action if needed in the future.

2022-05-06 13:40 UTC, chetansatasiya submitted a review, later dismissed

2022-10-10 09:58 UTC, chetansatasiya submitted a review, later dismissed

2023-07-18 04:49 UTC, closed without merging