Enhancement Update the Forum reply count, post count, scrubber count, and pagination to be the same --- For Theme 2.0
buddyboss/buddyboss-platform pull request #3263
Opened 2021-12-28 13:49 UTC by krunal-buddyboss

### All Submissions:

* [x] Have you followed the [Pull Requests Guidelines](https://github.com/buddyboss/buddyboss-platform/wiki/Submitting-Pull-Requests#pull-request-guidelines)?
* [x] Does your code follow the [WordPress' Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes https://github.com/buddyboss/buddyboss-theme/issues/1851

### How to test the changes in this Pull Request:

**Problem:**

When viewing a forum discussion, the count is wrong.... literally everywhere except for the admin:

- In the admin and database, the discussion topic is store separate from its replies. In the frontend when you view reply counts, and pagination, the discussion topic is magically included in the reply count.
- In the frontend, the pagination is only using top-level replies
- In the frontend, the scrubber uses the discussion topic, and all of its replies including nested replies in its Posts count
- In the frontend, the scrubber is resetting back to 1 on every page in pagination
- In the frontend, the scrubber is showing an incorrect total reply/post count on every page in pagination
- In the frontend, the reply count in the Forums view is always wrong (offset by 1)
- There are 4 different counts in frontend, and literally every single one is wrong always

**Solution:**

EVERYTHING needs to line up with what is in the admin and database!

1. In forum listing, the number of replies should be exactly the same number as in the admin: https://www.loom.com/share/69e3326e576a4d35a34a4bd6e85676bb

2. In single discussion, the Posts count should be renamed to Replies and it should be exactly the same number as in the admin: https://www.loom.com/share/0701884075644ea0b6a3cb4aac2cabd8

3. In single discussion, the pagination should be actually paginating by reply count, and should be the correct number of replies: https://www.loom.com/share/03c8d2a5a45a4b6ab4ddbfd345815ecb

4. In single discussion, change the scrubber text from "1 of 22 posts" to "1 of 22 replies". And then update the numbers to be inline with pagination, so like "1 of 31 replies" on top of page 1, "15 of 31 replies" at bottom of page 1, then "16 of 31 replies" on top of page 2, and then "31 of 31 replies at bottom of page 2, as an example. Ignore the first post which is not a reply. https://www.loom.com/share/bf8e77861e724d24989370eb5fbd49eb

5. We also need to look at the forums widgets and shortcodes and make sure they all are corrected along with this, to have correct reply counts and pagination etc.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2021-12-29 01:48 UTC, eisenwasser commented
@chetansatasiya 

Can you code review and merge these? I have already tested functionality. Theme and Platform PRs together.

https://github.com/buddyboss/buddyboss-theme/pull/1879
https://github.com/buddyboss/buddyboss-platform/pull/3263

2021-12-29 01:51 UTC, eisenwasser commented
Nevermind, still broken.

2021-12-29 09:39 UTC, chetansatasiya commented on src/bp-forums/replies/template.php
> +	$retstr = sprintf( __('Page %1$s of %2$s'), $curr_page, $total_pages );
add proper translation parameters

2021-12-29 09:39 UTC, chetansatasiya requested changes
Need requested changes

2021-12-29 10:19 UTC, chetansatasiya approved these changes

2021-12-29 11:01 UTC, KartikSuthar approved these changes

2021-12-29 23:36 UTC, eisenwasser commented
Still waiting on another change.

2021-12-30 07:21 UTC, krunal-buddyboss commented
Applied the changes as suggested above.

2022-01-05 11:05 UTC, merged