PROD-1889, PROD-1899, PROD-1920, PROD-1902, PROD-2127, PROD-1922, PROD-1921, PROD-2106 - Custom Profile & Group Layouts
buddyboss/buddyboss-platform pull request #3339
Opened 2022-02-14 13:31 UTC by krunal-buddyboss

### Jira Issue:
https://buddyboss.atlassian.net/browse/PROD-1988

https://buddyboss.atlassian.net/browse/PROD-1889
https://buddyboss.atlassian.net/browse/PROD-1899
https://buddyboss.atlassian.net/browse/PROD-1920
https://buddyboss.atlassian.net/browse/PROD-1902
https://buddyboss.atlassian.net/browse/PROD-2127
https://buddyboss.atlassian.net/browse/PROD-1922
https://buddyboss.atlassian.net/browse/PROD-1921
https://buddyboss.atlassian.net/browse/PROD-2106

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2022-02-21 04:41 UTC, chetansatasiya commented on src/bp-core/admin/bp-core-admin-functions.php
> +	$data = isset( $_POST['bp-member-type'] ) ? $_POST['bp-member-type'] : array(); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotValidated, WordPress.Security.ValidatedSanitizedInp
don't make the warning silence. Use the sanitizing functions

2022-02-21 04:41 UTC, chetansatasiya commented on src/bp-core/admin/bp-core-admin-functions.php
> +	$enable_group_type_enable_invite = isset( $_POST['bp-member-type-enabled-invite'] ) ? $_POST['bp-member-type-enabled-invite'] : ''; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNo
don't make the warning silence. Use the sanitizing functions

2022-02-21 04:42 UTC, chetansatasiya requested changes
Follow the PHPCS properly and remove the all the PHPCS silence comments.

2022-03-01 14:19 UTC, KartikSuthar requested changes

2022-03-01 14:19 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/groups/groups-loop.php
> +							<h4><span class="target_name"><?php echo esc_html__( 'Leave Group', 'buddyboss' ); ?></span></h4>
```suggestion
							<h4><span class="target_name"><?php esc_html_e( 'Leave Group', 'buddyboss' ); ?></span></h4>
```

2022-03-01 14:19 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/groups/groups-loop.php
> +							<p><?php echo esc_html__( 'Are you sure you want to leave ', 'buddyboss' ); ?><span class="bb-group-name"></span></p>
```suggestion
							<p><?php esc_html_e( 'Are you sure you want to leave ', 'buddyboss' ); ?><span class="bb-group-name"></span></p>
```

2022-03-01 14:19 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/groups/groups-loop.php
> +							<a class="bb-close-leave-group bb-close-action-popup" href="#"><?php echo esc_html__( 'Cancel', 'buddyboss' ); ?></a>
```suggestion
							<a class="bb-close-leave-group bb-close-action-popup" href="#"><?php echo esc_html_e( 'Cancel', 'buddyboss' ); ?></a>
```

2022-03-01 14:19 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/groups/groups-loop.php
> +							<a class="button push-right bb-confirm-leave-group" href="#"><?php echo esc_html__( 'Confirm', 'buddyboss' ); ?></a>
```suggestion
							<a class="button push-right bb-confirm-leave-group" href="#"><?php esc_html_e( 'Confirm', 'buddyboss' ); ?></a>
```

2022-03-01 14:19 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/groups/single/cover-image-header.php
> +						esc_attr__( 'Active %s', 'buddyboss' ),
```suggestion
						esc_html__( 'Active %s', 'buddyboss' ),
```

2022-03-02 09:31 UTC, milanhirapra commented on src/bp-core/bp-core-update.php
> +	if ( function_exists( 'buddyboss_theme' ) && version_compare( $bb_theme_version, '1.8.7', '>=' ) ) {
Its release in 1.8.7.

2022-03-02 10:50 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/groups/groups-loop.php
> +}
Remove this code, add corectly here: https://github.com/buddyboss/buddyboss-platform/pull/3339/files#diff-da4134c9b4d6993bbb5f8450b6676f905ba0e0b59de3ba349c62ddd6f8a46a0eR64
`'cover-' . $group_cover_height`

2022-03-02 10:51 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/groups/groups-loop.php
> +							<div class="bs-group-cover only-grid-view <?php echo esc_attr( $has_default_cover . ' ' . $group_cover_height_class ); ?>"><a href="<?php bp_group_permalink(); ?>"><img src="<?php echo esc_url
follow this here: https://github.com/buddyboss/buddyboss-platform/pull/3339/files#r817572973

2022-03-02 10:51 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/groups/groups-loop.php
> +						<?php } ?>
combine 2 if into one with above one.

2022-03-02 10:53 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/groups/single/cover-image-header.php
> +					<?php
```suggestion
				<?php if ( function_exists( 'bp_enable_group_hierarchies' ) && bp_enable_group_hierarchies() ) : 
```

2022-03-02 12:16 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/groups/groups-loop.php
> +								<div class="item-meta-wrap <?php echo bb_platform_group_element_enable( 'last-activity' ) || empty( $meta_privacy ) || empty( $meta_group_type ) ? 'has-meta' : 'meta-hidden'; ?> ">
Need escaping functions

2022-03-02 12:46 UTC, chetansatasiya submitted a review, later dismissed

2022-03-02 13:08 UTC, KartikSuthar approved these changes

2022-03-09 08:46 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/members/single/cover-image-header.php
> +$social_networks_urls_div_class = 'social-networks-hide';
Fix alignment here.

2022-03-09 08:48 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/members/single/member-header.php
> +	$social_networks_urls_div_class = 'social-networks-hide';
Fix alignment here.

2022-03-09 12:50 UTC, KartikSuthar approved these changes

2022-03-14 02:28 UTC, merged