PROD-3050 > Update the styling of link previews and embeds
buddyboss/buddyboss-platform pull request #3567
Opened 2022-07-18 05:56 UTC by shashank-buddyboss

### Jira Issue:
https://buddyboss.atlassian.net/browse/PROD-3050
https://buddyboss.atlassian.net/browse/PROD-3211

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2022-07-22 04:14 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/common/js-templates/activity/parts/bp-activity-link-preview.php
> +						<a data-bp-tooltip-pos="up" data-bp-tooltip="Change image" href="#" class="icon-exchange toolbar-button bp-tooltip" id="icon-exchange"><i class="bb-icon-l bb-icon-exchange"></i></a>
```suggestion
						<a data-bp-tooltip-pos="up" data-bp-tooltip="Change image" href="#" class="icon-exchange toolbar-button bp-tooltip" id="icon-exchange"><i class="bb-icon-l bb-icon-exchange"></i></a>
```

Need to add translation function in **Change image**

2022-07-22 04:15 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/buddypress/common/js-templates/activity/parts/bp-activity-link-preview.php
> +						<a data-bp-tooltip-pos="up" data-bp-tooltip="Remove image" href="#" class="icon-image-slash toolbar-button bp-tooltip" id="activity-link-preview-remove-image"><i class="bb-icon-l bb-icon-image-
```suggestion
						<a data-bp-tooltip-pos="up" data-bp-tooltip="Remove image" href="#" class="icon-image-slash toolbar-button bp-tooltip" id="activity-link-preview-remove-image"><i class="bb-icon-l bb-icon-image-slash"></i></a>
```
Need to add a translation function in **Remove image**

2022-07-25 10:10 UTC, KartikSuthar requested changes

2022-07-25 10:10 UTC, KartikSuthar commented on src/bp-activity/bp-activity-filters.php
> +	$parse_url   = parse_url( $preview_data['url'] );
```suggestion
	$parse_url   = wp_parse_url( $preview_data['url'] );
```

2022-07-25 10:42 UTC, KartikSuthar approved these changes

2022-08-17 09:51 UTC, merged