PROD-2815 strip script and style tags for the terms and privacy policy popup
buddyboss/buddyboss-platform pull request #3625
Opened 2022-09-01 10:13 UTC by bb-yudhisthir

strip script and style tags for the terms and privacy policy popup

[PROD-2815]
PROD-2815 #comment strip script and style tags for the terms and privacy policy popup

### Jira Issue:

https://buddyboss.atlassian.net/browse/PROD-2815

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2022-10-27 03:00 UTC, jitendrabanjara1991 requested changes

2022-10-27 03:00 UTC, jitendrabanjara1991 commented on src/bp-core/bp-core-catchuri.php
> +			$get_content        = apply_filters( 'bp_privacy_policy_content', wp_kses_post( $get_content ), $get_privacy_policy->post_content );
```suggestion
			$get_content        = apply_filters( 'bp_privacy_policy_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_privacy_policy->post_content ) ) ), $get_privacy_policy->post_content );
```
And remove 1525 line

2022-10-27 03:00 UTC, jitendrabanjara1991 commented on src/bp-templates/bp-nouveau/includes/template-tags.php
> +			echo apply_filters( 'bp_term_of_service_content', wp_kses_post( $get_term_content ), $get_terms->post_content );
```suggestion
			echo apply_filters( 'bp_term_of_service_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_terms->post_content ) ) ), $get_terms->post_content );
```
And remove 2611 line

2022-11-08 07:01 UTC, chetansatasiya commented on src/bp-core/bp-core-catchuri.php
> +			$get_content        = apply_filters( 'bp_privacy_policy_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_privacy_policy->post_content ) ) ), $get_privacy_
```suggestion
			$get_content        = apply_filters( 'bp_privacy_policy_content', apply_filters( 'the_content', $get_privacy_policy->post_content ), $get_privacy_policy->post_content );
```

2022-11-08 07:02 UTC, chetansatasiya commented on src/bp-core/bp-core-catchuri.php
> +			$get_term_content = apply_filters( 'bp_term_of_service_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_terms->post_content ) ) ), $get_terms->post_conten
```suggestion
			$get_term_content = apply_filters( 'bp_term_of_service_content', apply_filters( 'the_content', $get_terms->post_content ), $get_terms->post_content );
```

2022-11-08 07:04 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/template-tags.php
> +			echo apply_filters( 'bp_privacy_policy_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_privacy->post_content ) ) ), $get_privacy->post_content );
```suggestion
			echo apply_filters( 'bp_privacy_policy_content', apply_filters( 'the_content', $get_privacy->post_content ), $get_privacy->post_content );
```

2022-11-08 07:04 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/template-tags.php
> +			echo apply_filters( 'bp_privacy_policy_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_privacy->post_content ) ) ), $get_privacy->post_content );
```suggestion
			echo apply_filters( 'bp_privacy_policy_content', apply_filters( 'the_content', $get_privacy->post_content ), $get_privacy->post_content );
```

2022-11-08 07:04 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/template-tags.php
> +			echo apply_filters( 'bp_term_of_service_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_terms->post_content ) ) ), $get_terms->post_content );
```suggestion
			echo apply_filters( 'bp_term_of_service_content', apply_filters( 'the_content', $get_terms->post_content ), $get_terms->post_content );
```

2022-11-08 07:05 UTC, chetansatasiya commented on src/bp-core/bp-core-catchuri.php
> +			$get_term_content = apply_filters( 'bp_term_of_service_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_terms->post_content ) ) ), $get_terms->post_conten
```suggestion
			$get_term_content = apply_filters( 'bp_term_of_service_content', apply_filters( 'the_content', $get_terms->post_content ), $get_terms->post_content );
```

2022-11-08 07:05 UTC, chetansatasiya commented on src/bp-core/bp-core-catchuri.php
> +			$get_content = apply_filters( 'bp_privacy_policy_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_privacy->post_content ) ) ), $get_privacy->post_content
```suggestion
			$get_content = apply_filters( 'bp_privacy_policy_content', apply_filters( 'the_content', $get_privacy->post_content ), $get_privacy->post_content );
```

2022-11-08 07:05 UTC, chetansatasiya commented on src/bp-core/bp-core-catchuri.php
> +			$get_content      = apply_filters( 'bp_privacy_policy_content', wp_kses_post( bp_strip_script_and_style_tags( apply_filters( 'the_content', $get_privacy->post_content ) ) ), $get_privacy->post_con
```suggestion
			$get_content      = apply_filters( 'bp_privacy_policy_content', apply_filters( 'the_content', $get_privacy->post_content ), $get_privacy->post_content );
```

2022-11-08 07:07 UTC, chetansatasiya requested changes
Need requested changes

2023-01-31 13:43 UTC, KartikSuthar approved these changes

2023-02-21 01:31 UTC, merged