PROD-3655 - Group member able to post into group indirectly even if only allowed for Moderators/Organizers. Also modify query to exclude group in activity feed
buddyboss/buddyboss-platform pull request #3639
Opened 2022-09-15 09:22 UTC by jitendrabanjara1991

### Jira Issue:
https://buddyboss.atlassian.net/browse/PROD-3655

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2022-10-10 08:59 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/activity/functions.php
> +function bp_groups_get_join_sql_for_activity( $sql, $r ) {
```suggestion
function bb_groups_get_join_sql_for_activity( $sql, $r ) {
```

2022-10-10 08:59 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/activity/functions.php
> +function bp_groups_get_where_conditions_for_activity( $where_conditions, $r ) {
```suggestion
function bb_groups_get_where_conditions_for_activity( $where_conditions, $r ) {
```

2022-10-10 08:59 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/activity/functions.php
> +				add_filter( 'bp_groups_get_where_conditions', 'bp_groups_get_where_conditions_for_activity', 10, 2 );
```suggestion
				add_filter( 'bp_groups_get_join_sql', 'bb_groups_get_join_sql_for_activity', 10, 2 );
				add_filter( 'bp_groups_get_where_conditions', 'bb_groups_get_where_conditions_for_activity', 10, 2 );
```

2022-10-10 09:00 UTC, chetansatasiya commented on src/bp-templates/bp-nouveau/includes/activity/functions.php
> +				remove_filter( 'bp_groups_get_where_conditions', 'bp_groups_get_where_conditions_for_activity', 10, 2 );
```suggestion
				remove_filter( 'bp_groups_get_join_sql', 'bb_groups_get_join_sql_for_activity', 10, 2 );
				remove_filter( 'bb_groups_get_where_conditions', 'bp_groups_get_where_conditions_for_activity', 10, 2 );
```

2022-10-10 09:00 UTC, chetansatasiya requested changes
Need changes

2022-10-28 05:16 UTC, KartikSuthar approved these changes

2022-11-24 09:40 UTC, merged