PROD-3894
buddyboss/buddyboss-platform pull request #3686
Opened 2022-11-03 10:21 UTC by KartikSuthar

### Jira Issue:
https://buddyboss.atlassian.net/browse/PROD-3823
https://buddyboss.atlassian.net/browse/PROD-3894
https://buddyboss.atlassian.net/browse/PROD-3848

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2022-11-03 10:35 UTC, chetansatasiya approved these changes

2022-11-14 11:10 UTC, singhleo requested changes
Added Changes Request.

2022-11-14 11:10 UTC, singhleo commented on src/bp-core/classes/class-bp-user-query.php
> +				$sql['where'][] = $wpdb->prepare( 'u.date_recorded >= DATE_SUB( UTC_TIMESTAMP(), INTERVAL %d MINUTE )', $online_default_time / 60 );
try to use comparison in timestamp directly instead of converting them to minute.

2022-11-14 11:10 UTC, singhleo commented on src/bp-core/classes/class-bp-user-query.php
> +				$online_default_time = apply_filters( 'bb_default_online_presence_time', bb_presence_interval() + 5 );
extra span time should be a separate variable that should be changeable using filter.

2022-11-14 11:10 UTC, singhleo commented on src/bp-members/bp-members-functions.php
>  	if ( true === $expiry ) {
it should be if $expiry is empty. then use bb_presence_interval(). else use the time provided by $expiry variable.

2022-11-14 11:10 UTC, singhleo commented on src/bp-members/bp-members-functions.php
> +		$timeframe     = $interval_time + 5;
add the 5 sec into a variable called extra_time_span. It should be 20sec by default, considering the longest ajax call to be 20 sec.

this variable can be changeable using a filter also.

2022-11-14 22:14 UTC, singhleo approved these changes
Looks good. just check that single comment improvement else all good to go.

2022-11-14 22:14 UTC, singhleo commented on src/bp-notifications/bp-notifications-functions.php
> + * Function to check current user it offline for sending the push notification.
Return true or false telling if we can trigger a push notification to the user or not.

2022-12-02 05:40 UTC, merged