PROD-4121 : Allow members to manage their notification subscriptions
buddyboss/buddyboss-platform pull request #3729
Opened 2022-12-01 12:40 UTC by milanhirapra

### Jira Issue:

https://buddyboss.atlassian.net/browse/PROD-4121

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2022-12-27 13:48 UTC, KartikSuthar requested changes

2022-12-27 13:48 UTC, KartikSuthar commented on src/bp-forums/core/filters.php
> +		$blog_id = bp_get_root_blog_id();
remove this its not needed

2022-12-27 13:48 UTC, KartikSuthar commented on src/bp-forums/core/filters.php
> +		bb_subscriptions_update_subscriptions_status( $subscription_type, $post->ID, $subscription_status, $blog_id );
```suggestion
		bb_subscriptions_update_subscriptions_status( $subscription_type, $post->ID, $subscription_status );
```
$blog_id is optional param not needed to pass while update

2022-12-27 13:48 UTC, KartikSuthar commented on src/bp-forums/templates/default/bbpress/form-reply.php
> +									<label for="bbp_topic_subscription"><?php esc_html_e( 'Notify the author of follow-up replies via email', 'buddyboss' ); ?></label>
update the same condition here for the legacy email and the new one.

Do same for the topic as well

2022-12-27 13:48 UTC, KartikSuthar commented on src/bp-notifications/bp-notifications-settings.php
> +	<span class="forum-subscription-input"
Change the class name to target globally for all, not for the subscription specific.

2022-12-27 13:48 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/members/single/settings/subscriptions.php
> + * @since BuddyBoss [BBVERSION]
Add version here

2022-12-27 13:48 UTC, KartikSuthar commented on src/bp-templates/bp-nouveau/buddypress/members/single/parts/notification-subnav.php
> + */
Add version here

2022-12-30 13:29 UTC, KartikSuthar submitted a review, later dismissed

2023-01-03 07:39 UTC, jitendrabanjara1991 approved these changes

2023-01-03 09:13 UTC, KartikSuthar submitted a review, later dismissed

2023-01-11 09:25 UTC, KartikSuthar submitted a review, later dismissed

2023-01-20 12:33 UTC, KartikSuthar submitted a review, later dismissed

2023-01-27 11:52 UTC, KartikSuthar submitted a review, later dismissed

2023-02-03 10:51 UTC, KartikSuthar approved these changes

2023-02-07 10:43 UTC, merged