PROd-4097 -> PROD-4098 - Improve moderation for media
buddyboss/buddyboss-platform pull request #3751
Opened 2022-12-12 17:09 UTC by krunal-buddyboss

### Jira Issue:
https://buddyboss.atlassian.net/browse/PROD-4098

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2022-12-30 07:44 UTC, KartikSuthar requested changes

2023-01-02 05:48 UTC, krunal-buddyboss commented on src/bp-templates/bp-nouveau/includes/video/ajax.php
> +			if( ! empty( $video->group_id ) ) {
Fixed it

2023-01-02 05:49 UTC, krunal-buddyboss commented on src/bp-moderation/classes/suspend/class-bp-suspend-video.php
> +		if( ( isset( $args['scope'] ) && 'groups' === $args['scope'] ) || ! empty( $args['group_id'] ) ) {
Fixed it

2023-01-02 05:49 UTC, krunal-buddyboss commented on src/bp-moderation/classes/suspend/class-bp-suspend-document.php
> +		if( ( isset( $args['scope'] ) && 'groups' === $args['scope'] ) || ! empty( $args['group_id'] ) ) {
FIxed it

2023-01-02 05:49 UTC, krunal-buddyboss commented on src/bp-moderation/classes/suspend/class-bp-suspend-media.php
> +		if( ( isset( $args['scope'] ) && 'groups' === $args['scope'] ) || ! empty( $args['group_id'] ) ) {
Fixed it

2023-01-02 05:51 UTC, krunal-buddyboss commented on src/bp-moderation/classes/class-bp-moderation-members.php
> +			return ' ';
As this space needs to allow the function bp_core_get_userlink to work, I added a comment for the same as well.

2023-01-05 05:30 UTC, KartikSuthar approved these changes

2023-02-07 11:04 UTC, merged