PROD-3700
buddyboss/buddyboss-platform pull request #3935
Opened 2023-04-27 08:50 UTC by bb-yudhisthir

### Jira Issue:

https://buddyboss.atlassian.net/browse/PROD-3700
https://buddyboss.atlassian.net/browse/PROD-5233

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2023-05-05 07:03 UTC, KartikSuthar requested changes

2023-05-05 07:03 UTC, KartikSuthar commented on src/bp-media/bp-media-filters.php
> + * @param $attachment
correct the docblock

2023-05-05 07:03 UTC, KartikSuthar commented on src/bp-video/bp-video-filters.php
> + * @param $attachment
correct the docblock

2023-05-05 07:03 UTC, KartikSuthar commented on src/bp-video/bp-video-filters.php
> +				}
```suggestion
				$attachment_id = ! empty( $attachment['id'] ) && is_int( $attachment['id'] ) ? $attachment['id'] : $attachment;
```

2023-05-08 09:26 UTC, jitendrabanjara1991 approved these changes

2023-06-14 06:19 UTC, merged