# [PROD-5382]
buddyboss/buddyboss-platform pull request #4013
Opened 2023-06-20 07:33 UTC by bb-yudhisthir

# JIRA prepare commit msg > Please uncomment the line above if you want to insert JIRA ticket into commit message #PROD-5382 Admin settings to allow messaging without connection

### Jira Issue:

https://buddyboss.atlassian.net/browse/PROD-5382

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2023-06-29 09:23 UTC, KartikSuthar submitted a review, later dismissed

2023-06-29 10:21 UTC, jitendrabanjara1991 requested changes

2023-06-29 10:21 UTC, jitendrabanjara1991 commented on src/bp-templates/bp-nouveau/buddypress/groups/single/messages/private-message.php
> +					'group_id' => bp_get_current_group_id(),
```suggestion
				array(
					'sender_id'     => bp_loggedin_user_id(),
					'recipients_id' => $member->ID,
					'group_id'      => bp_get_current_group_id(),
```

2023-06-29 10:21 UTC, jitendrabanjara1991 commented on src/bp-templates/bp-nouveau/includes/groups/ajax.php
> +					)
```suggestion
					array(
						'sender_id'     => bp_loggedin_user_id(),
						'recipients_id' => $member->ID,
						'group_id'      => bp_get_current_group_id(),
					)
```

2023-06-30 10:37 UTC, KartikSuthar approved these changes

2023-07-24 11:20 UTC, merged