PROD-6214 : Profile Avatar User Initials
buddyboss/buddyboss-platform pull request #4205
Opened 2023-10-31 09:28 UTC by milanhirapra

### Jira Issue:

https://buddyboss.atlassian.net/browse/PROD-6214

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2023-11-06 09:21 UTC, KartikSuthar requested changes

2023-11-06 09:21 UTC, KartikSuthar commented on src/class-buddypress.php
> +		$this->db_version = 20764;
revert this.

2023-11-06 09:21 UTC, KartikSuthar commented on src/bp-core/bp-core-update.php
> +
remove this.

2023-11-06 09:21 UTC, KartikSuthar commented on src/bp-core/bp-core-update.php
> +}
remove this, we don't want to clear the API cache on update.
We just need to clear the cache when user changes the settings for "Default Profile Avatar" or "Default Group Avatar"
https://prnt.sc/jYPYMqk0uAkX

2023-11-06 09:21 UTC, KartikSuthar commented on src/bp-core/bp-core-functions.php
> +	}
please create a function for this which can return the object $wp_filesystem and use whenever necessary.

2024-01-02 12:43 UTC, KartikSuthar submitted a review, later dismissed

2024-01-08 09:10 UTC, KartikSuthar approved these changes

2024-02-01 06:24 UTC, jitendrabanjara1991 submitted a review, later dismissed

2024-02-21 04:41 UTC, merged