PROD-6636 - fix: while the account settings component inactive the us…
buddyboss/buddyboss-platform pull request #4254
Opened 2024-01-01 08:11 UTC by istiaq-bb

…er block action gives fatal error

### Jira Issue:
https://buddyboss.atlassian.net/browse/PROD-6636

### General Note
Keep all conversations related to this PR in the associated Jira issue(s). Do NOT add comment on this PR or edit this PR’s description.

### Notes to Developer
* Ensure the IDs (i.e. PROD-1) of all associated Jira issues are reference in this PR’s title
* Ensure that you have achieved the Definition of Done before submitting for review
* When this PR is ready for review, move the associate Jira issue(s) to “Needs Review” (or “Code Review” for Dev Tasks)

### Notes to Reviewer
* Ensure that the Definition of Done have been achieved before approving a PR
* When this PR is approved, move the associated Jira issue(s) to “Needs QA” (or “Approved” for Dev Tasks)

2024-01-01 10:00 UTC, jitendrabanjara1991 requested changes

2024-01-01 10:00 UTC, jitendrabanjara1991 commented on src/bp-moderation/bp-moderation-filters.php
> +			}
```suggestion
$response['redirect'] = bp_is_active( 'settings' ) ? trailingslashit( bp_loggedin_user_domain() . bp_get_settings_slug() ) . '/blocked-members' : bp_get_members_directory_permalink();
```

2024-01-02 08:49 UTC, jitendrabanjara1991 approved these changes

2024-01-03 04:39 UTC, KartikSuthar requested changes

2024-01-03 04:39 UTC, KartikSuthar commented on src/bp-activity/bp-activity-filters.php
> +	if ( empty( $post_id ) || empty( buddypress()->blogs ) || ! bp_is_active( 'activity' ) ) {
@istiaq-bb I'm unsure of the necessity for this condition, as it is already included in the activity filter file. If the activity is disabled, the file won't load. Please check and revert if not needed.

2024-01-03 05:40 UTC, KartikSuthar approved these changes

2024-01-24 12:24 UTC, merged